### ISSUE TITLE
Update pipeline template for v0.14.0

### ISSUE THREAD

**Issue by Kono14** [aws-samples/aws-lex-web-ui#110]
Please update the pipeline template to match version 0.14.0. 
I see the master template was updated. But the pipeline template was last updated 9 months ago and misses many of the features.

**Comment by bobpskier** [comment]
I found a couple of issues with the fullpage login and fullpage api so I'm working on an update for those. I'll push up a 0.14.1 version hopefully this weekend and will update the pipeline template as soon as that work is done and all the work has been merged back up to master. At the present time you can see a list of the new features in the development branch toplevel readme.

**Comment by Kono14** [comment]
any update on this? As far as I can see, there has been a couple updates in dev and master, but no update for the pipeline template.

**Comment by bobpskier** [comment]
I've committed and pushed the required changes up to the development branch. The next target release 0.14.4 will contain the update on master. In the interim, if you want to test using the development branch, you'll need to setup your own bootstrap bucket such that the new codecommit repo is populated from the src.zip from this bootstrap bucket.

**Comment by Kono14** [comment]
I have a hard time setting up my own s3 bootstrap bucket for the master-pipeline template. I followed the instructions in the Clouformation readme at the end. I have a working awscli, I created a new bucket, made it public, I edited `/config/env.mk` according to readme. 
But when I run `make upload` from build directory I get this cryptic error message:

```javascript
➜  build git:(development) ✗ make upload
mkdir -p "out"
[INFO] Validating templates
mkdir -p "out"
[INFO] Linting yaml syntax of template: codebuild-deploy.yaml
sed: 1: "s#\![^[:blank:]]*[[:bla ...": bad flag in substitute command: 'm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named yaml
make[1]: *** [codebuild-deploy.yaml.lint] Error 1
make: *** [upload-templates] Error 2
```

something about the `codebuild-deploy.yaml` file, which I didn't touch. It's laying in the template folder just as I cloned it from the repo here. Also a quick YAML lint check of the file showed it's content is valid.

**Comment by Kono14** [comment]
I managed to get the make script to run by re-executing it until it linted all templates. Because of course there were no errors in the templates, it's just the lint-check which fails. After that the `make upload` command executed successfully and uploaded all files to my s3 bootstrap bucket. 

After running CloudFormation with the `master-pipeline` template everything seems to work with own s3 bucket. **But** the pipeline template didn't create a CodeCommit repo and also no CodePipeline, which is the whole point this. So something in the template or my weird way of uploading to my s3 bootstrap bucket went wrong.

**Comment by bobpskier** [comment]
Super. I will get this merged into master for the next minor version release.
