### ISSUE TITLE
RespondCard Not Displaying

### ISSUE THREAD

**Issue by CathyXian** [aws-samples/aws-lex-web-ui#116]
Here is my code for display the respondcard, but it's not showing the buttons in the card:	if(lexResponse.responseCard){
			var imageElement = document.createElement("img");
			imageElement.setAttribute("src", lexResponse.responseCard.genericAttachments[0].imageUrl);
			imageElement.setAttribute("height", "80");
			imageElement.setAttribute("width", "100");
			responsePara.appendChild(imageElement);
			responsePara.appendChild(document.createElement('br'));
		}
		if (lexResponse.dialogState === 'ReadyForFulfillment') {
			responsePara.appendChild(document.createTextNode(
				'Ready for fulfillment'));
		} else {
			responsePara.appendChild(document.createTextNode(
				'(' + lexResponse.dialogState + ')'));
		}

Also, multiple messages still cannot be displayed. You can check it online: http://www.cathyxian.com/chatbot.html

**Comment by bobpskier** [comment]
Hi Cathy. I'm going to close this issue as its not related to the aws-lex-web-ui chatbot from this repository as you were referring to a different blog post about lex and a different UI. Please see my comments to you in the issue https://github.com/aws-samples/aws-lex-web-ui/issues/36 to help you get started using the aws-lex-web-ui.
