### ISSUE TITLE
Where should I add custom UI components based on input?

### ISSUE THREAD

**Issue by ASweeney22** [aws-samples/aws-lex-web-ui#117]
Hello,

I am trying to create a chatbot that pings a database and returns results into the iframe window. While I can reach the database and return data through the bot's response, I'd like to create something that would contain the results in a conatiner seperate from the chat bubbles as well as scroll through the data. 

After looking through the project, I suspect that I'd have to make edits to the action.js file in src/lex-web-ui/src/store and the Message.vue file in the nearby components directory.

Am I heading in the right direction? And what sections of the code should I focus on?

Thank you

**Comment by bobpskier** [comment]
How much data do you expect to need to return via the Lex response? I believe the max response is 25K with 12K being session attributes. Just want to make sure your response can live within these constraints. 

Can the db results be formatted using markdown and then added as part of the Lex response? If that is the case, the lex-web-ui can support this improved formatting albeit inside the message bubble. Something like a the following response using a custom payload with markdown as

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

can be formatted nicely in the current UI. 

Falling short of that, perhaps look at how the ResponseCard.vue component is used in the current design. I think adding a new TableResults.vue component that could be dynamically added to the Message.vue component might be one way to address this.

**Comment by ASweeney22** [comment]
Thank you for your response. That data isn't expected to reach that amount but it is something that could theoretically happen. Thanks for the headsup there. 

I will take a closer look at the ResponseCard.vue then, I'd rather not have the table encased in a message bubble.
