### ISSUE TITLE
Re-sync Mobile Hub deployed site files to the S3 bucket?

### ISSUE THREAD

**Issue by brorio** [aws-samples/aws-lex-web-ui#118]
I tried the (cough..) "simple" Mobile Hub deployment and of course, the deployed site causes the browser to download the file when I use the View from S3 link in the Mobil Hub.

![fireshot capture 3 - aws mobile hub_ - https___console aws amazon com_mobilehub_home](https://user-images.githubusercontent.com/39006138/47747098-d1999880-dc87-11e8-8b98-2463ea1f276a.png)

Now I am trying to follow the links and instructions such as this:

"NOTE: If the Mobile Hub deployed site causes the browser to download the files instead of rendering it, you will have to re-sync the files to the S3 bucket using the S3 console or aws cli. See the Add Mobile Hub Hosting and Streaming to Your Mobile App section of the Mobile Hub documentation for details."

The problem is that the links does not contain the content that is mentioned.

I have found the page that is probably the one metioned: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/mobile-hub-web-host-frontend.html

So I am stuck at how to re-sync. There is probably a simple solution.

![fireshot capture 2 - aws mobile hub_ - https___console aws amazon com_mobilehub_home](https://user-images.githubusercontent.com/39006138/47747117-dbbb9700-dc87-11e8-9ac3-c7a1f1a01124.png)

I also clicked the Sync files with the command line that according to the text "The Sync files with the command line link takes you to content on this page that describes how to use the command line to manage the web app and streaming media files in your bucket."

which it doesn't..

![fireshot capture 4 - aws mobile hub_ - https___console aws amazon com_mobilehub_home](https://user-images.githubusercontent.com/39006138/47747398-9481d600-dc88-11e8-8c29-315894d051ac.png)

**Comment by juandavidpalomino** [comment]
Same problem
