### ISSUE TITLE
Response cards not displaying from lambda

### ISSUE THREAD

**Issue by keodance** [aws-samples/aws-lex-web-ui#119]
I am passing dialog back with the following lambda function.  Issue #9 seems like it could be a similar problem but I am unable to decipher how to implement it into my function.  Any help would be greatly appreciated.

'use strict';

function close(sessionAttributes, fulfillmentState, message, responseCard) {
    return {
        sessionAttributes,
        dialogAction: {
            type: 'Close',
            fulfillmentState,
            message,
            responseCard,
        },
    };
}
 
// --------------- Events -----------------------
 
function dispatch(intentRequest, callback) {
    console.log(`request received for userId=${intentRequest.userId}, intentName=${intentRequest.currentIntent.name}`);
    const sessionAttributes = intentRequest.sessionAttributes;
    const esacname = intentRequest.sessionAttributes.esacname;
    var diagnosis = intentRequest.sessionAttributes.diagnosis;

    callback(close(sessionAttributes, 'Fulfilled',
    {'contentType': 'PlainText', 'content': `Thank you for completing the ESAC—which stands for
    the Early Screening for Autism and Communication Disorders for ${esacname}.`}, 
    {
      'version': `0`,
      'contentType': `application/vnd.amazonaws.card.generic`,
      'genericAttachments': [
          {
             
             'buttons':[ 
                 {
                    'text':`read step 2`,
                    'value':`welcome`
                 }
              ]
           } 
       ] 
        
    }));

}

 
// --------------- Main handler -----------------------
 
// Route the incoming request based on intent.
// The JSON body of the request is provided in the event slot.
exports.handler = (event, context, callback) => {
    try {
        dispatch(event,
            (response) => {
                callback(null, response);
            });
    } catch (err) {
        callback(err);
    }
};

**Comment by PoojaG20** [comment]
hi my card is not visible if i send it from lambda any help
