### ISSUE TITLE
incorrect URL generated when enableLogin is true

### ISSUE THREAD

**Issue by 9514Edward** [aws-samples/aws-lex-web-ui#121]
My lex-web-ui-loader-config.json file:

{
  "cognito": {
    "poolId": "us-east-1:970882cf-32XXXXXXXXXc6b5fb3d",
    "appUserPoolClientId": "dpssrvttXXXXXXX65a5p3",
    "appUserPoolName": "XXXXXXX",
    "appDomainName": "XXXXXX.auth.us-east-1.amazoncognito.com",
    "appUserPoolIdentityProvider": ""
  },
  "lex": {
    "botName": "TestBot",
    "initialText": "Under development",
    "initialSpeechInstruction": "Say nothing.",
    "reInitSessionAttributesOnRestart": false
  },
  "ui": {
    "parentOrigin": "https://www.XXXXXXX.cloud",
    "toolbarTitle": "Test Bot",
    "toolbarLogo": "",
    "enableLogin": true,
    "AllowSuperDangerousHTMLInMessage": false,
    "shouldDisplayResponseCardTitle": false,
    "pushInitialTextOnRestart": false
  },
  "polly": {
    "voiceId": "Salli"
  },
  "recorder": {
    "preset": "speech_recognition"
  },
  "iframe": {
    "iframeOrigin": "https://lex-web-ui-codebuilddeploy-hi7e32ne4-webappbucket-1XXXXXXXw7b.s3.amazonaws.com",
    "shouldLoadIframeMinimized": false,
    "iframeSrcPath": "/index.html#/?lexWebUiEmbed=true"
  }
}
The generated URL:
https://aXXXXXr.auth.us-east-1.amazoncognito.com/oauth2/authorize?redirect_uri=https%3A%2F%2Fwww.apXXXXXd%2F%3Floggedin%3Dyes&response_type=code&client_id=dpssrvtt557kc8tfqc965a5p3&state=RYvlGhgY0YLwZJ6QO7QUS1uqIuIdYxWc&scope=email%20openid%20profile

gives us redirect_mismatch error

If only we change redirect_uri=https%3A%2F%2Fwww.XXXXX.cloud%2F%3F
to redirect_uri=https%3A%2F%2Fwww.XXXXX.cloud&
the url would give no error.

The %2F%3F is "/?" which makes no sense right there.  I realize I may be using Cognito differently from how it was intended with this commit, although I'm doing straight forward per this link https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html

**Comment by bobpskier** [comment]
During CloudFormation execution, the allowable callback URL(s) are configured in the User Pools' App integration / App client settings. You can see these in the AWS Cognito Console. The sample pages at parent.html and index.html, when redirecting to the Cognito hosted login pages, need to supply valid callback URLs. The callback URLs provided by the default pages are computed based on the location the site is being served from. The redirect_mismatch error indicates either the client side is not computing the correct callback URLs or the configured Callback URL(s) in Cognito config are impropper. 

First step in is to verify the configuration in Cognito. The callback URLs defined in Cognito config should have been:

https://www.XXXXXXX.cloud/index.html?loggedin=yes, https://www.XXXXXXX.cloud/parent.html?loggedin=yes

The Sign out URL(s) should have been similar using a 'loggedout=yes'.

The AWS Cognito Console can confirm this.

If these look correct in Cognito configuration, the next step is to look at the callback url generated by the web page. It is dynamically created via javascript.

window.location.protocol + '//' + window.location.hostname + window.location.pathname + '?loggedin=yes'

This string needs to match one of the elements in the defined Cognito App client settings callback URL(s).

Please comment on which appears to be incorrect and we can investigate further. Based on your notes, it sounds like it is in the callback URL supplied by the web page but want to confirm.

**Comment by 9514Edward** [comment]
I have not coded any actual callback page yet.

I have a configuration somewhere that is causing window.location.pathname to be blank and thus I get a /? where I need ? in the javascript created callback url.

I looked at some of my other configurations.
iframeSrcPath: '/index.html#/?lexWebUiEmbed=true',  

Even though I don't have an /index.html page on my website, that is the only value for iframeSrcPath that allows the bot to generate.  Any other value results in Error: "chatbot loading time out".  My home page, the one with the bot on it is just https://www.XXXX.cloud with nothing after.

Looking at the WebAppPath in the lex-web-ui stack cloud formation stack.  This seems to be the place where /parent.html and /index.html are coming from as they are referenced in the comments although I'm not using either of those pages.  

Right now, 
WebParentOrigin is https://www.XXX.cloud
WebAppPath is blank (I guess it gets set to /index.html because I purposely left it blank or with only a forward slash to the same effect).

Suggestions on how I should configure all this?  Should I be putting an index.html on my site?  Any link to a reference on how to make this page for this purpose?

I'm misusing dot net MVC as a kind of single page app for reference as to my development environment.
