### ISSUE TITLE
Update/Increment message ID of messages

### ISSUE THREAD

**Issue by jinot92** [aws-samples/aws-lex-web-ui#122]
Hi,

I hope to populate the bot with some previous conversation once the bot loads for the first time. I am able maintain,retrieve and display the messages. But as of now, the messages which are loaded externally are being pushed down in the chat by user entered messages and the bot responses.
I am assuming this is due to the message ID every message has.
Since I am new to Vue, I would appreciate some help on how I could update/increment the id of the messages so that all the message(the ones sent by lex and the ones externally loaded) line up properly.

**Comment by bobpskier** [comment]
I think the best way to handle this would be to use the vuex store action "pushMessage" to add each of the prior messages you've loaded back into the array holding the messages during init processing. The list of messages is managed using the vuex store. To push a new message onto this list use

this.$store.dispatch('pushMessage', message);

I believe the id you mention is just the element index into an array of messages. As new messages are pushed onto the array, the id just increments by one. If you are reloading messages using their original id you are probably adding at the end of the array vs the beginning. Most likely, as the user interacts with the bot, their messages are being pushed in front of the messages you reloaded. You'll want to restore the saved messages back into the array letting the id be assigned using the "pushMessage" action in the vuex store.

**Comment by jinot92** [comment]
Where would the right place to add the logic to load previous conversation
I have added the following in LexWeb.Vue
```
this.$store.dispatch('initMessageList'),
this.$store.dispatch('loadConversation'),
```
I've the added the loadConversation in actions.js
I am able to display text message,but cannot display cards nor am I able to access the session attributes via context object.

**Comment by jinot92** [comment]
Hi @bobpskier,is there a way to continue the conversation/intent after loading the previous conversation?
