### ISSUE TITLE
Unable to use UserPool

### ISSUE THREAD

**Issue by MaheshBeri** [aws-samples/aws-lex-web-ui#124]
Using CF template I was able to create the stack correctly. (UserPool,IdentityPools etc created sucessfully)
Case 1 : Enable access to unauthenticated identities - Yes
If I go to my web ui, it is loaded. Then I hit login, I shows UserPool sign-in. I use local users and sign in. Everything works and I can login. If I check JS debug, after login idtoken are generated but it seems the UI is NOT using user pool identity but unauthenticated  identity (as confirmed  by tests below)

Case 2: Enable access to unauthenticated identities - No
(My real use case since I  want users to be authenticated)
If I go to my web ui, there is nothing. JS Debug shows error
NotAuthorizedException: Unauthenticated access is not supported for this identity pool.

Case 2b Enable access to unauthenticated identities - Yes
Cognito Identity Pool  UnAuthRole -Remove access to Lex
Now the page loads but when I post I get error in postTextMessage , so it is NOT using credentials from user pool.
AccessDeniedException: User: arn:aws:sts::XXXXXXX:assumed-role/lex-web-ui-CognitoIdentityPool-1-CognitoUnauthRole-9AA3XFPRSKQQ/CognitoIdentityCredentials is not authorized to perform: lex:PostText on resource: arn:aws:lex:us-east-1:XXXX:bot:CCCCBalance:$LATEST

NOTE:
Sometimes if I past same link into another tab, I can get bot working which uses credentials obtained from  user pool, but it is not consistent. 90% times I get above error which means it uses wrong AWSCredentials.

Question is how to  does the aws-lex-ui JS code use the new credentials after login. The code is there and idtokens are obtained. But somehow it uses the unauthenticated AWS credentials ONLY

**Comment by bobpskier** [comment]
Updated processing to switch roles between noauth and auth depending on login / logout. This is available in version 0.14.4.
