### ISSUE TITLE
Formatting the response message sent to lex

### ISSUE THREAD

**Issue by pr4shantS0naw4n3** [aws-samples/aws-lex-web-ui#130]
How am i suppose to format the response message which is sent to the lex chat bot,because the '\n' line breaking element is not working
![screenshot 1](https://user-images.githubusercontent.com/45059891/49513059-c7397280-f8b5-11e8-9825-5a905bdb57a9.png)

**Comment by bobpskier** [comment]
Ultimately you are displaying content on a web page. I think your best bet is to return markdown syntax. The lex-web-ui will support markdown returned via the Lex response.  You could respond with a message like:
<pre>
#### Your asset information 
|Property             | Value              | 
|:--------------------|-------------------:|
| Display Name                 | Apple Macbook Pro 15"  |
| Serial Number                | 123456789 |
| Wireless Mouse Serial Number | null ____      |
</pre>

**Comment by MeerZaheen** [comment]
@bobpskier I set ui.AllowSuperDangerousHTMLInMessage to "true" but I'm not sure how to configure my lambda function?

function dispatch(intentRequest, callback){
const sessionattributes = intent request.sessionattributes;
const slots = intent request.currentintent.slots;
const HUB = slots.HUB;

sessioninfo(sessionattributes, 'fullfiled', HUB)
.then(data => {
let response = data;
callback (response);
});

.catch(err => {
alert(err);
});
