### ISSUE TITLE
What is context parameter in actions.js

### ISSUE THREAD

**Issue by ilyes-hamrouni** [aws-samples/aws-lex-web-ui#135]
Sorry, i don't have access yet to the amazon account (still waiting) and i wanted to understand before i can even try, so in the actions.js all the services have a parameter called context,
```
postTextMessage(context, message) {
    return context.dispatch('interruptSpeechConversation')
      .then(() => context.dispatch('pushMessage', message))
      .then(() => context.dispatch('lexPostText', message.text))
      .then((response) => {
        // check for an array of messages
        if (response.message.includes('{"messages":')) {
          const tmsg = JSON.parse(response.message);
          if (tmsg && Array.isArray(tmsg.messages)) {
            tmsg.messages.forEach((mes, index) => {
              let alts = JSON.parse(response.sessionAttributes.appContext || '{}').altMessages;
              if (mes.type === 'CustomPayload') {
                if (alts === undefined) {
                  alts = {};
                }
                alts.markdown = mes.value;
              }
              context.dispatch(
                'pushMessage',
                {
                  text: mes.value,
                  type: 'bot',
                  dialogState: context.state.lex.dialogState,
                  responseCard: tmsg.messages.length - 1 === index // attach response card only
                    ? context.state.lex.responseCard : undefined, // for last response message
                  alts,
                },
              );
            });
          }
        } else {
          let alts = JSON.parse(response.sessionAttributes.appContext || '{}').altMessages;
          if (response.messageFormat === 'CustomPayload') {
            if (alts === undefined) {
              alts = {};
            }
            alts.markdown = response.message;
          }
          context.dispatch(
            'pushMessage',
            {
              text: response.message,
              type: 'bot',
              dialogState: context.state.lex.dialogState,
              responseCard: context.state.lex.responseCard,
              alts,
            },
          );
        }
      })
      .then(() => {
        if (context.state.lex.dialogState === 'Fulfilled') {
          context.dispatch('reInitBot');
        }
      })
      .catch((error) => {
        const errorMessage = (context.state.config.ui.showErrorDetails) ?
          ` ${error}` : '';
        console.error('error in postTextMessage', error);
        context.dispatch(
          'pushErrorMessage',
          'Sorry, I was unable to process your message. Try again later.' +
          `${errorMessage}`,
        );
      });
  },
```

that's an example however when this function is called, in inputContainer.vue 

    postTextMessage() {
      this.onInputButtonHoverLeave();
      this.textInput = this.textInput.trim();
      // empty string
      if (!this.textInput.length) {
        return Promise.resolve();
      }

      const message = {
        type: 'human',
        text: this.textInput,
      };

      return this.$store.dispatch('postTextMessage', message)
        .then(() => {
          this.textInput = '';
        });
    },

it only passes the message parameter, i don't understand this ?
PS:sorry if this is not the place, but i wanted to learn why.

**Comment by bobpskier** [comment]
The aws-lex-web-ui uses the Vuex which is a state management pattern and library for Vue.js applications. It serves as a centralized store for all the components in an application. See [Vuex](https://vuewx.vuejs.org). 

The js files in lex-web-ui/src/store all participate in the Vuex state management pattern. The actions.js file defines asynchronous store actions available to the components in the lex-web-ui. By definition action handlers receive a context object. See [Actions](https://vuex.vuejs.org/guide/actions.html). Actions are triggered with the store.dispatch method which you have shown above. This method will provide the context to the action being invoked. 

Check out the documentation at vuex.vuejs.org as this provides the best source for understanding how Vuex applications can manage state using the store.
