### ISSUE TITLE
ChatBot displays SSML text

### ISSUE THREAD

**Issue by shantang96** [aws-samples/aws-lex-web-ui#140]
Hi,

So when you send a response to Lex using a Lambda function with messageContentType set as SSML, it displays the SSML code in the text responses in chat. (see attached image below)

The speech output reads the SSML correctly, so that's working just fine.

I couldn't find any documentation on hiding this, and this should be hidden automatically in the text. 

Let me know if this is not the right place for this, my bad if it isn't.

Thank you.
<img width="405" alt="screen shot 2019-03-07 at 11 49 06 am" src="https://user-images.githubusercontent.com/10554513/53977635-0eaae700-40cf-11e9-8601-01a9b73f7ced.png">

**Comment by bobpskier** [comment]
The aws-lex-web-ui does not have direct support for SSML using the messageContentType. This feature I believe was add later to Lex. However, prior to the introduction of SSML support in Lex, the aws-lex-web-ui developed an alternate way to allow SSML from the qnabot (https://www.amazon.com/qnabot).

If you have your Lambda function add "appContext" to the Lex session attributes similar to the following json, you should be able to achieve the same result. 

```
  "appContext": {
    "altMessages": {
      "markdown": {
        "ssml": "<speak> This will be spoken by the lex web ui </speak>"
      }
    }
  }
```

At some point I I believe we will incorporate direct support of SSML via messageContentType into the aws-lex-web-ui. For now though, perhaps this is a way to work around the issue.
