### ISSUE TITLE
	The following resource(s) failed to create: [CognitoIdentityPool]. . Rollback requested by user.

### ISSUE THREAD

**Issue by vivek1may** [aws-samples/aws-lex-web-ui#141]
Hi I am trying to create a stack in aws cloud-formation. When I tried to deploy a bot I got using the template I got the following error.

The following resource(s) failed to create: [CognitoUnauthRole, CognitoAuthRole].

I used the arn role with full access for lex, lambda and power user for congito. Still I can't create the stack for the bot.

Any help is appreciated. !
Thanks in advance

**Comment by bobpskier** [comment]
You are probably missing some additional policy actions which are required. In addition to CloudFormation actions and those you listed, you'll need: iam:createRole, iam:PutRolePolicy, iam:DeleteRolePolicy, iam:DeleteRole, codebuild:CreateProject, codebuild:DeleteProject, codebuild:BatchGetProjects.

When you run the master lex-web-ui cf template, additional cf stacks are launched as child stacks. These can report failures as well. When you see a failure in the master stack be sure to look at the child stacks which will be in the Deleted state for error information.
