### ISSUE TITLE
Iframe Loader can't find config file

### ISSUE THREAD

**Issue by lecharcutier** [aws-samples/aws-lex-web-ui#142]
Hello,

i've deployer the aws-lex-web-ui product with cloud formation and i've "migrated it" on an other S3 bucket (which contain my website project)

I've the follwing on the eframe loader call 
iframe-component-loader.js:103 missing iframeSrcPath config field

I've check and the Config.json file a is well reachable. (http://www.instinct-robotique.me/lex-web-ui-loader-config.json)
And it do have the correct argument for the loader function (apparently)
Any idea :) ?

**Comment by kirstenEhlers** [comment]
is it public read?

**Comment by wcheek** [comment]
I fixed this particular issue (`missing iframeSrcPath config field`) by just including a `.` in front of the path: `"iframeSrcPath": "./index.html#/?lexWebUiEmbed=true"`
