### ISSUE TITLE
dist/lex-web-ui.js, dist/lex-web-ui.css not built

### ISSUE THREAD

**Issue by chengkiang** [aws-samples/aws-lex-web-ui#144]
I tried to do a fresh build by deleting the files in the ./dist folder, followed by running 

> npm run build-dev

However, only the following files are built:

> lex-web-ui-loader.css
> lex-web-ui-loader.css.map
> lex-web-ui-loader.js
> lex-web-ui-loader.js.map

It is missing lex-web-ui.css and lex-web-ui.js. So, when I ran 

> npm run dev

and navigate to http://localhost:8000, it's complaining about missing lex-web-ui.css and lex-web-ui.js.

Is there a way to get these files to be re-built? Or should I be using only the ones included in this repo? Thanks.

**Comment by bobpskier** [comment]
There are two supporting bash script files that assist in building. These are build/release.sh and build/upload-bootstrap.sh. These provide a repeatable process to create the required files in dist and then upload to your own bootstrap bucket. Before running upload-bootstrap.sh set BUCKET to point to the name of your S3 bucket that will hold the bootstrap files.
