### ISSUE TITLE
how to implement login page in lex-web-ui

### ISSUE THREAD

**Issue by tusharIndore** [aws-samples/aws-lex-web-ui#15]
Hi,

I want to implement login functionality in lex web ui  and after successful login i want to set user id in session attribute which i want to pass using get method. how this can be done ,Kindly let me know.

Thanks,
Tushar Choudhary

**Comment by atoa** [comment]
Hi Tushar,

The Lex web UI uses AWS credentials to authenticate to the Lex and Polly services. From your web application, you can use [Cognito User Pools](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html) to provide the login functionality and to obtain AWS credentials associated to the users. Once your application obtains AWS credentials, it can instantiate the Lex and Polly clients with the credentials from Cognito and pass the client instances to the Lex web UI.

This use case would require you to build the login functionality in your own web application and [import](https://github.com/awslabs/aws-lex-web-ui#npm-install-and-vue-component-use) the Lex web UI into your project. In this setup, the Lex web UI is consumed as an imported [library](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#library) which can be used as a Vue plugin.

The [Tracking Bot](https://github.com/awslabs/aws-ai-tracking-bot) project integrates the [Cognito hosted UI](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html) with the Lex web UI using the approach described above. You can see the integration of it in the following file: [App.vue](https://github.com/awslabs/aws-ai-tracking-bot/blob/master/dashboard-app/dashboard-app/src/App.vue).

Hope this helps.

-- Oliver

**Comment by tusharIndore** [comment]
Hi Oliver,

Can you please elaborate more ,even i don't have knowledge of "vue".Please specify the location and file which require changes for this task, also provide the code with example if possible.

Thanks,
Tushar Choudhary

**Comment by rstrahan** [comment]
+1 for integrating Cognito login to lex-web-ui (with ability to enable/disable via config)

**Comment by dileephell** [comment]
Hi if am trying to access this `http://localhost:8080/parent.html` from this `aws-lex-web-ui-master\lex-web-ui` folder then i am getting this error `iframe-component-loader.js:271 GET http://localhost:3000/admin/index.html 404 (Not Found)` in my console. But if I am trying to access the url localhost:8080/ i am able to see the bot which i have made.

My requirement is towards loading the iframe. Any help is appreciated. Thanks.

**Comment by JohnCalhoun** [comment]
we are tracking this feature in #51
