### ISSUE TITLE
A response car with video

### ISSUE THREAD

**Issue by throne1986** [aws-samples/aws-lex-web-ui#150]
Hi
I am new to Amazon aws, Is lex chat bot support video eg MP4 , ?

Assume something like this: 
Bot: would you like to watch the tutorial?
Human: Yes
Bot: displays a video 

A video can be alone or with response card .
Is this possible????

**Comment by bobpskier** [comment]
Using Lex, an Intent's Response can be configured to use Custom Markup. The Lex Web UI will render this markup and video playback will be presented. This is your easiest path for supporting video in LexWebUi. 

```
**Video playback example** - press play to start
<iframe src="https://yourlink/videos/video.mp4"></iframe>
```

![Screen Shot 2019-05-19 at 7 55 58 AM](https://user-images.githubusercontent.com/11319101/57983134-aac86700-7a0b-11e9-9dab-42b0cdeb66ab.png)

The Lex ResponseCard data type requires an Image URL. Video playback is not supported through a Lex ResponseCard at least not that I've seen. The Lex ResponseCard data type supports images and buttons. 

Alexa response cards do support ability to provide video references for playback on appropriate Alexa devices / fire tv. In this case, the Lambda handler used for an Alexa Skill would generate appropriate json based payload. [QnABot](https://www.amazon.com/qnabot) is an infrastructure that would support development of LambdaHooks to provide this mechanism for Alexa skills and Lex chatbots.
