### ISSUE TITLE
`npm run build-dist` script is not working under the lex-web-ui folder

### ISSUE THREAD

**Issue by mollyiyuyu** [aws-samples/aws-lex-web-ui#152]
I am trying to rebuild the lex-web-ui.js library. What I did was cd to the lex-web-ui directory and run `npm run build-dist`. I got an error saying ''unecpected token)" like this :
![Screen Shot 2019-05-21 at 10 05 08 AM](https://user-images.githubusercontent.com/49848029/58102838-f74ca780-7baf-11e9-9e11-c2224a1b3bc2.png)
Then I noticed an unused , in the build-dist file.
![Screen Shot 2019-05-21 at 10 05 14 AM](https://user-images.githubusercontent.com/49848029/58102955-26631900-7bb0-11e9-9869-6ea82dfab5ef.png)

After this, it looks like the building started successfully, but didn't finish as expected. Got errors like this 
![Screen Shot 2019-05-21 at 10 08 00 AM](https://user-images.githubusercontent.com/49848029/58103072-56aab780-7bb0-11e9-94dc-0808cf3355a3.png)
. 
Does antbody know why I got this error? It's saying "  Failed at the lex-web-ui@0.14.6 build-dist script 'node build/build-dist.js'" but how come previous comitts don't have this problem ...

**Comment by bobpskier** [comment]
The following steps might resolve the problem.

Make sure your branch is up to date with 'origin/master'. git status will confirm this.

Then from the root directory run
```
npm install
cd lex-web-ui
npm install
cd ../build
./release.sh
```
This should complete a full rebuild resulting in files in dist. 

package.json was updated in the current version. The npm install in both directories should bring dependent modules up to date and set package-lock.json with correct versions. The error seems to suggest a problem with package-lock.json and current installed versions in the respective node_modules folders. 

If this still fails, you can try removing package-lock.json and lex-web-ui/package-lock.json and perform an npm install in both folders again. Then cd back to the build and rerun ./release.sh.

Hopefully these steps will resolve the issue.l

**Comment by mollyiyuyu** [comment]
@bobpskier thanks for the response, I tried the commands as above. The dist foulder was created succeesffully. But still get the error saying :
/Users/nnz/Desktop/tryit/aws-lex-web-ui/lex-web-ui/build/build-dist.js:49
      );
      ^
SyntaxError: Unexpected token )

And I assume the comma is not valid here since there is only one parameter inside of the function. After I removed it, I got the bundle foulder even still having errors. 
![Screen Shot 2019-05-29 at 11 43 34 AM](https://user-images.githubusercontent.com/49848029/58571045-09a98f80-8207-11e9-8eac-65794f3a29af.png)

**Comment by bobpskier** [comment]
@mollyiyuyu which version of node is installed on your system? Using nvm I downgraded to v6.10.0 and was able to reproduce the same error. Can you try using node version v.8.16.0? That is the node version I'm building with and the build process works correctly for me.
