### ISSUE TITLE
import fails on exported json file

### ISSUE THREAD

**Issue by aaronmarkham** [aws-samples/aws-lex-web-ui#154]
I used the console to export my bot, extracted the json file from the zip file, and then used the `lex_manager.py` utility to test importing it. 
```
python lex-manager.py -i lexception_Export.json
```
This fails with:
```
[INFO] sucessfully read bot definition from file: lexception_Export.json
[ERROR] failed to import bot invalid bot_definition argument
```
Why can't it take an export and import it? I'd like to update the json file programmatically, but it isn't clear what the problem is.

**Comment by bobpskier** [comment]
The lex-manager.py was designed to be used as a custom resource using an older version of the boto3 library and a json representation that might not match that exported from the console. The better way to import the json exported from the AWS Lex console is using the aws cli. Replace YOUR_BOT_EXPORT_FILE.zip with your filename in the command below and it should start an import. 

```
aws lex-models start-import --payload fileb://./YOUR_BOT_EXPORT_FILE.zip --resource-type BOT --merge-strategy FAIL_ON_CONFLICT
```
For a description of the command you can run the following.

```
aws lex-models start-import help
```
