### ISSUE TITLE
Access Control Error on Safari (not chrome)

### ISSUE THREAD

**Issue by kirstenEhlers** [aws-samples/aws-lex-web-ui#156]
I am loading my chatbot. It works on chrome (always even after refresh). On Safari, it works the first time that the website opens on the browser. After a refresh, it does not load and gives the following errors:

[Error] Origin XXXXX is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://lex-web-ui-codebuilddeploy-vta1xvwx7-webappbucket-XXXXX.s3.amazonaws.com/lex-web-ui-loader-config.json due to access control checks.
[Error] Error: error getting chatbot UI config from url: https://lex-web-ui-codebuilddeploy-vta1xvwx7-webappbucket-XXXXX.s3.amazonaws.com/./lex-web-ui-loader-config.json
	(anonymous function) (programs:91)
	promiseReactionJob
[Error] Failed to load resource: Origin XXXXX is not allowed by Access-Control-Allow-Origin. (lex-web-ui-loader-config.json, line 0)

My JSON config has the correct parent origin (I checked).

**Comment by businessglitch** [comment]
Hey Kirsten, was wondering if you can help me know how to rebuild the files? I have made changes to the components but dont seem to see the changes when the app is running as if its accessing the old build files.

**Comment by kirstenEhlers** [comment]
When you reupload the files with chrome, make sure that you clear your cache. This can be found in advanced settings.
