### ISSUE TITLE
Custom Styles

### ISSUE THREAD

**Issue by PCrompton** [aws-samples/aws-lex-web-ui#16]
I'm not familiar with Vue.js and I can't seem to find any CSS or other styling controls for customizing the colors. I figure it should be simple but the documentation is confusing. Can anyone help me?

**Comment by atoa** [comment]
I can think of a couple of approaches:

1) Change the style in the *.vue files and rebuild the application. The style of the chatbot UI is defined within the `style` tags in the *.vue files under the [components](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui/src/components) directory. This approach requires a [build setup](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#dependencies-and-build-setup) to rebuild the files under the [lex-web-ui](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui) directory or using the [pipeline deployment mode](https://github.com/awslabs/aws-lex-web-ui/blob/master/templates/README.md#pipeline-deployment-mode) in the CloudFormation templates provided by this project to automate the build and deployment of changes.
2. Create your own CSS to override the values in the pre-built CSS. This custom CSS would need to be included after the pre-built chatbot CSS which is dynamically added as a `link` tag by the [chatbot-ui-loader.js](https://github.com/awslabs/aws-lex-web-ui/blob/1f15f61a6227464cf752e73c9c7b61e6ca29a0aa/src/website/chatbot-ui-loader.js#L144) script. Please note that many of the `style` tags in the *.vue files use [scoped css](https://vue-loader.vuejs.org/en/features/scoped-css.html) which introduces a CSS attribute in the built files that may change across builds.

Hope this clarifies it a bit. I am leaving this ticket open until a style customization section is added to the project documentation. Feel free to ask further questions or provide feedback that would help to drive this documentation or improve the style customization. Pull requests are also welcomed (including documentation).

Thanks

-- Oliver

**Comment by PCrompton** [comment]
When you say 'build' the application I'm assuming that's something different than simply running the application. I set up the pipeline deployment mode via CloudFormation, cloned the repository to my local machine, changed the Lex bot configuration from the auto-generated one to the one I want to use in `src/config/chatbot-ui-loader-config.json`, ran it on my local machine by running `node server.js` and everything seemed to work as I anticipated, with my custom bot. Then I committed the changes on master and pushed them, expecting it to work on the live site, but it's still using the auto-generated "Buy Flowers" bot. What am I doing wrong?

**Comment by atoa** [comment]
> When you say 'build' the application I'm assuming that's something different than simply running the application

You can rebuild the project from scratch on your own machine and run it locally in development mode.  This is done with the files under the `lex-web-ui` directory   See: [build setup](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#dependencies-and-build-setup).

When you run `node server.js`, it is using the pre-built dist files and the config files under `src/config`.  When you build the application, it uses a different set of config files. These config files are found under the `lex-web-ui/src/config` directory. See: [build-time configuration](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#build-time-configuration). 

The pipeline deployment mode from CloudFormation actually rebuilds the application from scratch. In this mode, you want to modify the file `lex-web-ui/src/config/config.prod.json` and commit/push it to the repo. That should trigger the pipeline and the application in your S3 bucket will be rebuilt with the new config values.

Once you have your own build version, you could substitute the pre-built files under the `dist` directory if you want to distribute it as a library. This can be done by running the `make` command inside the `dist` directory`.

Let me know if you have questions/comments/suggestions

Thanks

-- Oliver

**Comment by bigrig2212** [comment]
Suggestion: would be great if there were a version of this that didn't use a particular build system or JS framework. Something simple like static html/javascript - just so that we don't have to learn a number of new systems/frameworks to start playing around with it... Even if it were much more bare bones...

**Comment by bigrig2212** [comment]
Oh, found this: https://aws.amazon.com/blogs/machine-learning/greetings-visitor-engage-your-web-users-with-amazon-lex/. That was more what I was looking for... awesome.

**Comment by patran** [comment]
@atoa , I tried the css and was not successful changing the color, the width or any other styling.

Would you be able to show with a code sample? Where would I load the CSS and how would I override the pre-loaded values? I am using the iframe approach with the original parent.hmtl and index.html

Thanks,

**Comment by CelticRugger** [comment]
lex-web-ui.css
----------------
you can change some things Example the colour of the bubbles

.message-bot .message-bubble[data-v-46cd8705] {
  background-color: #ffebee
}

.message-human .message-bubble[data-v-46cd8705] {
  background-color: #e8eaf6
}

in the lex-web-ui-load.json  you can set some things and pass them through
  "ui": {
    "parentOrigin": "My URL",
    "toolbarTitle": "My TITLE",
    "toolbarLogo": "",
    "avatarImageUrl": "My URL Image",
    "pushInitialTextOnRestart": false,
    "toolbarColor": "purple"
  }

The rest is in the vue files (see the source) which constructs the interface, and you customize this and rebuild according to the notes i've seen. Whats really missing in this project
1. Animate bubbles (fade in or zoom in)
2. Change bubble (bot and customer) colour from configs
3. Within the popup iframe or parent to receive messages i.e. to capture the input text if typed
4. Disconnect the messaging to lex but still receive the messages from input field
5. Disconnect the microphone (turn on or off)
6. Receive a failure or fulfilment event (nothing in the docs but might be able to get that through lexupdate status not tried but should be contained in the popup ideally) so its possible to connect to a 3rd party human agent to continue chatting

Cheers

**Comment by asalria** [comment]
Hi @CelticRugger , I tried doing this but it is not working. I just modified the files on S3.
Any clue on some other thing I must change?

Thanks
