### ISSUE TITLE
Custom Front-End UI

### ISSUE THREAD

**Issue by wbhylton** [aws-samples/aws-lex-web-ui#160]
Hey all,

We're trying to change the look-and-feel of the chatbot's front-end UI. It appears that the file _lex-web-ui-loader-config.json_ contains some properties to modify background color, borders, etc. 

Is anyone aware of a list of all the UI properties that are available to be used?

**Comment by kirstenEhlers** [comment]
Toolbar: lex-web-ui-loader-config.json  ui, toolbar color
Bot Response bubble: lex-web-ui.css  .message-bot .message-bubble[data-v-46cd8705]{background-color:#ebf7ff}
User bubble: lex-web-ui.css  .message-human .message-bubble[data-v-46cd8705]{background-color:#96d5ff}
Thinking bubble: lex-web-ui.css  message-bot .message-bubble[data-v-6d624218]{background-color:#ebf7ff}.footer{

**Comment by abhilashdonepudi** [comment]
@kirstenEhlers Do we need to update these values in S3? If we do that, aren't they going to overridden by a new deployment?

**Comment by kirstenEhlers** [comment]
These are in lex-web-ui.css. They need to be changed and then uploaded to s3. They can be overridden by any changes in s3. If you want to upload a new css but use the old one you can change the link in lex-web-Ui-loader.js to a previous version link. See dependencies

**Comment by abhilashdonepudi** [comment]
@kirstenEhlers Thank you. It helped us a lot. What is the best way to make changes to lex-web-ui.js? I made changes and pushed to the repo. Codebuild deployed to S3 and the changes are not reflecting.  Any insight?

**Comment by kirstenEhlers** [comment]
Sometimes you need to clear your cached files before the upload. (Chrome settings). Also, if you have a test website, check what version of the file it is linking to in lex-web-UiI-loader.js
