### ISSUE TITLE
Pass cognito auth token from parent to child

### ISSUE THREAD

**Issue by shunyeka** [aws-samples/aws-lex-web-ui#164]
Hello,

I have and existing web application using Cognito auth https://autobot.live. It's a cloud governance application. I want to enabled lex chat for logged in users. How can I pass the loggend user auth token to the chat so that the chat can use the same auth.

**Comment by bobpskier** [comment]
Two ways that you might explore to achieve setting Lex session attributes for a jwtToken.

First is to set the token as a sessionAttribute passed to the iframeLoader something like the following.
```
var chatbotUiconfig = {
    lex: {
        sessionAttributes: {
            'jwtToken': myToken
        }
    }
};
iframeLoader.load(chatbotUiconfig);
```
Hence, when the parent page is refreshed with a valid token, the chatbot UI can be loaded with this session attribute which will be used as a session attribute for Lex. 

Second, there is some support for Cognito based logins directly in the chatbot UI. See https://github.com/aws-samples/aws-lex-web-ui/tree/master/lex-web-ui#credential-management. The end result after login with Cognito is that Lex session attributes are set for accesstokenjwt, idtokenjwt, and refreshtokenjwt which are then available on the backend. The lex-web-ui-loader-config.json cognito section supports configuration of Cognito user pool app client information in this case. 

At this point, there is no direct javascript API to call on the parent page to set a Lex session attribute. This would not be too difficult to introduce.
