### ISSUE TITLE
customizing lex response 

### ISSUE THREAD

**Issue by MeerZaheen** [aws-samples/aws-lex-web-ui#170]
I set ui.AllowSuperDangerousHTMLInMessage to "true" but I'm not sure how to configure my lambda function?

<-----lambda function---->

let output - "output" + HUB + ":\n";

ddb.query(params).promise()
 .then(data => {
  console.log("data received:". data);
  if (data.items.length <1){
   console.log("no items found");
  return resolve({
   sessionAttributes,
  dialogAction:{
  type: 'close',
  fullfillmentstate,
  "message": {
   "contentType": "PlainText",
  "content": "There are no Data"
}
}
});

**Comment by bobpskier** [comment]
There are two ways to emit content that takes advantage of either markdown or html from a lex lambda based handler. 

Lex response typically contain a _dialogAction_ with a _message_ property. The _message_ has attributes of _contentType_ and _content_. Set the _contentType_  to  'CustomPayload' and the _content_ to contain markdown. Return this as the response from your lambda handler. The is described at https://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html#using-lambda-response-format. 

The second method is to use an older technique which was specific to the lex-web-ui. You can set a session attribute named either appContext.altMessages.markdown or appContext.altMessages.html. See https://github.com/aws-samples/aws-lex-web-ui/tree/master/lex-web-ui#markdown-and-html-support.
