### ISSUE TITLE
LexWebUI as an iframe - login page using passport

### ISSUE THREAD

**Issue by MeerZaheen** [aws-samples/aws-lex-web-ui#176]
Hi,

I have a separate simple login page with nodejs and passport ldap strategy.

I want the user to login first and upon successful login, they would be redirected to either a full page lexwebui or just a blank page with the iFrame

I have the login page with passport ldap strategy already

is this possible? if so, what is the right approach?

**Comment by bobpskier** [comment]
The full page lexwebui provided in index.html does not enforce any authentication on its own. You could clone the repo and update the index.html file to validate a token passed to it when redirecting from your login page. 

Same approach in general for a page hosting the lex-web-ui iframe loader. This page could optionally display the iframe if a valid token is passed to it. If not offer a link to the login page which would provide the login facility and then redirect back to the content page after valid authentication passing in the token generated during login. The iframe should be restricted using CORS to the "parent" page hosting the iframe. 

If you have backend lambdas integrated with the Lex bot, you might also consider passing the generated token as a session attribute to Lex. This would then be made available to the Lambdas and the backend could ensure proper authentication as well. 

So, Yes it is feasible.

If you can integrate Amazon Cognito with your authentication mechanism it might also be feasible to use the built in login capability of the lex-web-ui. The token generated by Cognito will be made available on the backend as well and processing could be controlled based on availability of this token.

**Comment by MeerZaheen** [comment]
Unfortunately, I would not be able to integrate Cognito.  I do have backend lambdas and I will be integrating API gateway and lambda validation on top of LDAP authentication. However, I'm new to this approach and not sure how to move forward.
