### ISSUE TITLE
 Failed to create resource. Reason: "failed to Create bot: Parameter validation failed:\nInvalid type for parameter nextToken, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>"

### ISSUE THREAD

**Issue by biswazr** [aws-samples/aws-lex-web-ui#178]
Lexbot Resource is failed to create 

nextToken value is None and it fail to proceed .

Error 
Failed to create resource. Reason: "failed to Create bot: Parameter validation failed:\nInvalid type for parameter nextToken, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>"

**Comment by tomjames19** [comment]
@biswazr can you provide more details on the steps before this error so I can attempt to recreate?
