### ISSUE TITLE
Code pipeline not deploying the latest changes

### ISSUE THREAD

**Issue by abhilashdonepudi** [aws-samples/aws-lex-web-ui#183]
Artifacts bucket has the latest sourceoutput. But S3 webappbucket has old code. We deleted all the folders in both artifacts and webappbucket and we still see the issue. Any insight?

**Comment by tomjames19** [comment]
This might be an issue with the dist folder not being built either in the build phase or before you push to CodeCommit.  2 potential fixes 
1. Run the release.sh script in the build folder before pushing to CodeCommit
`cd build && ./release.sh`
OR
2. Make sure the Makefile in the parent directory has the following lines of code in the build phase (prefered fix)
```
build: config
	@echo "[INFO] Building loader"
	npm run build
	@echo "[INFO] Building component in dir [$(WEBAPP_DIR)]"
	cd $(WEBAPP_DIR) && npm run build  
	cd $(WEBAPP_DIR) && npm run build-dist
	@echo "[INFO Building Dist"
	cd $(DIST_DIR) && make```

Hopefully this helps

**Comment by abhilashdonepudi** [comment]
We are following step 1 at this time. We are using the code pipeline. Are you saying the above config you provided is not part of the existing pipeline?

**Comment by tomjames19** [comment]
The config in step 2 was missing in a few previous releases, if you've pulled the most recent release that config should be present.

**Comment by tomjames19** [comment]
if there are no other issues I'm going to mark this as closed
