### ISSUE TITLE
The Buttons are off-the hook - not rendered

### ISSUE THREAD

**Issue by krishnamurali88** [aws-samples/aws-lex-web-ui#185]
Dear Team,

When we integrate the lex bot with the UI, the buttons are not rendered properly. Please advice how could we make it render properly.
Please refer the attachment. 

<img width="506" alt="Issue with buttons in lex ui" src="https://user-images.githubusercontent.com/19565101/71870915-84437180-313d-11ea-9321-47fc6fc259c7.png">

Thanks,
Muralikrishna

**Comment by bobpskier** [comment]
The Lex Web Ui renders buttons based on existence of buttons in a Response Card from Lex. Normally a response card can contain up to five buttons which is what the UI is designed for. I'm wondering what the logic is on the Lex side to return 9 buttons. Only way I can think of to get this working they way it is displayed is to have three response cards with 3 buttons each. Can you confirm this is the technique? 

If you are using multiple response cards and this is working properly, you might then use five response cards.  The first four with two buttons each and the fifth with just one button. Each row I think would fit properly. 

Another approach is to increase the width of the lex web ui giving it more real estate to place the three buttons. 

Final technique is to adjust css to try and organize or make this fit better. Lex Web Ui uses Vue and the responsible component with css styling is in the source ResponseCard.vue.

The css defined in this component  is

```
.button-row {
  display: inline-block;
}

.btn {
  margin: 10px !important;
  font-size: 12px !important;
  min-width: 44px !important;
}

.card__actions.button-row {
  justify-content: center;
  padding-bottom: 0.15em;
}
```

You'll need to either fit all three buttons in a single row or allow the buttons to wrap almost as if they are in a new row. 

Do you have design preference on the three options? Five response cards would require no code changes, increasing the size of the iframe or vue component would take some adjustment in html, css would require overriding the css with a separate css file or rebuilding the project.

**Comment by krishnamurali88** [comment]
@bobpskier We have implemented based on multiple cards i.e three response cards with 3 buttons each. We tried implementing the way you suggested with the design. 

Please refer the attached which shows the way we implemented. 
[Lex_cards.docx](https://github.com/aws-samples/aws-lex-web-ui/files/4052767/Lex_cards.docx)
