### ISSUE TITLE
Upgrade Vuetify

### ISSUE THREAD

**Issue by andrewshirk** [aws-samples/aws-lex-web-ui#186]
The version of Vuetify (0.17.7) used is extremely old. Is there a plan to upgrade it? Thank you.

**Comment by pdkn** [comment]
With Vue3 coming out soon too, there might be an opportunity of a larger update.

**Comment by andrewshirk** [comment]
I'd be happy to contribute, but this project seems dead.

**Comment by tomjames19** [comment]
Hi upgrading to more recent versions of Vuetify is definitely a priority, currently our version of Vuetify is extremely old so it will require lots of testing to make sure there are no breaking changes to the new version of Vuetify.  

And no this project is not dead!

**Comment by andrewshirk** [comment]
Great to hear the project is not dead! Is there a roadmap or wishlist that I missed somewhere?

**Comment by tomjames19** [comment]
As of right now there is not, but I will add one in the near future
