### ISSUE TITLE
Intermittent issues in AWS LEX bot 

### ISSUE THREAD

**Issue by MadhuriDasa** [aws-samples/aws-lex-web-ui#189]
Hi team,
We have developed a "bot " using AWS Lex and Lambda.We have bot configured with few buttons. When we test in AWS lex, the flow works fine without any issue.

But after integrating with our custom website, we see few intermittent issues like,
1. If we click a button, sometimes it follows the flow. But sometimes it gives the end result.
2. If we click a button, sometimes it displays the custom "fallback" intent we have developed.
etc...

Please let us know where the issue and what might be it is? Is it with integration or with "bot" itself.
Thanks.
Devaki

**Comment by bobpskier** [comment]
Button clicks from a button in a response card will send a postText request back to Lex using the value in the button. You can see these requests in browser debugger when looking at network requests. Lex would take the postText request and process accordingly. Depending on the session state and required slots, Lex might prompt the user for further input before reaching fulfillment. Once in fulfillment the bot would normally process from here. Is lex session data being used to support state? Are slot values required for the intent and are these being set? What setting did you use for the LexWebUi's ReInitSessionAttributesOnRestart parameter? Is it possible to provide a url and sample input for the UI to reproduce the problem?
