### ISSUE TITLE
chatbot loading time out

### ISSUE THREAD

**Issue by himanshuladola** [aws-samples/aws-lex-web-ui#190]
S3 has been hosted with sample application, CORS policy has been configured properly to load. Me and my team working on local host so parentOrigin is different within team.
Below configuration has been provided while instantiating chat bot loader. Which should override the configuration settings and change parentOrigin.
 var chatbotUiconfig = {
      ui: {
        parentOrigin: 'http://localhost:5734'
      },
      iframe: {
        // origin hosting the HTML file that will be embedded in the iframe
        iframeOrigin: 'http://cloudhrbot.s3-eu-west-1.amazonaws.com'
      },
      lex: {
        sessionAttributes: {
          token: token,
          realmurl: keycloakUrl,
          hosturl: host
        }
      }
    };

Default JSON file hosted in S3 contains below configuration.
"ui": {
    "parentOrigin": "http://localhost:5735",
    "toolbarTitle": "Talk to Me",
    "toolbarLogo": "",
    "positiveFeedbackIntent": "",
    "negativeFeedbackIntent": "",
    "helpIntent": "help",
    "enableLogin": false,
    "AllowSuperDangerousHTMLInMessage": true,
    "shouldDisplayResponseCardTitle": false,
    "pushInitialTextOnRestart": false,
    "directFocusToBotInput": false,
    "showDialogStateIcon": false
  },
  "iframe": {
    "iframeOrigin": "http://cloudhrbot.s3.eu-west-1.amazonaws.com",
    "shouldLoadIframeMinimized": false,
    "iframeSrcPath": "/index.html#/?lexWebUiEmbed=true"
  }
However I am getting "chatbot loading time out" and no clue about same.
![image](https://user-images.githubusercontent.com/24384240/73334089-aee29f00-4291-11ea-88f0-e977f4339967.png)

When application configured to use http://localhost:5735 IFrame is getting launch successfully and below are console log from same.
![image](https://user-images.githubusercontent.com/24384240/73334254-3c25f380-4292-11ea-8337-a6436f068cc5.png)

Not sure how I can change parentOrigin runtime and also loader is taking same in account.

**Comment by YoussefKafa** [comment]
Hi @himanshuladola , Have you solved this issue?
