### ISSUE TITLE
Allow fullscreen mode to dispatch 'ready' event

### ISSUE THREAD

**Issue by pdkn** [aws-samples/aws-lex-web-ui#191]
In `@components/LexWeb.vue initConfig()`. The 'ready' event is only dispatched if embedded in iFrame

```
...
.then(() => (
        (this.$store.state.isRunningEmbedded) ?
          this.$store.dispatch(
            'sendMessageToParentWindow',
            { event: 'ready' },
          ) :
          Promise.resolve()
      ))
      .then(() => console.info(
        'sucessfully initialized lex web ui version: ',
        this.$store.state.version,
      ))
...
```
(Also, in iFrame mode, the promise isn't resolved so `console.info('sucessfully initialized lex web ui version: '...)` isn't called

There are valid scenarios for the 'fullpagecomponent' mode to also listen for a ready event. (i.e I'm relying on it to make a `lexPostText` request to get a custom welcome message from the elasticsearch knowlegebase.

I've patched this by removing the check for `this.$store.state.isRunningEmbedded`: (will put in a pull request)

```
.then(() => {
        this.$store.dispatch(
          'sendMessageToParentWindow',
          { event: 'ready' },
        );
        Promise.resolve();
 })
```

**Comment by andrewshirk** [comment]
Curious if you've tested this. What does it do for you without a parent window to post a message to?

**Comment by pdkn** [comment]
It allows me to set a custom welcome message based on session data. (It also make a more consistent api between full screen and IFrame) ;)

**Comment by andrewshirk** [comment]
I see. Thanks!

**Comment by pdkn** [comment]
It allows me to set a custom welcome message based on session parameters.

**Comment by pdkn** [comment]
I should also add, we haven’t yet decide if we will offer the chatbot as both a panel in iframe and/or a full screen version (as an option with improved accessibly)
