### ISSUE TITLE
Issue with lex-web-ui

### ISSUE THREAD

**Issue by vaibhavdubey97** [aws-samples/aws-lex-web-ui#200]
The CloudFormation stack on being launched shows the following error message:

An error occurred (AccessDeniedException) when calling the GetSlotTypes operation: User: arn:aws:sts::167046113074:assumed-role/lex-web-ui-Bot-JX2X7AMW39MV-LexBotLambdaRole-1G3CD9TGPS32/lex-web-ui-Bot-JX2X7AMW39MV-LexBotLambda-J98MF9Z9D634 is not authorized to perform: lex:GetSlotTypes on resource: arn:aws:lex:us-east-1:167046113074:slottype:*

I am not sure how to resolve this. Kindly help, if possible.

**Comment by bobpskier** [comment]
The LexBotLamdaRole is created and used in a nested stack when no bot is specified in the initial stack configuration. Looks like changes to increase the least privilege model of this nested stack caused to the GetSlotType operation to fail. Will get a fix going for this issue. 

The quick workaround is to use the Amazon Lex console to create a bot. Under "Try A Sample" pick OrderFlowers. Then at the bottom of the form select No for COPPA and then click on Create. This will build an "OrderFlowers" Bot for you. You should see the status of Ready once the Bot is available for use.

Delete the original stack that failed and then  relaunch the LexWebUi stack. This time for the parameter BotName use "OrderFlowers" or use a name of a Bot that exists from the Amazon Lex Console. It should complete successfully.

**Comment by vaibhavdubey97** [comment]
Got it. Thanks a lot! That worked for me.
