### ISSUE TITLE
Integrating with own chatbot

### ISSUE THREAD

**Issue by vaibhavdubey97** [aws-samples/aws-lex-web-ui#201]
How can I integrate the stand-alone chatbot UI with my own chatbot? While loading the cloudformation stack, I put my own chatbot's name, but the bot on the webpage is not working. The error being shown is:

![image](https://user-images.githubusercontent.com/41820607/75908170-8a09ba80-5e41-11ea-97f5-9e5c8dd75a0d.png)

**Comment by bobpskier** [comment]
Is the status of the target Lex Bot "ready"? Most likely the bot is not in the "ready" state. Any requests against the bot will fail with this error while not in the ready state. Most likely you need to build the bot in the AWS Lex Console such that the bot is put in the READY state.
