### ISSUE TITLE
Error While Deployment

### ISSUE THREAD

**Issue by sanakalam** [aws-samples/aws-lex-web-ui#209]
I want to deploy chatbot using cloud formation on my dummy web page. m getting below error :
**Error:**
Access to XMLHttpRequest at 'https://lex-web-ui-codebuilddeploy-iii2ktqlj-webappbucket-imve2dz8r4c7.s3.us-east-1.amazonaws.com/lex-web-ui-loader-config.json' from origin 'http://localhost:57296' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
**Code**
</script>
    <script src="https://lex-web-ui-codebuilddeploy-iii2ktqlj-webappbucket-imve2dz8r4c7.s3.us-east-1.amazonaws.com/lex-web-ui-loader.min.js"></script>
<script>
  var loaderOpts = {
    baseUrl: 'https://lex-web-ui-codebuilddeploy-iii2ktqlj-webappbucket-imve2dz8r4c7.s3.us-east-1.amazonaws.com/',
    shouldLoadMinDeps: true
  };
  var loader = new ChatBotUiLoader.IframeLoader(loaderOpts);
  loader.load()
    .catch(function (error) { console.error(error); });
</script>

**Comment by bobpskier** [comment]
The LexWebUi utilizes CORS configuration to prevent the iframe from being loaded by an unauthorized parent domain. When the LexWebUi is deployed, a configuration parameter is available in the template to help set this up properly. This is the parent origin parameter. When specified, the parent origin is configured in the CORS section of the S3 bucket permissions. In your case the parent origin would have been specified as http://localhsot:57296.  This would be visible in the S3 bucket CORS configuration. The parent origin is also configured in the lex-web-ui-loader-config.json file in the s3 bucket. The parent origin configured in this file will also be http://localhost:57296 using your example. If both of these are properly set, the parent page at http://localhost:57296 should be able to load the iframe correctly.

**Comment by sanakalam** [comment]
Hi @bobpskier ,
Thanks, a lot for your Quick Response I set the configuration parameter as : http://localhsot:57296 Now it's working fine. But if I want to deploy it on our live web and set the parameter to **https://abc.com**  I am getting below Error:

> Parameter WebAppParentOrigin failed to satisfy constraint: Empty or valid browser origin.

**Comment by sanakalam** [comment]
@bobpskier Thanks For your Quick Response. It's Working.
