### ISSUE TITLE
Hide Buttons In ChatBot

### ISSUE THREAD

**Issue by sanakalam** [aws-samples/aws-lex-web-ui#210]
I want to hide the Previous Button and help button from the chatbot. And Instead of previous want to add a close button to end the chat. Is there any solution?
![image](https://user-images.githubusercontent.com/54615542/81690799-405ad300-9475-11ea-9fbf-83a76684deeb.png)

**Comment by bobpskier** [comment]
Download and modify lex-web-ui-loader-config.json file from your S3 bucket. In this file set ui.helpIntent in this json to the empty string and upload this back to your s3 bucket. This should disable the help button. For the "previous" button you can disable this by adding to custom-chatbot-style.css. Place the following outside of the orginially commented section.

```
.nav-button-prev {
    display: none;
}
```

For both lex-web-ui-loader-config.json and custom-chatbot-style.css, upload these into S3 using -acl public-read.

**Comment by sanakalam** [comment]
Any update stack option is required after uploading the Config file. because I update the file but no changes will appear in the preview.
 "ui": {
    "parentOrigin": "http://localhost:57296",
    "toolbarTitle": "Help Desk",
    "toolbarLogo": "",
    "positiveFeedbackIntent": "",
    "negativeFeedbackIntent": "",
    "helpIntent": "",
    "enableLogin": false,
    "AllowSuperDangerousHTMLInMessage": true,
    "shouldDisplayResponseCardTitle": true,
    "hideInputFieldsForButtonResponse": false,
    "pushInitialTextOnRestart": false,
    "directFocusToBotInput": false,
    "showDialogStateIcon": false
  },

**Comment by bobpskier** [comment]
No stack update required. Just an upload to S3 with acl public-read. Make sure to clear your browser cache after upload before refreshing the page. You can confirm using the network tab of your browser debugger (disable cache checkbox) and look at the response for this resource.

**Comment by sanakalam** [comment]
@bobpskier Thanks It works.
