### ISSUE TITLE
Can we display a drop down(list of available options) to user for selection in Lex chatbot  

### ISSUE THREAD

**Issue by nagamaneesh437** [aws-samples/aws-lex-web-ui#216]
Greetings !!!
I need to provide a drop down(list of available options which changes dynamically) to user for selection in Lex chatbot. Do we have any provision for doing this in Lex? 

Thanks in Advance.

**Comment by reegz** [comment]
This is not an issue with the repo in question.

Theoretically it is possible. You would need to use Lex's response to return the list of values and then you'd need to customise your chat widget to handle and display the values accordingly. 

However, I can't see why you'd want to offer a drop down. Either offer buttons if the selection set is small, or add your options as a slot type and have the user type in their selection.
