### ISSUE TITLE
Can we assign a default intent if Lex is not able to understand user intent?

### ISSUE THREAD

**Issue by nagamaneesh437** [aws-samples/aws-lex-web-ui#218]
I want to assign Lex to default intent instead of triggering ElicitIntent if Lex is not able to understand user intent. Can I do that?

**Comment by reegz** [comment]
The Fallback intent might be what you're looking for.

https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-lex-announces-support-for-fallback-intent/
