### ISSUE TITLE
Unable to build prod dist folder from parent directory

### ISSUE THREAD

**Issue by SuneetPatil** [aws-samples/aws-lex-web-ui#221]
Hi Team,

Currently to get charts in Lex-Web-UI, we have modified the Message.Vue and added package and updated code base and build. CHarts will be rendered when we pass session variables from lambda and everything is working when we run the lex-web-ui/lex-web-ui code using npm start, however when we build the build-prod from lex-web-ui parent folder we are getting below error. Need help is resolving the below issue,
URL: http://localhost:8000/
````ChatBotUiLoader loaded
fullpage-component-loader.js:339 Uncaught (in promise) Error: failed to load LexWebUi: ReferenceError: LexWebUi is not defined
    at fullpage-component-loader.js:339
    at new Promise (<anonymous>)
    at Function.value (fullpage-component-loader.js:334)
    at fullpage-component-loader.js:306
````
Steps to reproduce it,
in parent folder lex-web-ui
````
npm install
cd lex-web-ui
npm install
npm run dev (works fine with new changes both as full screen loader and Iframe loader)
ie http://localhost:8080/
````
now to build prod from parent folder,
````
cd build
release.sh
cd ..
npm start (throws error)
````
Please let us is the commands followed to run the prod dist folder is correct? if not, can you please share the pointers or snippets which help to resolve this issue.

Let me know if you need further inputs.

Thanks,
Suneet

**Comment by jegathish-presidio** [comment]
@SuneetPatil SuneetPatil Has the above error been resolved? If so, what did you do?

**Comment by jegathish** [comment]
@SuneetPatil Has the above error been resolved? If so, what did you do.
