### ISSUE TITLE
remove audio part

### ISSUE THREAD

**Issue by akuma34** [aws-samples/aws-lex-web-ui#23]
HI, I dont want to offer the audio part to my customer, is there a way to disable it and have a lightweight js that can only support text and cards? or at least just disable the audio part.

**Comment by atoa** [comment]
Hi,

You can disable the voice feature by setting to `false` the `enable` field under the `recorder` configuration key.

```javascript
// config
{
  ...
  recorder: {
    enable: false,
    ...
  },
  ...
}
```

Let me know if this answers the question

-- Oliver
