### ISSUE TITLE
CORS error when deploying the chatbot locally 

### ISSUE THREAD

**Issue by brandon707** [aws-samples/aws-lex-web-ui#236]
Hi, 
i'm having an issue where i'm trying to deploy the chat bot to my website without the need of the S3 bucket meaning all chat bot files are running locally aside but i having the CORS issues which reads as follows "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." 
I have read through some issues that were posted here but i'm unable to find a way to fix the CORS error for local deployment, is there anyway to fix the CORS policy issue without the use of the S3 bucket CORS configuration

**Comment by sterankin** [comment]
@brandon707 did you every resolve this?
