### ISSUE TITLE
Resize chatbot iframe UI

### ISSUE THREAD

**Issue by elmofuellas** [aws-samples/aws-lex-web-ui#237]
Hi. I deployed the chatbot in my website using the CloudFormation stack. What file should I edit to resize the iframe UI?

**Comment by bobpskier** [comment]
The css for the page hosting the iframe could be altered to adjust the chatbot's size and position. See https://github.com/aws-samples/aws-lex-web-ui/blob/master/README-css-style.md#iframe-width-and-height. Below the diagram is a section on Iframe width and height.

**Comment by elmofuellas** [comment]
Hi bobpskier, 

Thanks for the reply. Really helpful, was able to resize the frame.

 Another query though, tried to un-comment and edit the css in the custom-chatbot-style.css file then re-upload it in S3, but the changes doesn't reflect on the iframe in my deployed website. I also tried to clear the cache but to no avail. Am I missing some steps? 

Thanks
