### ISSUE TITLE
Changing region to Singapore (CloudFormation)

### ISSUE THREAD

**Issue by elmofuellas** [aws-samples/aws-lex-web-ui#241]
Hi. 

All my resources (Lex, Lambda, etc.) are in Singapore region. Can I configure the CloudFormation stack to launch on Singapore region? Tried launching the Sydney region stack, but it doesn't recognize my bot since my bot is deployed in Singapore. 

Hope you can help.

Thanks, 
Elmo

**Comment by bobpskier** [comment]
I setup a distribution bucket in the Singapore region to allow simple launches in this region. Eventually a one click button will be available in the README.md and and the blog post.  For now you can cut and paste this URL to launch in this region from your browser.

https://ap-southeast-1.console.aws.amazon.com/cloudformation/home?region=ap-southeast-1#/stacks/create/review?templateURL=https://s3.amazonaws.com/aws-bigdata-blog-replica-ap-southeast-1a/artifacts/aws-lex-web-ui/artifacts/templates/master.yaml&stackName=lex-web-ui&param_BootstrapBucket=aws-bigdata-blog-replica-ap-southeast-1a

**Comment by elmofuellas** [comment]
Hi bobpskier,

It worked great. Thanks for the quick response!

Regards,
elmofuellas

**Comment by elmofuellas** [comment]
Hi bobpskier,

It worked great. Thanks for the quick response!

Regards,
elmofuellas
