### ISSUE TITLE
chatbot UI failed to load Error: "config event timed out"

### ISSUE THREAD

**Issue by iwells16** [aws-samples/aws-lex-web-ui#244]
Hello,
I deployed the solution with Cloud Formation and it works awesome. index.html and parent.html pages works as I needed, but I am having an issue with the iframe when trying to add it to a different server or a local application. 

I followed the guide  [iframe](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-embedding) and once I started my application, the web page is showing up but it seems the iframe chatbot UI is not rendering. I used the developer tools and I see the following error at the console

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/43506991/97126770-6b707080-16fd-11eb-85a9-645377448792.png">

On the CloudFormation I changed the parameters WebAppParentOrigin, ParentOrigin and the WebAppUrl to https://localhost:4200, that is were my local application is running.

Also in the page I add the Script as I see on the instructions like this

![image](https://user-images.githubusercontent.com/43506991/97126988-f7829800-16fd-11eb-8b5b-da21e0eea9c6.png)

I tried to see on the rest of the issues and re visit the Readme files to see If I was missing something and it seems that no. This Widget is very useful, and I was wondering if someone faced the same and can kindly give me a clue how to make this work.

I really appreciate in advance

**Comment by HardikaDoshi** [comment]
Hi, were you able to solve this issue?

**Comment by wcheek** [comment]
It's because you are using the `shouldLoadConfigFromEvent` option in your `loaderOpts`. You need to add an event listener for the `receivelexconfig` event and send your config through a custom event, as per [this documentation](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#event-based-config).
