### ISSUE TITLE
"\n" (backslash-n) not recogized

### ISSUE THREAD

**Issue by efuellas** [aws-samples/aws-lex-web-ui#247]
Hi.

I'm using Python in Lambda and it is integrated with Lex. I have these response messages that need to be printed by Lex line by line. The chatbot window UI doesn't recognize the "\n" (or new line) that is included in my declared string. Is there other ways to print in a new line?

Thanks

**Comment by rstrahan** [comment]
You can use a markdown response to force line breaks in Lex Web UI output..  Insert 2 blank spaces at end of each line
E.g.
```
line 1   
line 2   
line 3  
  
OR with html tag
  
line 1 <br/> line 2 <br/> line 3
```

Renders as

![image](https://user-images.githubusercontent.com/10953374/98306877-ac387700-1f92-11eb-8085-29580e16d1c2.png)

**Comment by efuellas** [comment]
Hi rstrahan,

Thanks for these again. Tested this out and it worked.

To add, to use a markdown response, your ContentType should be "CustomPayload".

Cheers!
