### ISSUE TITLE
response cards

### ISSUE THREAD

**Issue by Samer2** [aws-samples/aws-lex-web-ui#25]
1. Is there an option to include response cards with Initial text. 
ex. Hello, welcome to myBot. I can help you with below today. 
Btn_BookCar, Btn_BookHotel, etc.. 

2. How to authenticate&authorize the users from Lex-Web-UI and generate the temporary credentials based on the token received from 3rd party IDP. 

3. I have placed the index.html in a S3 bucket and made it public. If i enable restrict access, i am not able to reach lexRuntime though i provide valid IdentityPoolID (Public)

**Comment by atoa** [comment]
> 1. Is there an option to include response cards with Initial text.

This is not supported at this time

> 2. How to authenticate&authorize the users from Lex-Web-UI and generate the temporary credentials based on the token received from 3rd party IDP.

I suggest you look into [Amazon Cognito](https://aws.amazon.com/cognito/) which allows to federate with external identity providers.

> 3. If i enable restrict access, i am not able to reach lexRuntime though i provide valid IdentityPoolID (Public)

You may want to take a look at the web developer console in your browser for any indications
