### ISSUE TITLE
How to do human agent handover from Lex

### ISSUE THREAD

**Issue by ravikanthvob** [aws-samples/aws-lex-web-ui#253]
Not a issue, but trying to find a amazon solution; if Lex allows human agent handover at certain point in conversation. What are the AWS and non-AWS (if I may have to) integration available

#200

**Comment by rstrahan** [comment]
Hi @ravikanthvob  - 

If the bot interaction is already being done through a Connect contact center, then see our example integration described in the blog - it includes a placeholder for how the bot can set a session attribute to get Connect to transfer to an agent queue: www.amazon.com/qnabot#connect

Or if the bot is on a different channel, say the web UI, then a nice option is to request an agent callback using Connect.. See example in [QnABot Self Paced Guide](https://d14r4b0p45o2hl.cloudfront.net/guides/qnachatbot/index.html) section titled "Set Up Your Q&A Chatbot to Receive a Call Back from your Amazon Connect Instance"
