### ISSUE TITLE
full page lex ui frame cutoff on mobile

### ISSUE THREAD

**Issue by bradartman** [aws-samples/aws-lex-web-ui#254]
I'm having an issue where the "Type here or click mic" area of the page being below the action bar on almost every iOS device (Unless I turn landscape).  I'm just attempting to load the full frame index.html page from safari.  If I pinch shrink the page a few times it will resize properly.  Typical web browser renderings work fine.

Any thoughts where I can check first?

**Comment by athewsey** [comment]
I'm also seeing this on Android Firefox (menu bar at the bottom obscures the input area, with no way to scroll around it!) - but OK in Chrome (menu bar appears at top, scrolling down shows the app as intended as full-screen).
