### ISSUE TITLE
cloudformation template is failing when creating codecommit repo

### ISSUE THREAD

**Issue by rkowtha** [aws-samples/aws-lex-web-ui#264]
Getting the following error when creating the codecommitrepo - Parameters: [Timestamp] do not exist in the template

**Comment by bobpskier** [comment]
Thanks for reporting the issue. Working on a solution. As soon as one is available I'll post back on this thread.

**Comment by bobpskier** [comment]
Pipeline based deployment should be resolved in version 0.17.8.

**Comment by rkowtha** [comment]
Thanks. It worked successfully.
