### ISSUE TITLE
Changes made to custom-chatbot-style.css are not displaying

### ISSUE THREAD

**Issue by rkowtha** [aws-samples/aws-lex-web-ui#265]
The UI changes to color and font made in custom-chatbot-style.css are not displaying after deployment. It was working in v0.17.3. Looking forward in fixing this issue.

**Comment by bobpskier** [comment]
Can you provide a bit more detail about the issue? After updating custom-chatbot-style.css in the webapp deployment S3 bucket you'll need to open the corresponding CloudFront distribution and perform an object invalidation. Once the invalidation completes, reload the browser page making sure to clear cache in the browser. This should allow the change to have an affect on the style. If this process is not working for you, please let us know..
