### ISSUE TITLE
how to access passport object from server.js in Vue component at startup

### ISSUE THREAD

**Issue by devcode925** [aws-samples/aws-lex-web-ui#271]
we are using the sample UI as our framework. It has been really easy to work with. 
A current requirement is to load okta info on startup and load in a passport object. Mostly user info. That works fine.
Also at startup we need to access the passport object in the MessageList.vue component to check a property in the user info and possibly show a different message at startup.

I've tried using beforeMount() in the Vue component to call the passport object via axio. Which shows the new method being accessed. However, it seems the components are loaded before the axio call comes back, so I don't have the value. I've tried async and await in the call as well no luck.
any ideas, on how to solve this one?

**Comment by bobpskier** [comment]
One thought is perhaps to add the passport object as part of the vuex state during startup and then reference this state in the MessageList.vue. Vuex is used to manage state in the app and its probably the easiest way to store and share state between the components. You'd add the default within lex-web-ui/src/store/state.js and then add support for the new object in lex-web-ui/src/store/mutations.js and lex-web-ui/src/store/getters.js. Perhaps the vuex lex-web-ui/src/store/actions.js might be a place to drive initialization as well.  Check out https://vuex.vuejs.org/ for info on vuex.

**Comment by devcode925** [comment]
hi @bobpskier, we did try something similar with success. I ended up with adding a method in created() block in the MessageList.vue. From there I called the state.js method with fetch() and it worked fine.
thanks for your help!
