### ISSUE TITLE
Error : Sorry, I was unable to process your message. Try again later.

### ISSUE THREAD

**Issue by kanniahvj2020** [aws-samples/aws-lex-web-ui#273]
Hi Team,

I have customer demo tomorrow and as per the Blog, i have launched the stack and it is completed, when i try to launch the Web Interface using Cloudfront URL, i am getting the error 

https://aws.amazon.com/blogs/machine-learning/deploy-a-web-ui-for-your-chatbot/

You can ask me for help ordering flowers. Just type "Buy flowers" or click on the mic and say it.
I say: buy flowers
bot says: Sorry, I was unable to process your message. Try again later.

can you please help 
<img width="960" alt="error" src="https://user-images.githubusercontent.com/64630641/115543716-52690680-a2bf-11eb-991f-8e74272ea136.PNG">

**Comment by bobpskier** [comment]
This usually occurs if the bot name and bot alias have changed or are no longer available in Lex. For the general case, the values provided in template are stored in the lex-web-ui-loader-config.json file in the s3 webapp bucket. Its best to confirm these are still correct. You can use CloudFormation Update Stack mechanism to update the values or download the json file, make the change and upload back to S3.  

In your case, you are probably using the sample Order Flowers bot created by the template. Most likely this sample bot has been removed. This can occur if you have installed the lex-web-ui stack multiple times using the sample and then removed one of the stacks. The lex-web-ui does not create separate instances of the Order Flowers bot on install. When multiple instances of lex-web-ui are installed using the sample bot, and one instance is subsequently removed, it will remove the Order Flowers bot that the second install depends on resulting in this failure. You can install a new lex-web-ui which would reinstall the sample bot or create a sample bot directly in the Lex console and reconfigure the Lex-Web-Ui to use this new sample bot.
