### ISSUE TITLE
How translate the text "Type here or click on the mic"? 

### ISSUE THREAD

**Issue by rlteccr** [aws-samples/aws-lex-web-ui#279]
Please help. How to translate the text "Type here or click on the mic"? My aws lex implementation will be in Spanish

**Comment by bobpskier** [comment]
This text is changeable in the lex-web-ui-loader-config.json file which exists is in the webapp S3 bucket once the template finishes deployment. Download this file and edit the json file per the info below. Save the changes and upload back to the S3 bucket. Use the AWS CloudFront console to open the lexwebui cloudfront distribution and invalidate the current objects. Reload your browser containing the lex-web-ui and it should pickup the modified text. 

In the lex-web-ui-loader-config.json, look for the ui section and add the property

textInputPlaceholder: 'translated spanish text'

It would look something similar to

```
"ui": {
     ........,
    "textInputPlaceholder": "translated spanish text"
  },  
 ```

**Comment by rlteccr** [comment]
Great thank you so much!
