### ISSUE TITLE
Embed the lex chatbot UI into an existing page using an iframe

### ISSUE THREAD

**Issue by dileephell** [aws-samples/aws-lex-web-ui#28]
I have to integrate the iframe lex ui into my website. I tried the https://github.com/awslabs/aws-lex-web-ui#iframe but unable to implement. I am not getting any error while inspecting as well. i have filled all the configurations related to iam and cognito pool ids.

![sampleparent](https://user-images.githubusercontent.com/2589018/36264721-84d0124a-1293-11e8-9018-df93fd31b3ab.png)

This one is lex-web-ui and working fine. But i need the iframe version of this to be integrated with the website which i am having in my website (node.js). 

![samplehome](https://user-images.githubusercontent.com/2589018/36264733-902803e6-1293-11e8-9914-59253a1cf648.png)

please suggest where my approach is going wrong.

Thanks,
Dileep

**Comment by atoa** [comment]
Hi Dileep,

Are you seeing errors in browser console ([developer tools](https://developers.google.com/web/tools/chrome-devtools/))? Also, I suggest you make sure that browser plugins are not interfering.

-- Oliver

**Comment by dileephell** [comment]
As i mentioned earlier. No errors in the developer tools. And no plugins are  interfering.

I even tried to rename the parent.html to index.html from the src/website folder to make it work, but this iframe is not loading.  The only thing i am getting in the developer tools is Timeout.

**Comment by atoa** [comment]
Looks like there may be a discrepancy in the origin configuration. The console error points to [iframe-component-loader.js:208](https://github.com/awslabs/aws-lex-web-ui/blob/master/src/lex-web-ui-loader/js/lib/iframe-component-loader.js#L207-L208) which is the place where the origins are checked.

You may want to take a look at the [Iframe Embedding section of the documentation](https://github.com/awslabs/aws-lex-web-ui/tree/master/src#iframe-embedding) to see details about the iframe config and origins. Make sure that the origin fields in your `lex-web-ui-loader-config.json` file match your use case.

Feel free to post your `lex-web-ui-loader-config.json` and a brief description of how the environment was set up to see if we can spot the issue.

Thanks

-- Oliver

**Comment by dileephell** [comment]
Thanks Oliver. I looked into the JSON and i am able to load the iframe into localhost at port :8000/parent.html. Now my query is when i am trying to integrate it with my localcode in node.js server. When i took only the parent.html from current repo to my localcode along with lex-web-ui-loader.js. i am getting the error of index.html should be there. And when i am keeping that(index) then parent.html  is not loading.

what should I do to only load the parent.html ifame without the index.html.

Error is `chatbot-ui-iframe-loader.js:477 GET http://localhost:3000/admin/index.html 404 (Not Found)`

but i am redirecting in my code after login it will go to admin/sendFile.html.


Attaching the gist for [server.js](https://gist.github.com/dileephell/acb234e8265a1ca4ceadc0d4469f9019) and the [sendFile.html](https://gist.github.com/dileephell/93e26dcc5991ce0751cd51f2e45e28dc) as.

Please help me if any approach is going wrong to load.

**Comment by JohnCalhoun** [comment]
this looks related to #29
