### ISSUE TITLE
how to set initial utterance according to postText.api()?

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#280]
I want to send initial utterance according to the post text api how can i do that?
For example, as mentioned in [Iframe embedding section]( https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-embedding) on pushing:
.then(function () {
// send an utterance to the bot
return lexWebUiLoader.api.postText('Hello')

It should push the initial utterance to bot "Hi I am aayog, how may i help you"

If the function is:
.then(function () {
// send an utterance to the bot
return lexWebUiLoader.api.postText('Check my phone')

It should push the initial utterance to bot "Hi I am aayog, I can help you in scanning your phone"

I am actually new in javascript. So having an issue. Can anyone help me in this.

Thanks in advance

**Comment by rstrahan** [comment]
Hi @karanakatle  - the latest version of LexWebUI will do this for you if you install via CloudFormation - no JavaScript coding required. There is a new CF parameter - WebAppConfBotInitialUtterance. Populate it when you install/update Lex Web UI stack and then it will get sent to bot when the page loads.

**Comment by karanakatle** [comment]
Hey thank you so much for the solution. Could you please also help me in ony of my question again which is asked in issue  #197
 Open
