### ISSUE TITLE
iframe loader is not recognizing the updated lex-web-ui-loader-config.json

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#281]
Hi have tried updating the parameters from cloudformation but my iframe embeded chatbot is not recognizing the updated parameters. I have tried manually uploading the lex-web-ui-loader-config.json but still it is not recognizing the updated version. I have tried this 2 methods previously also at that time it works, now not sure why iframe loader is not recognizing this now.

However my standalone chatbot which we can access from cloudfront link is modified according to changes. Only the iframe loader is not updating. I have re-checked file names, everything is correct. Also set public read access, still facing same problem.

How to resolve it?

**Comment by bobpskier** [comment]
After verifying the lex-web-ui-loader-config.json object in S3 is updated,  I usually invalidate the CloudFront distribution and clear browser cache prior to a reload of the parent page. Next in browser debugger one can look at the the requests for lex-web-ui-loader-config.json and verify proper response content matching the json stored in S3. If the response content is correct but the behavior still not expected, confirm that no configuration is being passed to the loader object from the parent page that might override that stored in lex-web-ui-loader-config.json.

**Comment by karanakatle** [comment]
Hey thank you so much bob for this.
Could you please help me in the issue #197.
Actually I got the part of it. But required your guidance in specific case
