### ISSUE TITLE
Embed a link in a chatbot

### ISSUE THREAD

**Issue by suyogbhavsar** [aws-samples/aws-lex-web-ui#283]
Can anyone help me in embedding a link for ex. Amazon.com in my chatbot. I want to embed in such a way that the user should be able to see it all the time such as embedding the link below chatbot.

I am new in JS and hence need a guidance on it

**Comment by bobpskier** [comment]
Can you describe the use case a bit further? The lex-web-ui can be embedded on a "parent" page as an iframe. In this model the link you describe could be visible on the parent page all the time near or next to the iframe. In addition, the parent page can receive events from the iframe based on chatting with the bot. These events could instruct the parent page to adjust (show/hide) the link as necessary. Is this the use case you are thinking of?

**Comment by suyogbhavsar** [comment]
@bobpskier I have a created multingual chatbot (3 languages) using AWS Lex and Lex-web-ui as a chatbot interface. I have created a localemapping function on the jsx page on which I have added my snippet code. As soon as the user select a language on the parent page, the localemapping function detects the Locale and passes a specified value to a post text api. For example if a Locale is En, it will pass 'eng' value to post text api or if Locale is Es, it will pass 'Spanish'  value to post text api. These are the values which I have entered as a sample utterance of the intent. So as the user selects language, the specific intent gets triggered and the conversation starts in the specific language. 
The chatbot is loading as an iframe on the website. 
What further I need to do is:
1. Embedding a link in the iframe of a chatbot below or above the textinput area. For example : click here to contact customer service which will take user to the customer service page. 
2. When the iframe is minimized on the parent page, the toolbar title should be visible next or near the iframe logo.
3. I would like to change the language of the chatbot iframe toolbar title, toolbar title which will be visible near the chatbot logo when it is minimized and the embedded link along with the language of the chatbot. Is there any way to do it in Lex-web-ui.

**Comment by karanakatle** [comment]
I can help you with 2nd question. Edit minbuttoncontent in lex-web-ui-loader-config.json file this will sort out your second concern

For embedding a link in iframe u need to be a vue programmer however you could also look for the idea discussed in #246

**Comment by suyogbhavsar** [comment]
OK thanks
