### ISSUE TITLE
How can we capture the opening event of chatbot iframe

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#284]
Is there any way to capture the opening event of chatbot iframe.

I have integrated a chatbot on a specific button and my use case is if the chatbot is minimized, then clicking the button should maximize the chatbot and if chatbot is already maximized then clicking that button should not perform any actions.

However after integration, it performs only toggle action ex. if chatbot is minimized, clicking on the button maximized it and if chatbot is maximized, clicking on the button minimizes it.

I want to know is there anyway from which i could know that the chatbot iframe is opened.

**Comment by bobpskier** [comment]
@karanakatle When the chatbot is ready to process input within the iframe, it sends a lexWebUiReady event to the parent page. However, I think you are looking for a mechanism to determine current state of the iframe and if it is minimized into a button form. The following function looks to see if the iframe element is using the minimized css class. This might provide what you are looking for.

```
    function isBotMinimized() {
        // look at the options of the loader to determine the iframe
        // element ID
        var elementId = iframeLoader.options.elementId;

        // this class is present in the iframe when minimized
        var minimizedClass = 'lex-web-ui-iframe--minimize';
        return $('#' + elementId).hasClass(minimizedClass);
    }
 ```

**Comment by karanakatle** [comment]
@bobpskier thank you so much for your guidance.
I have a last question and looking the help in it as well. So if possible, please provide a way for that as well.

Is there any way to trigger the chatbot iframe through link.
On a multiple pages i don't want chatbot icon to be visible.. It should be visible on the first page only,
however if i clicked on a certain button on that page, it should load my chatbot iframe.
Cloudfront link is not loading an iframe, it is loading a standalone chatbot. Is there any way to achieve this? 

Thanks in advance
