### ISSUE TITLE
ChatBot Connect Chat Integration

### ISSUE THREAD

**Issue by htc36** [aws-samples/aws-lex-web-ui#289]
I see you have the branch feature/live-chat-connect.
I am wondering if you've got a time frame of when this will be released  (1 month, 3 month, 1year)? 
Cheers

**Comment by rstrahan** [comment]
Can't share a time frame just yet, but we are working on it, and hoping 'soon' :)
Do you have a good use case for it?

Sent from Workspace ONE Boxer

On May 31, 2021 12:47 AM, htc36 ***@***.***> wrote:

I see you have the branch feature/live-chat-connect.
I am wondering if you've got a time frame of when this will be released (1 month, 3 month, 1year)?
Cheers

-

**Comment by htc36** [comment]
Yes we currently operate a lex bot that handles covid-19 and clinical intents, and we are looking to roll out a live chat handoff to connect customers with nurses if the chat bot can not answer their question.
