### ISSUE TITLE
words not detecting correctly by the Bot

### ISSUE THREAD

**Issue by gdsnc** [aws-samples/aws-lex-web-ui#293]
I am using QNA BOT with the same configurations mentioned here.  Text is working perfectly but when i try voice, the words are not taken correctly. Could you please help in this. I may be missing some configurations in ui or something that may be related to polly. I am using chrome browser. Its working but words are not picked correctly like if i try "where can i report" is shown as "where" but when we replay the voice it was recorded properly.

**Comment by rstrahan** [comment]
Lex speech recognition is greatly helped by using content designer to (1) enter questions as close as possible to the sentences the user says, and (2) use the ‘Rebuild Lex bot’ menu item to rebuild the Lex but (it will train the bot using the questions you entered, which will help with speech recognition).


From: gdsnc ***@***.***>
Sent: Thursday, June 3, 2021 10:56 AM
To: aws-samples/aws-lex-web-ui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aws-samples/aws-lex-web-ui] words not detecting correctly by the Bot (#293)


I am using QNA BOT with the same configurations mentioned here. Text is working perfectly but when i try voice, the words are not taken correctly. Could you please help in this. I may be missing some configurations in ui or something that may be related to polly. I am using chrome browser. Its working but words are not picked correctly like if i try "where can i report" is shown as "where" but when we replay the voice it was recorded properly.
