### ISSUE TITLE
403 Error [Sorry, I was unable to process your message. Try again later.]

### ISSUE THREAD

**Issue by nanyoci** [aws-samples/aws-lex-web-ui#299]
So I have a Lex bot created using from the stack here
(https://aws.amazon.com/blogs/machine-learning/creating-a-question-and-answer-bot-with-amazon-lex-and-amazon-alexa/)
but i want to have an authentication for client before they can access the bot so I set up the cloudformation from the stack https://aws.amazon.com/blogs/machine-learning/deploy-a-web-ui-for-your-chatbot/ and configure it to the existing bot before I created the stack. However, the bot kept giving me response as "Sorry, I was unable to process your message. Try again later." and according to the console, it is 403 error. 
How could I fix this?

**Comment by rstrahan** [comment]
Hi @nanyoci  - I see you closed the issue.. did you find the problem? If possible can you post some notes on the cause and the fix?

**Comment by nanyoci** [comment]
The problem was that I was that I have 2 Lex bot, one V1 and another V2. However, I connected to V1 bot which has some problem. My V2 bot is working so when I left BotName for V1 bot blank, everything works.
