### ISSUE TITLE
How do I Integrate with a Lex Bot that I have built?

### ISSUE THREAD

**Issue by SonicV2** [aws-samples/aws-lex-web-ui#30]
I have entered the Cognito ID and Name for my lex bot is the aws-config.json. The error message I am getting is TypeError: lexClient is undefined. 

Also, I tried the alternative version of the Mobile Hub. However it keeps asking me to download a file when I am open the index.html. What do you mean by syncing the files to avoid that?

**Comment by JohnCalhoun** [comment]
are you using the mobilehub version or the web client version? iframe?
