### ISSUE TITLE
Issues in loading iframe for multilingual bot

### ISSUE THREAD

**Issue by ladabhi** [aws-samples/aws-lex-web-ui#301]
Hey guys,

I am working on a multilingual chatbot and delpoyed it using lex-web-ui. I have integrated the chatbot on my homepage.
I have 4 locales 'english', 'russian', 'french', 'armenian' integrated on my website.
The bot is working as expected on a first load, but problem arises when i change the language of the page.

After a first load in order to change the bot according to locale, I am using a code:

element=document.getElementById('lex-web-ui-iframe')
if (element) {
element.parentNode.removeChild(element)
}

As on changing the locale the website build doesn't refresh, it just change the language of the page. So i am removing the lex-web-ui-iframe div for a sec and then again loading it using 

var iframeloader = new window.ChatBotUiLoader.IframeLoader(loaderOpts);
iframeloader.load()

At first, the bot loads perfectly and the lex-web-ui-iframe class is in minimized state and a min-button is visible on the homepage.

But when i change the language, the bot loads with a min-button visible on the homepage with transparent box of the size of maximized chatbot, the class of lex-web-ui-iframe also changed to 'lex-web-ui-iframe lex-web-ui-iframe--show', it toggles out the minimize class whereas it should be 'lex-web-ui-iframe lex-web-ui-iframe--show lex-web-ui-iframe--minimize'.

When i clicked on a min-button after changing a locale, it maximize the bot but the class of lex-web-ui-iframe doesn't change, it remains same ie., 'lex-web-ui-iframe lex-web-ui-iframe--show'. 

When i again change the locale ie., then the bot works perfectly fine as it was on working on the default locale. when i further change a locale the same problem occurs ie., min-button with transparent box and class as 'lex-web-ui-iframe lex-web-ui-iframe--show'.

hiding the transparent box will not work as it will make the contents of website behind it inaccessible.

Does anyone have an idea how to resolve it or a better way of doing these things.

**Comment by bobpskier** [comment]
Can you provide a Url that we can see the problem on? I've not experimented with the technique of removing the div element and reloading the LexWebUi recreating the div element. I tend to think it should work and would need to see the failure to comment on it. Is this a Lex V1 or Lex V2 bot on the backend? For a V1 based bot, how are you incorporating locale for processing on the backend?

**Comment by ladabhi** [comment]
@bobpskier thank you so much for replying. I would love to share the link, but right now i am experimenting this on a localhost. Actually I have solved the problem which I discussed above but now observing the unexpected behaviour of toggleShowUi class. On changing the locales sometimes chatbot loads and works as expected but sometimes on changing the locale 'lex-web-ui-iframe--show' class is toggled Out leaving behind 'lex-web-ui-iframe lex-web-ui-iframe--minimize'

While being on a homepage for sometime ex.10 mins and then changing the locale the above problem occurs i.e., toggling out the 'lex-web-ui-iframe--show' class from class list and chatbot disappeared. 

I tried changing toggle method to add method in toggleShowUi class only (no other changes with respect to this were made) so instead of disappearance of the chatbot, sometimes on changing a locale instead of min-button, minimized toolbar appeared in which we can click on the arrow on the right side of the toolbar and it gets maximized and then again clicking it, it gets minimize.

Can you give me some guidance for solving this issue.

I will try to explain you how I tackle the previous problem:

I am using a V1 bot. In the backend I am passing a specific word for through iframeloader.api.postText() method. for example, english word which will start the conversation in english, russian word starting conversation in russian and in order to make the consistency of the conversation in a specific language, I have coded a python script in AWS lambda. also I'm allowing users to choose only from response cards and not allowing them to enter any answer by hiding input fields.

Our website is designed using React.js so on one of the utilities.jsx files where most of the function resides, I have created a key value pair .

for ex. const localeChatMapping = [{locale: 'en', message: 'english', title: 'welcome'},
                                                         {locale: 'ru',message: 'russian', title: 'добро пожаловать'},
                                                         {locale: 'hy', message:'armenian', title: 'Բարի գալուստ'},
                                                         {locale:'fr', message:'french', title:'bienvenue'}]

and define the var iframeloader globally. Defined it globally because i want the title to change along with the locale and defining iframeloader in function was creating a problem in that.

and in a jsx file created a function 

`displayChat(ev) {
        console.log('display Chat is invoked');
        const loc = ev && typeof ev === 'string' ? ev : sessionStorage.getItem('locale');
        const existingChat = document.getElementById('lex-web-ui-iframe');
        if (existingChat) {
            existingChat.parentNode.removeChild(existingChat);
        }

        const localeMapping = localeChatMapping.find(elem => elem.locale === loc);
        iframeloader.config.ui = {
            toolbarTitle: localeMapping.title,
            minButtonContent: localeMapping.title,
        };
        iframeloader
            .load()
            .then(() => {
                return iframeloader.api.postText(localeMapping.message);
            })
            .catch(function(error) {
                console.error(error);
            });
    },`

And invoking it on a homepage in this way:
`    pageDidMount() {
        setTimeout(() => {
            utilities.displayChat();
        }, 300);
    }
    pageWillUnmount() {
        const existingChat = document.getElementById('lex-web-ui-iframe');
        const page = this.props?.pageConfig?.pageName;

        if (existingChat) {
            existingChat.parentNode.removeChild(existingChat);
        }
    }`

Added a pagewillunmount because i want this chat on homepage only.

I have tried solving this problem and came up with custom events in lex-web-ui-loader.js
I have created 2 custom events `removeMinimizeUi` which is used for removing minimize class and `MinimizeUi` which is adding a minimize class. 
Please see the code below for lex-web-ui-loader.js

`     // sent when minimize button is pressed within the iframe component
        MinimizeUi: function MinimizeUi(evt) {
          this.MinimizeUiClass().then(function () {
            return evt.ports[0].postMessage({
              event: 'resolve',
              type: evt.data.event
            });
          }).catch(function (error) {
            console.error('failed to MinimizeUi', error);
            evt.ports[0].postMessage({
              event: 'reject',
              type: evt.data.event,
              error: 'failed to MinimizeUi'
            });
          });
        },
        // sent when minimize button is pressed within the iframe component
        removeMinimizeUi: function removeMinimizeUi(evt) {
          this.removeMinimizeUiClass().then(function () {
            return evt.ports[0].postMessage({
              event: 'resolve',
              type: evt.data.event
            });
          }).catch(function (error) {
            console.error('failed to removeMinimizeUi', error);
            evt.ports[0].postMessage({
              event: 'reject',
              type: evt.data.event,
              error: 'failed to removeMinimizeUi'
            });
          });
        },`

This was just changing the name of toggleMinimizeUi to removeMinimizeUi and MinimizeUi which are added after toggleMinimizeUi

`{
    key: "MinimizeUiClass",
    value: function MinimizeUiClass() {
      try {
        this.containerElement.classList.add("".concat(this.containerClass, "--minimize"));

        if (this.containerElement.classList.contains("".concat(this.containerClass, "--minimize"))) {
          localStorage.setItem("".concat(this.config.cognito.appUserPoolClientId, "lastUiIsMinimized"), 'true');
        } else {
          localStorage.setItem("".concat(this.config.cognito.appUserPoolClientId, "lastUiIsMinimized"), 'false');
        }

        return Promise.resolve();
      } catch (err) {
        return Promise.reject(new Error("failed to minimize UI ".concat(err)));
      }
    }
  }, {
    key: "removeMinimizeUiClass",
    value: function removeMinimizeUiClass() {
      try {
        if (this.containerElement.classList.contains("".concat(this.containerClass, "--minimize"))) {
        this.containerElement.classList.remove("".concat(this.containerClass, "--minimize"));
        localStorage.setItem("".concat(this.config.cognito.appUserPoolClientId, "lastUiIsMinimized"), 'false');
        }
        return Promise.resolve();
      } catch (err) {
        return Promise.reject(new Error("failed to remove minimize UI ".concat(err)));
      }
    }
  }, {
    key: "showIframe",
    value: function showIframe() {
      var _this11 = this;

      return Promise.resolve().then(function () {
        // check for last state and resume with this configuration
        if (_this11.config.iframe.shouldLoadIframeMinimized) {
          _this11.api.MinimizeUi();
          localStorage.setItem("".concat(_this11.config.cognito.appUserPoolClientId, "lastUiIsMinimized"), 'true');
        } else if (localStorage.getItem("".concat(_this11.config.cognito.appUserPoolClientId, "lastUiIsMinimized")) && localStorage.getItem("".concat(_this11.config.cognito.appUserPoolClientId, "lastUiIsMinimized")) === 'true') {
          _this11.api.toggleMinimizeUi();
        } else if (localStorage.getItem("".concat(_this11.config.cognito.appUserPoolClientId, "lastUiIsMinimized")) && localStorage.getItem("".concat(_this11.config.cognito.appUserPoolClientId, "lastUiIsMinimized")) === 'false') {
          _this11.api.ping();
        }
      }) // display UI
      .then(function () {
        return _this11.toggleShowUiClass();
      });
    }`

Please note that I have not removed anything from the js file just added a classes. removeMinimizeUi class and MinimizeUi class as shown above are added after toggleMinimizeUi class.

and then defining the api method  for this :
`        MinimizeUi: function MinimizeUi() {
          return _this12.sendMessageToIframe({
            event: 'MinimizeUi'
          });
        },
        removeMinimizeUi: function removeMinimizeUi() {
          return _this12.sendMessageToIframe({
            event: 'removeMinimizeUi'
          });`

in LexWeb.vue,
i have created this events in a message handler function like this:

`        case 'MinimizeUi':
          this.$store.dispatch('checkIsUiMinimized').then(function () {
            return evt.ports[0].postMessage({
              event: 'resolve',
              type: evt.data.event
            });
          });
          break;
  
        case 'removeMinimizeUi':
          this.$store.dispatch('removeIsUiMinimized').then(function () {
            return evt.ports[0].postMessage({
              event: 'resolve',
              type: evt.data.event
            });
          });
          break;`
 
added a method for this in the following way:

`    toggleMinimizeUi() {
      return this.$store.dispatch('toggleIsUiMinimized');
    },
    MinimizeUi() {
      return this.$store.dispatch('checkIsUiMinimized');
    },
    removeMinimizeUi() {
      return this.$store.dispatch('removeIsUiMinimized');
    },`

and i a template updating min-button and toolbar-container tag updating v-on: toggleMinimizeUi like this:

<template>
  <v-app id="lex-web"
    v-bind:ui-minimized="isUiMinimized"
  >
    <min-button
      v-bind:toolbar-color="toolbarColor"
      v-bind:is-ui-minimized="isUiMinimized"
      **v-on:toggleMinimizeUi="removeMinimizeUi"**
    ></min-button>
    <toolbar-container
      v-if="!isUiMinimized"
      v-bind:userName="userNameValue"
      v-bind:toolbar-title="toolbarTitle"
      v-bind:toolbar-color="toolbarColor"
      v-bind:toolbar-logo="toolbarLogo"
      v-bind:is-ui-minimized="isUiMinimized"
      **v-on:toggleMinimizeUi="MinimizeUi"**
      @requestLogin="handleRequestLogin"
      @requestLogout="handleRequestLogout"
    ></toolbar-container>

In lex-web-ui.js in UI and parent communication actions defined checkIsUiMinimized and removeIsUiMinimized in the following way below toggleIsUiMinimized

`  checkIsUiMinimized: function checkIsUiMinimized(context) {
    context.commit('checkIsUiMinimized');
    return context.dispatch('sendMessageToParentWindow', {
      event: 'MinimizeUi'
    });
  },
  removeIsUiMinimized: function removeIsUiMinimized(context) {
    context.commit('removeIsUiMinimized');
    return context.dispatch('sendMessageToParentWindow', {
      event: 'removeMinimizeUi'
    });
  },`

And as the toggleIsUiMinimized is used to track the expand/minimize status of the window action added checkIsUiMinimized and removeIsUiMinimized along with it.

`  /**
  * used to track the expand/minimize status of the window when
  * running embedded in an iframe
  */
  toggleIsUiMinimized: function toggleIsUiMinimized(state) {
    state.isUiMinimized = !state.isUiMinimized;
  },
  checkIsUiMinimized: function checkIsUiMinimized(state) {
    state.isUiMinimized = !state.isUiMinimized;
  },
  removeIsUiMinimized: function removeIsUiMinimized(state) {
    state.isUiMinimized = !state.isUiMinimized;
  },`

So, updating a v-on:toggleMinimizeUi = 'removeMinimizeUi' in min-button tag in LexWeb.vue componenet and adding api.MinimizeUi in show Iframe  in lex-web-ui-loader.js solves my problem of toggling effect which i explained above.

Like on changing a locale with toggleMinimizeUi first it was loading chatbot with a class 'lex-web-ui-iframe lex-web-ui-iframe--show lex-web-ui-iframe--minimize' but on changing the locale then it was loading chatbot with class  'lex-web-ui-iframe lex-web-ui-iframe--show' and then on further changing locale it would again load the chatbot normally with class 'lex-web-ui-iframe lex-web-ui-iframe--show lex-web-ui-iframe--minimize'.

Using a api.MinimizeUi in show Iframe key in lex-web-ui-loader.js, on locale change every time, it would load the chatbot with class 'lex-web-ui-iframe lex-web-ui-iframe--show lex-web-ui-iframe--minimize' and v-on:toggleMinimizeUi: "removeMinimizeUi" in min-button content tag in LexWeb.vue component remove the lex-web-ui-iframe--minimize class after clicking the button. Please here make a note that I have not changed the on-click function in MinButton.vue component. It is the same as it was :         `v-on:click.stop="toggleMinimize"`

And in order to minimize the chatbot when it is maximized, added `v-on:toggleMinimizeUi="MinimizeUi` in toolbar container tag of LexWeb.vue component. Here also I have not changed the v-on:click.stop="toggleMinimize" thing.
