### ISSUE TITLE
Cannot change title on tab

### ISSUE THREAD

**Issue by nanyoci** [aws-samples/aws-lex-web-ui#306]
The default title on tab is "Order Flowers Bot" and theme color. I tried changing the lex-web-ui-loader-config.json and  lex-web-ui.js files, index.html but the title is still the same. 

Is it possible to change the toolbar name?

**Comment by atoa** [comment]
Have you tried setting the tittle using the `ui.pageTittle` config field in your lex-web-ui-loader-config.json file?

**Comment by rexosariemen** [comment]
@nanyoci If you're using it as an iFrame, you have control over the title of html index page metadata. I believe the value of the title tag here will be reflected on the browser tab for your page

**Comment by Anastasiyatik** [comment]
> Have you tried setting the tittle using the `ui.pageTittle` config field in your lex-web-ui-loader-config.json file?

I have the same issue. I didn't file ui.pageTittle attribute. Any luck to fix this?
