### ISSUE TITLE
Multiple Parent origin support

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#309]
Hey, I have created a lex chatbot and deployed it using lex-web-ui. 

Is there any way that instead of creating different deployment package, we can have multiple urls of the same domain name to the WebparentOrigin path in the cloudformation stack, so that chatbot should be available on all the environments.

I checked some of the previously asked question and tried giving wildcard domain name https://*.mydomainname.com in the cors policy of the S3 bucket, but it is not working. Chatbot becomes available only for the url added in parentOrigin of lex-web-ui-loader-config.json file.

Can you please help me in this?

**Comment by ojo-john** [comment]
Did you figure this out?

**Comment by karanakatle** [comment]
Nope..

**Comment by SharvariNagesh** [comment]
We are also facing the same problem. not able to have multiple origins. We tried having multiple origins separated by comma. but no luck. If any one has any suggestions, please post

**Comment by karanakatle** [comment]
I figure out a way for this and I guess you people might have tried that.

Creating a different alias of chatbot (for ex: dev and prod) and configuring that alias under the botAlias field of cloudformation stack and then creating a different cloudformation stack for different domains.

Means, for development parent URL botAlias should be dev and then for production parent URL botAlias should be prod.

In this case if we make any change in the Dev alias if chatbot, it won't affect prod alias unless we publish that version under prod alias.

In this case if tou make any changes

**Comment by sk814** [comment]
I have a single s3 bucket used by different sites (.com and .de) using cloud front, not sure how to create 2 parent origins of the LexV2 Chatbot UI. If any one has any solution, please help.

**Comment by bobpskier** [comment]
@sk814 I think the best bet would be to deploy lexwebui twice. Configure one for each parent origin. Each lexwebui can support a single parent origin. Then in the "parent" html page hosted in the single s3 bucket, conditionally load the appropriate lexwebui based on the origin the client is operating against. Each lexwebui will have its own snippet of code. Both of these would be placed on the single parent page however only one would be used / selected based on origin the client is requesting.

**Comment by sv1033** [comment]
@karanakatle  
I need to integrate chatbot into more than 1000 web sites. in this case do I need to create a more than 100 aliases and stacks? this may not be the ideal way of doing. is there a way how can I give multiple (100 website origins) in a **WebAppParentOrigin** section? Please answer. Thank you

**Comment by sv1033** [comment]
> I figure out a way for this and I guess you people might have tried that.
> 
> Creating a different alias of chatbot (for ex: dev and prod) and configuring that alias under the botAlias field of cloudformation stack and then creating a different cloudformation stack for different domains.
> 
> Means, for development parent URL botAlias should be dev and then for production parent URL botAlias should be prod.
> 
> In this case if we make any change in the Dev alias of chatbot, it won't affect prod alias unless we publish that version under prod alias.

I need to integrate chatbot into more than 1000 web sites. in this case do I need to create a more than 100 aliases and stacks? this may not be the ideal way of doing. is there a way how can I give multiple (100 website origins) in a WebAppParentOrigin section? Please answer. Thank you

**Comment by sv1033** [comment]
> I figure out a way for this and I guess you people might have tried that.
> 
> Creating a different alias of chatbot (for ex: dev and prod) and configuring that alias under the botAlias field of cloudformation stack and then creating a different cloudformation stack for different domains.
> 
> Means, for development parent URL botAlias should be dev and then for production parent URL botAlias should be prod.
> 
> In this case if we make any change in the Dev alias of chatbot, it won't affect prod alias unless we publish that version under prod alias.

I need to integrate chatbot into more than 100 web sites. in this case do I need to create a more than 100 aliases and stacks? this may not be the ideal way of doing. is there a way how can I give multiple (100 website origins) in a WebAppParentOrigin section? Please answer. Thank you

**Comment by sv1033** [comment]
I need to integrate chatbot into more than 100 web sites. in this case do I need to create a more than 100 aliases and stacks? this may not be the ideal way of doing. is there a way how can I give multiple (100 website origins) in a WebAppParentOrigin section? Please answer. Thank you

**Comment by jawwadturabi** [comment]
facing same problem. Need support for multiple parent origin
