### ISSUE TITLE
compiling lex-web-ui.min.js

### ISSUE THREAD

**Issue by SharvariNagesh** [aws-samples/aws-lex-web-ui#315]
When I compile the module using "`npm run build-dist`" or `npm run build:prod` or `npm run build:lib-prod`, I see that lex-web-ui.min.js and lex-web-ui.min.css files are not getting created in the "dist" folder. The issue BUILD_TARGET is not recognized when we run the commands. Can anyone help me with the steps to create these files. I am not very good with javascript. If you can give me detailed steps to create these two files, it will be very helpful.
Thanks in advance.

**Comment by kalyanigaydhane** [comment]
Hello sharvari,

I am able to run this code on linux platform. in the lex-web-ui folder first you can build the dist folder by using below command:
lex-web-ui >> npm run build-dist
 in this step you will see a new build of dist folder. once it is done. you can execute below command in master directory build folder:
 . release.sh
 the second step is for production build.

**Comment by bobpskier** [comment]
@SharvariNagesh Hopefully the build and release steps are working for you now. If not, please reopen this issue.
