### ISSUE TITLE
Cannot run AWS Lex inside an iframe

### ISSUE THREAD

**Issue by dougofredo** [aws-samples/aws-lex-web-ui#322]
Hello,
I'm trying to add an iframe with my aws bot inside a very simple Html page.
I've followed the steps described [https://github.com/aws-samples/aws-lex-web-ui#iframe](url) by adding the libraries and related files from the dist directory into one of my folder.

This is the link to my code [https://github.com/dougofredo/awsLexIFrame](url)
My code is deployed here: [https://main.derco5fondey5.amplifyapp.com/](url)

The bot won't load and I get the following errors. Some of the files are not being found.
This is from the console. Thanks for your input!

/lex-web-ui-loader-config.json/:1 Failed to load resource: the server responded with a status of 404 ()
​ Error: failed to get chatbot config with status: 404
    at XMLHttpRequest.xhr.onload (config-loader.js:95)
(anonymous) @ main.derco5fondey5.amplifyapp.com/:69
/favicon.ico/:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by bobpskier** [comment]
Have you looked at deploying the prebuilt version (cloud formation template) and then using the snippet of html / javascript provide as output from the stack? This is probably the quickest and easiest approach to embedding the lex-web-ui iframe in an html page.

**Comment by dougofredo** [comment]
Thank you!
It did work. I used as explained the snippet URL from the stack and copied in my index.html 

This is how my code looks like now:

`<!DOCTYPE HTML>

<html>
	<head>
		<title>Bot example</title>
	</head>
	<body>
        <div>
                
                <script src="https://***********.cloudfront.net/lex-web-ui-loader.min.js"></script>
                <script>
                var loaderOpts = {
                    baseUrl: 'https://***********.cloudfront.net/',
                    shouldLoadMinDeps: true
                };
                var loader = new ChatBotUiLoader.IframeLoader(loaderOpts);
                loader.load()
                    .catch(function (error) { console.error(error); });
                </script>
             
        </div>	  	
	  </body>
</html>`
