### ISSUE TITLE
Passing session attributes through Lex Web-Ui

### ISSUE THREAD

**Issue by abhat2** [aws-samples/aws-lex-web-ui#33]
I am trying to send session attributes to Lex when the user starts interacting with the web-ui. My intention for the chatbot is to send an email to the user at the end of the conversation. I have a site that utilizes Amazon Cognito User Pools and I can retrieve the signed in user's email address on the browser end.

My lambda function is able to handle the incoming session attributes from a PostText request (this works when I do the request outside the web-ui). However, I need to handle this PostText request when ever the user interacts with the web-ui.

So everytime the user types a message in the web-ui, their email address (session attribute) is passed to Amazon Lex.

How do I pass values to this function from the web browser?

**Lex-Web-Ui.js**

`  __WEBPACK_IMPORTED_MODULE_1_babel_runtime_helpers_createClass___default()(_class, [{
    key: 'initCredentials',
    value: function initCredentials(credentials) {
      this.credentials = credentials;
      this.lexRuntimeClient.config.credentials = this.credentials;
      this.userId = credentials.identityId ? credentials.identityId : this.userId;
    }
  }, {
    key: 'postText',
    value: function postText(inputText) {
      var _this = this;

      var sessionAttributes = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};

      var sessionAttr = getUserAttributes();

      console.log(sessionAttr);

      var postTextReq = this.lexRuntimeClient.postText({
        botAlias: this.botAlias,
        botName: this.botName,
        userId: this.userId,
        inputText: inputText,
        sessionAttributes:  [PASS VALUE HERE]
      });
      return this.credentials.getPromise().then(function (creds) {
        return creds && _this.initCredentials(creds);
      }).then(function () {
        return postTextReq.promise();
      });
    }
  },`

**Comment by kirstenEhlers** [comment]
I'm not sure if this is what you want, but I solved a similar problem here: https://stackoverflow.com/questions/56259721/how-do-i-pass-a-parameter-from-my-website-in-javascript-to-my-amazon-bot-when
