### ISSUE TITLE
Response card not displayed on Web UI for Lex V2

### ISSUE THREAD

**Issue by amitdubay** [aws-samples/aws-lex-web-ui#332]
I have built a Lex V2 Bot, after entering the intent it presents a response card with a few buttons as part of the slot. The data is being returned correctly from the Bot, and it does work in the Test widget on AWS console, but for some reason it doesn't render in the web chat window. 

Please let me know if there is anything I am missing in setting this up.

Below is the response returned from the Bot that I can see in the parent.html page, but the UI doesn't display it.

{
  "version": "1",
  "contentType": "application/vnd.amazonaws.card.generic",
  "genericAttachments": [
    {
      "title": "Please select an option",
      "subtitle": "I want to...",
      "imageUrl": "https://hidden.amazonaws.com/assets/images/logo.svg",
      "buttons": [
        {
          "text": "When is my next appointment?",
          "value": "When is my next appointment?"
        },
        {
          "text": "Where is my appointment?",
          "value": "Where is my appointment?"
        },
        {
          "text": "I want to cancel or reschedule my appointment.",
          "value": "I want to cancel or reschedule my appointment."
        }
      ]
    }
  ]
}

**Comment by bobpskier** [comment]
Your response looks more like a response for a Lex V1 bot postText request. See https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostText.html. 

For a Lex V2 bot, the response to recognizeText is defined at https://docs.aws.amazon.com/lexv2/latest/dg/API_runtime_RecognizeText.html

Plugging your example into a V2 QnABot using a different png image as part of the imageUrl returns a payload that includes the following. Notice the response card is part of the array of messages.

When configured to use a Lex V2 bot, LexWebUi will expect this format of response. 

```
    "interpretations": [
        {
            "intent": {
                "confirmationState": "None",
                "name": "QnaIntent",
                "slots": {
                    "qnaslot": {
                        "value": {
                            "interpretedValue": "help",
                            "originalValue": "help",
                            "resolvedValues": [
                                "help",
                                "help me"
                            ]
                        }
                    }
                },
                "state": "Fulfilled"
            },
            "nluConfidence": {
                "score": 1.0
            }
        },
        {
            "intent": {
                "name": "FallbackIntent",
                "slots": {}
            }
        }
    ],
    "messages": [
        {
            "content": "Please select an option",
            "contentType": "PlainText"
        },
        {
            "contentType": "ImageResponseCard",
            "imageResponseCard": {
                "buttons": [
                    {
                        "text": "When is my next appointment?",
                        "value": "When is my next appointment?"
                    },
                    {
                        "text": "Where is my appointment?",
                        "value": "Where is my appointment?"
                    },
                    {
                        "text": "I want to cancel or reschedule my appointment.",
                        "value": "I want to cancel or reschedule my appointment."
                    }
                ],
                "imageUrl": "https://d1.awsstatic.com/webteam/homepage/F45D%20HP/illustration_digital_blue-inverse_275x135.0331d1deeb7079d2e286e51c34cdafabd4123373.png",
                "title": "Please select an option"
            }
        }
    ],
    "sessionId": "us-west-2:221b8c5f-360b-44e3-a87e-5314a23fef52",
    "sessionState": {
        "dialogAction": {
            "type": "Close"
        },
        "intent": {
            "confirmationState": "None",
            "name": "QnaIntent",
            "slots": {
                "qnaslot": {
                    "value": {
                        "interpretedValue": "help",
                        "originalValue": "help",
                        "resolvedValues": [
                            "help",
                            "help me"
                        ]
                    }
                }
            },
            "state": "Fulfilled"
        },
        "originatingRequestId": "b8c35e56-f622-4336-baca-21ec5577d854",
       
            
        }
    }
}
```

**Comment by amitdubay** [comment]
Thank you for the response @bobpskier . Is there any documentation on how this can be configured on a V2 bot, I followed the steps as mentioned in the link below, but it still returns V1 response.  Appreciate your help.

https://aws.amazon.com/blogs/machine-learning/creating-a-bankingbot-on-amazon-lex-v2-console-with-support-for-english-and-spanish/

**Comment by bobpskier** [comment]
LexWebUi will operate either with a Lex version 1 bot OR a Lex version 2 bot but not both at the same time. There are fields in the template that define the Lex V1 parameters or the Lex V2 parameters. 

BotName is a Lex V1 parameter. Once LexWebUi is configured with a BotName it will always use the Lex V1 postText API. LexWebUi will send postText requests to this V1 bot. If these postText requests are succeeding, then a bot named 'bankingBot' must exist in the Lex V1 console. If this is unintentional then you should delete the bankingBot from the Lex V1 console.  You'll need to redeploy a new LexWebUi that targets the V2 bankingBot. 

To configure LexWebUi to use a Lex V2 bot, all the three fields for LexV2 should be filled in. These are LexV2BotId, LexV2BotAliasId, and LexV2BotLocaleId. In addition all the fields in the Lex V1 parameter section should remain empty. Note that LexV2BotId is not equal to the BotName. 

I tested setting up a V2 bankingBot after first setting up use of the Lex V2 console. I progressed through the first welcome intent. Deviating a bit from the blog post, I added a card group and button to the response in the Lex V2 console for the english welcome intent. I then saved the updated intent, performed a build, and then setup a new version of the bot. Finally I assigned the alias being used by LexWebUi to use the new version. 

Next I used LexWebUi to target this lex V2 bot. 

The Lex V2 bot properly returns the following when I type in hi to the lexwebui. This is returned via the recognizeText API on Lex V2. 

```
{
  "interpretations": [
    {
      "intent": {
        "confirmationState": "None",
        "name": "Welcome",
        "slots": {},
        "state": "Fulfilled"
      },
      "nluConfidence": {
        "score": 1.0
      }
    },
    {
      "intent": {
        "name": "FallbackIntent",
        "slots": {}
      }
    }
  ],
  "messages": [
    {
      "content": "Hi! I’m BB, the BankingBot. How can I help you today?",
      "contentType": "PlainText"
    },
    {
      "contentType": "ImageResponseCard",
      "imageResponseCard": {
        "buttons": [
          {
            "text": "Hello",
            "value": "Hello"
          }
        ],
        "title": "Options"
      }
    }
  ],
  "sessionId": "us-west-2:a2d353ef-a68d-4165-ac0b-679346eadf02",
  "sessionState": {
    "dialogAction": {
      "type": "Close"
    },
    "intent": {
      "confirmationState": "None",
      "name": "Welcome",
      "slots": {},
      "state": "Fulfilled"
    },
    "originatingRequestId": "9fba7b38-a6a2-40c9-96be-09fcb4f7424f",
    "sessionAttributes": {
      "localTimeZone": "\"America/Denver\""
    }
  }
}
```
I hope this helps solve the configuration issues you are running into. First make sure you don't have a V1 bot named 'bankingBot'. You'll need to delete the existing LexWebUi stack and redeploy a new stack using the V2 bot identifiers.

**Comment by amitdubay** [comment]
Thank you @bobpskier for detailed explanation, though there are bots in V1 they are named differently. I will still delete everything and recreate it to see if that helps by providing the LexV2BotId, LexV2BotAliasId, and LexV2BotLocaleId. I have taken the ID for both name and alias which is a code that's different from the name.

I will let you if it resolves the issue. I truly appreciate your time looking into this.

**Comment by amitdubay** [comment]
I deleted everything and recreated the Bot. I setup a new version this time, which I didn't do previously, was using the default draft, it works now with the new version!

Thank you so much @bobpskier !

**Comment by amitdubay** [comment]
I probably overlooked the config file because while creating the stack, I had to give the botAlias because of which the botName was also populated in the config file which was the same as V2BotId. That was the reason it was working because it was connecting to V1, have opened another issue mentioning that the CFT won't proceed if botAlias is kept blank. Manually updating the config file to remove the botName and botAlias leaves the web app in a broken state where the app times out connecting to the Bot.
