### ISSUE TITLE
build:lib-prod issue

### ISSUE THREAD

**Issue by gribchic** [aws-samples/aws-lex-web-ui#336]
I try to run script build:lib-prod
it emits an issue:
'BUILD_TARGET' is not recognized as an internal or external command,
I use Webstorm on Windows 10 OS

**Comment by bobpskier** [comment]
You'll need to build on OSX, Linux, AWS Cloud9 IDE, or use the Linux subsystem on Windows. Builds can be performed using  npm commands both at the root level and in the folder lex-web-ui. The build/release.sh provides the definitive mechanism to perform a build. The following engines are required as defined in package.json.

  "engines": {
    "node": ">= 12.0.0",
    "npm": ">= 7.10.0"
  }
  
  After building, localhost use can be started using "npm run start" in the lex-web-ui folder.
  
  The lex-web-ui can be installed from prebuilt distributions referenced in the top level readme.
