### ISSUE TITLE
Response card is not getting

### ISSUE THREAD

**Issue by user-preethy** [aws-samples/aws-lex-web-ui#338]
I am using lex v2 version and I have own bot..I used bot id ,bot alias id etc in stack creation.My Bot is integrated with lambda also and it is working fine in lex itself..In lex web, response card is not getting.What to do?

**Comment by bobpskier** [comment]
Is a link to your page hosting the LexWebUi shareable? We can look at the response back to the LexWebUi and see what the issue might be.

**Comment by user-preethy** [comment]
![20211119_105839](https://user-images.githubusercontent.com/93519481/142572099-18451adf-87de-4164-97a5-aa5843c4c015.jpg)
During stack creation, I gave BotAlias in Lex V1 otherwise it shows errors.

**Comment by bobpskier** [comment]
Could you share the V2 Response payload from the network tab in your browser debugger? If would look like the following:
![V2response](https://user-images.githubusercontent.com/11319101/142631807-764a89f2-d79a-4017-bb80-6fdae7e9b8ca.png)

**Comment by user-preethy** [comment]
![20211122_131647](https://user-images.githubusercontent.com/93519481/142822893-3ed94ace-3d89-4722-8840-121efe7efd9f.jpg)

**Comment by user-preethy** [comment]
![Uploading 20211122_144250.jpg…]()

**Comment by user-preethy** [comment]
![20211122_144250](https://user-images.githubusercontent.com/93519481/142834364-355198d2-25fe-4da6-b705-708ffffc4299.jpg)

**Comment by bobpskier** [comment]
The fundamental difference from the two images above that will affect how LexWebUi works is the first entry in the messages array that I posted. In this example, a message with a string in "content" and a contentType of "PlainText" is present. LexWebUi in its current implementation will require an element in the messages array with content.  
```
... ,
{
    "content": "This would be displayed in the message bubble",
    "contentType": "PlainText"
} ,   
... 
```

It will not be able to support just an ImageResponseCard.

Could you test adding in a simple message to your bot's response in addition to the ImageResponseCard?

I'll see if a mechanism can be developed which processes messages that only have an ImageResponseCard.

**Comment by user-preethy** [comment]
Thank you sir..Now its partially works..Response card created via lambda works fine now..But some response cards are created in lex itself..That is not getting.
