### ISSUE TITLE
Output 'SnippetUrl' not found in stack 'arn:aws:cloudformation:us-east-1.....'

### ISSUE THREAD

**Issue by rdsingleton** [aws-samples/aws-lex-web-ui#35]
I get this issue when trying to deploy using the pipeline mode.  I haven't changed any of the default settings apart from selecting my own bot which I created in the same region.  

What am I doing wrong?

Thanks

**Comment by bhaskarbj197** [comment]
I am also facing similar problem. When I am trying to deploy using Pipeline and default settings, it gives me same error - SnippetUrl' not found in stack .......

Have you resolved this issue? Thanks in advance.

**Comment by JohnCalhoun** [comment]
checking in on this.

so there is no "SnippetUrl" in the stack outputs in the AWS console?
what is the exact error and where are you seeing it?

**Comment by DVGalarza** [comment]
@JohnCalhoun Almost immediately (~30 sec) upon deploying the Pipeline Mode stack, it encounters an error and begins to rollback. When I look under Events for the stack, I see this as the erroring event:

`Output 'SnippetUrl' not found in stack 'arn:aws:cloudformation:us-east-1...'. Rollback requested by user.`
