### ISSUE TITLE
lex-web-ui.js not getting built

### ISSUE THREAD

**Issue by siva-kishore** [aws-samples/aws-lex-web-ui#350]
I need a fresh build. So I run the command npm run build-dev. But only few files are getting build. We need lex-web-ui.js to be rebuild which is not happening. What could be the problem here.

**Comment by chrislott** [comment]
Hello. Have you made sure you have all the dependencies installed?  
See how to install dependencies like vuetify [here](https://github.com/aws-samples/aws-lex-web-ui#npm-install-and-vue-component-use).

Once you get those installed, you can use [this section, Building and Deploying Your Own Lex-Web-UI](https://github.com/aws-samples/aws-lex-web-ui#building-and-deploying-your-own-lexwebui) that has the commands to build your own lex-web-ui. If you want to use the built assets directly, you can ignore the last two lines that upload the assets to S3. For example: 

```
npm install
cd lex-web-ui
npm install
cd ../build
./release.sh
```

Hope this helps!
