### ISSUE TITLE
Voice to Text functionality

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#364]
Hi team, I am trying to use voice to text functionality for a chatbot deployed using AWS LEX WEB UI. It is a Lex V1 chatbot.
For a response card in chatbot if we type the card values, it works fine, but if we try saying card value using the microphone option it gives an error with utterance 'Sorry, I had an error handling this conversation.'. 
I checked previous response regarding this issue but didn't understood properly. The snapshot of error which i am getting in network debugger tab is attached here. 

Can you please help me in resolving this issue.

![Screenshot (3)_LI](https://user-images.githubusercontent.com/54977850/157130181-aa33d04b-2b77-45fd-a14b-d21acb010e43.jpg)

**Comment by bobpskier** [comment]
Looks like a status code 400 response is being returned to the post content method. Is it possible to look at the Response tab and see what error message is present? My guess is some error with respect to the lex bot handling this post content. From the image it looks like the user would say "yes" or "no" and the bot is having issues interpreting as either yes or no. If there is a lambda backing the bot, check the function for errors during processing as well.

**Comment by karanakatle** [comment]
Hi @bobpskier I looked into it and found a bug. The output voice was selected to None in lex console.

Now there are two problems:
Expectations: If we interact with lex chatbot (deployed using lex web ui) via voice, it should give a response by reading an utterance and response cards. Also bot should display response cards.

Behaviour: 
1. When we configure expected utterance for each slot under Prompt in Lex console and Required field is checked:
a. If we interact with chatbot via voice, it gives response in voice output, but does not show response cards.
b. If we interact with them using text, then it gives response in text format and displays response cards as well

2. When we configure expected utterance for each slot in lambda functions instead of Lex console (unchecking required field in lex console for the slot and providing placeholders in prompt section):
a. If we interact with chatbot via voice, it gives response in text format only (voice output is not there, neither response cards)
b. If we interact with them using text, then it gives response in text format and displays response cards as well

Our chatbot is deployed using 2nd behaviour and we want to make enhancement on it by adding voice to text support. Is there any way to do it?

**Comment by bobpskier** [comment]
Response cards are a limited means of conveying either an image to present or provide input options to the user for their next interaction. As you noted, placing URLs in response card buttons will only configure the LexWebUi to send those URLs as a postText if clicked. Also, Lex does not compile an audio response using content from a responseCard. Since audio is not provided in the response to LexWebui from Lex, its not possible to play a response card as audio.

In terms of a hyperlink, the best to way to present this to user is via markdown in the appContext session attribute which will be presented as a link in the message in LexWebUi. See https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#markdown-and-html-support.

**Comment by karanakatle** [comment]
@bobpskier I tried with it:

`                session_attributes['appContext'] =  {
                                                   "altMessages": {
                                                              "markdown": {
                                                                "ssml": '<speak>Great! I can help you with that! \
                                                                            <br>\
                                                                            [Click on help link for more details]('+help_link+' "Help")
                                                                            <br>\
                                                                            Ready? \
                                                                            [Apply Now]('+apply_now_link+' "Apply Now")</speak>'
                                                              }
                                                            }
                                                          }
                response = {
                    'sessionAttributes': session_attributes,
                    'dialogAction': {
                        'type': 'Close',
                        'fulfillmentState': 'Fulfilled',
                            }
                        }`

after this i am returning a response

In lex console, it is giving me error "An error has occurred: The server encountered an error processing the Lambda response"

I am checking with cloudwatch, cant find the errors there as well?
