### ISSUE TITLE
Issue with sessionAttributes being reset to an empty object

### ISSUE THREAD

**Issue by PiotrRut** [aws-samples/aws-lex-web-ui#370]
This issue keeps happening regardless of whether `reInitSessionAttributesOnRestart` is true or false - it seems that every now and then, the `sessionAttributes` are being reset between intents/refreshes of the page, which results in them being sent as an empty object with each Lex call, hence not providing the necessary information to the lambda functions.

Any idea as to why this might be and how this can be mitigated?

**Comment by PiotrRut** [comment]
Actually upon further investigation, I think it happens when I "clear chat" - I reckon that clears sessionStorage, and along with it the `sessionAttributes`. Any way to stop that? Is the only solution for this to refresh the page, which will re-mount the web ui and reload the script with the attributes?
<img width="166" alt="image" src="https://user-images.githubusercontent.com/43642399/160432478-0f3d5103-ac38-4c0d-b895-8644ee9873ae.png">

**Comment by bobpskier** [comment]
@PiotrRut The clear chat UI element uses the resetHistory function in lex-web-ui/src/store/actions.js. resetHistory mutates the state by calling clearMessages in lex-web-ui/src/store/mutations.js. clearMessages resets the state.messages array to an empty list and sets state.lex.sessionAttributes to an empty object. 

The reason it clears sessionAttributes is that the UI is being reset to an initial state just as if the bot has never been called before and will display initial text or markdown if configured in lex-web-ui. That is probably more than it should do especially if login is enabled and tokens are being stored in session attributes. However, that is what is implemented at the present time. 

A quick fix would be to change clearMessages to not reset sessionAttributes to an empty object. Is there any state in your bot that would need to be cleared if messages are being cleared? 

Are you building your own version or deploying from the prebuilt version? You could make this change and test a deployment with it to see what other side affects you might encounter. 

Is enabling history needed in the short term? You could change the this template parameter to false and remove the clear history menu item.
