### ISSUE TITLE
Getting vue dependency failure for deployed chatbot

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#378]
Hi Team, we are getting a vue dependency failure for deployed chatbots suddenly. Screenshots are attached for your reference.

![Screenshot (18)](https://user-images.githubusercontent.com/54977850/164291932-12401252-0f3c-4f92-bd17-ab39caf3569c.png)

Can you please help me in this.

**Comment by bobpskier** [comment]
@karanakatle Browser is trying to load vue.min.js from https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js and is being prevented by browser from what looks like a CA cert issue. I just tried on a number of running lex web ui instances and they are able to pull from this url. Are you switching vpns used by the browser or changing browser config? Its a cloudflare cert I think with a CA of Baltimore CyberTrust Root.

**Comment by bobpskier** [comment]
@karanakatle For me switching vpn is problematic for browsers until I restart the browser and then most of the times clear cache. I see this across a wide range of vpns on most of the web sites I use. This specific error to me means the browsers you are using in conjunction with the vpn / no vpn config on your OS are not handling CA certificate verification from the cdn.jsdeliver.net site. The browsers refuse to load the vue js file and hence the UI can't start. From your browser can you directly load https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js  and then look at the certificate? Are there any differences when you are on or off vpn? Are there any differences between browsers? Are you experiencing a man in the middle attack? For whatever reason, your browser is not happy with the CA cert from this resource whomever is supplying it and is preventing it from loading.
