### ISSUE TITLE
lex-web-ui loaded as icon(load.min) on desktop browser while mobile device browser loaded as full page till we min the page to icon

### ISSUE THREAD

**Issue by jasonzhangvdr** [aws-samples/aws-lex-web-ui#383]
We deployed 0.19.4 lex-web-ui and defined index.html as following, the desktop browser shows bot in icon mode(minimized) while mobile device browser shows bot as full page, instead of as icon.
Here is index first few lines:  
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">
    <title>LexWebUi Demo</title>
    <link href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII=" rel="icon" type="image/x-icon"/>
    <link href="lex-web-ui-loader.min.css" rel="stylesheet">
    <link rel="stylesheet" href="./custom-chatbot-style.css">
    </head>
    <body>
      <script src="lex-web-ui-loader.min.js"></script>
--------------------------------------------------------------------------------

Here is the lex-web-ui-loader-config.json for iframe session:
  "iframe": {
    "iframeOrigin": "https://XXXXXXXXXXXXXXXX",
    "shouldLoadIframeMinimized": true,
    "iframeSrcPath": "/index.html#/?lexWebUiEmbed=true"
  }
}

**Comment by chrislott** [comment]
Hi jasonzhangvdr,

Which mobile device / browser are you using?

**Comment by jasonzhangvdr** [comment]
We found the root cause, and fixed the issue
