### ISSUE TITLE
Readme organization

### ISSUE THREAD

**Issue by t-jones** [aws-samples/aws-lex-web-ui#384]
Your readme would be easier to consume if you moved the changelog to the bottom of the page.  As a new developer using lex web ui, I had to scroll 2/3 down the page to get started, and then it wasn't clear that I was in the right place.

My opinion.  If you think it's a good idea, lmk and I'll submit a PR.

Great framework.

**Comment by chrislott** [comment]
Yes, that would be great - send PR please.

**Comment by t-jones** [comment]
Done.  #386
