### ISSUE TITLE
Buttons repeating for each message for a prompt

### ISSUE THREAD

**Issue by gokula-krishna-dev** [aws-samples/aws-lex-web-ui#387]
I am customizing the CSS for my Lex. I am sending multiple messages for each prompt followed by 2 buttons. The buttons are repeated for each message of a prompt but on the test console, it appears once for a prompt. 

Can anyone help me resolve this issue?

<img width="659" alt="image (4)" src="https://user-images.githubusercontent.com/33853819/167061813-96705c50-283b-4ea6-b33a-f55d9ee48621.png">

**Comment by SandeepPasula898** [comment]
Hi @bobpskier, I am also facing similar issue. In my response, I have 3 messages and 1 response card. But in UI it looks as below.
![image](https://user-images.githubusercontent.com/42517479/177739999-d6998f2e-8d4e-454c-a206-f93a14a8631a.png)
My response in network tab looks as below:
![image](https://user-images.githubusercontent.com/42517479/177741004-16255aed-7970-449f-8ea7-c375f50a99c1.png)

Note: I have tested with lex-web-ui (downloaded in 2021) in my local machine, No problems faced with that version. Only latest stack have issue. Please fix this one...

**Comment by bobpskier** [comment]
@SandeepPasula898 I've reproduced the issue and am working on a solution. I'll update you tomorrow with status.

**Comment by bobpskier** [comment]
@SandeepPasula898 I submitted a pull request (405) with a fix for this issue. Up to the AWS team to accept the pull request and merge into development and then release on master branch.

**Comment by chrislott** [comment]
Thanks @bobpskier and @gokula-krishna-dev and @SandeepPasula89, will pull this fix in and make a release with some other fixes soon.
