### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by jasonzhangvdr** [aws-samples/aws-lex-web-ui#388]
Failed to load resource: the server responded with a status of 403 ()

**Comment by bobpskier** [comment]
Most likely this is due to a CORS error where the parent origin configured is not the same as the actual page hosting the lex-web-ui. Your browser debugger in the network tab might show the errors being encountered. Can you capture some of the 403 responses and post here.
