### ISSUE TITLE
The Bot created in Amazon Lex V2 is not working in the solution.

### ISSUE THREAD

**Issue by FranklinBulmez** [aws-samples/aws-lex-web-ui#392]
I have tried to complete all the functionality, but I cannot get the Bot that I have created to activate in the chat, it continually gives me the error "Sorry, I was unable to process your message. Try again later." The Bot is configured in the V2 console and is fully tested. During the creation process, the slack did not indicate any creation error. If anyone has suggestions they will be well received, thanks in advance.

**Comment by bobpskier** [comment]
@FranklinBulmez The failure will be indicated in the response from the lex which you can see in the browser debugger in the network tab. First thing to check is to make sure the post request is being made to RecognizeUtterance. This indicates that LexWebUi is indeed sending the request using LexV2. Did you configure any string in the Lex V1 BotName field in the LexWebUi template? If you filled in the Lex V1 BotName field, LexWebUi will use V1 irregardless of parameters supplied for the Lex V2 area of the template. Once you know the error provided in the response, it will be a bit easier to figure out how to correct it.

**Comment by bobpskier** [comment]
@FranklinBulmez Another possible error is if the Lex V2 Bot calls a fulfillment lambda and that lambda fails or returns an error. The error message returned in the RecognizeUtterance request might indicate this as well.

**Comment by FranklinBulmez** [comment]
Thanks @bobpskier , I will review what you tell me, anything I tell you, thank you very much for your support.
