### ISSUE TITLE
Slot type for accepting Amount (in dollars and cents) for Lex V2 multilingual bot

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#394]
We have a multilingual bot built on LexV2 (voice integrated) for English, spanish, korean, japanese, chinese and portugese locales.
For amount question we have used a custom slot with expand values as a resolution type and given numeric, alphanumeric characters, numeric characters with decimals, dollar signs, commas, strings such as "one thousand dollars and thirty cents", "1 dollar", "thirty cents", etc. 

Now most of the time it is accepting the same value which we feed in custom slot type Ex., if we feed 8345, the slots will accept input for 8345 only, if we enter any other 4 digit number, it gives error, similarlly we type "one thousand dollars and thirty cents", it will accept it but for "two thousand dollars and twenty cents" it will give an error.
Note: Total number of samples that i used for custom slot type are 10.

We also tried for using grammer slot type, but it cant be used for other locales. Is there any way we can solve this?

**Comment by chrislott** [comment]
What about custom slot types for dollars and cents for each language?

"{Dollars} dollars and {Cents} cents" as an example utterance?
