### ISSUE TITLE
Embed chatbot in ReactJS site behind AWS Cognito authentication

### ISSUE THREAD

**Issue by wcheek** [aws-samples/aws-lex-web-ui#395]
I want to build a React site that uses authentication to sign users in before gaining access to the chatbot interface. 

I'm able to add a deployed bot to my site using the SnippetUrl, following [this method](https://catalog.us-east-1.prod.workshops.aws/workshops/94f60d43-15b7-45f4-bbbc-17889ae64ea0/en-US/lexwebui/embedding).

I can get the bot working on my site by doing what is suggested, just adding the snippet to the end of my `<body>` in `index.html`. Unfortunately this means that the bot will show as a widget on every page of the ReactJS app, including on the auth page.

I'm very new to React. I have been thinking to 'inject' the snippet the same way that I inject the React code from `App.js` into `index.html`, but I'm not sure how to do this. It seems like simply pasting the HTML into the React app isn't going to cut it.

I've tried approaches like those [here](https://www.codingdeft.com/posts/react-add-script/) but once the script is loaded, how do I go about using the script to load the chatbot? I can't get `ChatBotUiLoader` to be an object to work with.

Below is my snippet that should end up in `index.html` somehow (but not before a user is authenticated..)
```html
    <script src="https://d2hzdehxxxxx.cloudfront.net/lex-web-ui-loader.min.js"></script>
    <script>
      var loaderOpts = {
        baseUrl: "https://d2hzdehxxxxx.cloudfront.net/",
        shouldLoadMinDeps: true,
      };
      var loader = new ChatBotUiLoader.IframeLoader(loaderOpts);
      var chatbotUiConfig = {
        /* Example of setting session attributes on parent page
          lex: {
          sessionAttributes: {
          userAgent: navigator.userAgent,
          QNAClientFilter: ''
          }
          }
        */
      };
      loader.load(chatbotUiConfig).catch(function (error) {
        console.error(error);
      });
    </script>
```

Below find my `App.js` code with working authentication:
```javascript
import React from "react";
import { Amplify } from "aws-amplify";
import {
  AmplifyProvider,
  Authenticator,
  Button,
  Flex,
  Image,
  Text,
  View,
} from "@aws-amplify/ui-react";

import { COGNITO } from "./configs/aws";
import "@aws-amplify/ui-react/styles.css";
import theme from "./theme";
import logo from "./logo.svg";

Amplify.configure({
  aws_cognito_region: COGNITO.REGION,
  aws_user_pools_id: COGNITO.USER_POOL_ID,
  aws_user_pools_web_client_id: COGNITO.APP_CLIENT_ID,
});
const App = () => {
  return (
    <AmplifyProvider theme={theme}>
      <Authenticator>
        {({ signOut, user }) => (
          <Flex
            direction="column"
            justifyContent="flex-start"
            alignItems="center"
            alignContent="flex-start"
            wrap="nowrap"
            gap="1rem"
            textAlign="center"
          >
            <Image src={logo} alt="logo" width={240} height={240} />
            <View width="100%"></View>
            {user && (
              <View width="100%">
                <Text>Hello {user.username}</Text>
                <Button onClick={signOut}>
                  <Text>Sign Out</Text>
                </Button>
              </View>
            )}
            <View width="100%">
              <Text>
                Edit <code>src/App.js</code> and save to reload.
              </Text>
            </View>
            <div className="App"></div>
          </Flex>
        )}
      </Authenticator>
    </AmplifyProvider>
  );
};

export default App;
```

**Comment by bobpskier** [comment]
@wcheek I'm not a react developer however can a function like the following be dynamically called after successful login completes.

After login, have the document create a script element. Asynchronously load the loader min js. When async load of this script completes, then instantiate a new ChatBotUiLoader.IframeLoader passing in loaderOpts. With a new loader object, call the load() method passing in the config object. Once this load completes, use the loader.api to start a new lex session and post any initial text that you'd like to prime the bot with. The lex script element created at the start of the function is appended to the document as part of onload. 

I've seen this pseudo code work elsewhere such as inside a vue app. It could be conditionally executed based on window origin location or perhaps again if you can key off a successful login, maybe this can be run dynamically to load in the bot. 

```
export const buildAndInitLexWebUI = () => {
    const lex = document.createElement('script')
    lex.src = 'https://d#######.cloudfront.net/lex-web-ui-loader.min.js' // your distribution
    lex.onload = async function () {
        const loaderOpts = {
            baseUrl: 'https://d#######.cloudfront.net/', // your distribution
            shouldLoadMinDeps: true
        }
        const loader = new window.ChatBotUiLoader.IframeLoader(loaderOpts)
        const config = {
            lex: {
                sessionAttributes: {
                    userAgent: navigator.userAgent
                },
            },
        }
        loader.load(config).then(function () {
            loader.api.startNewSession()
            loader.api.postText('Startup Text if needed')
        }).catch(function (error) {
            console.error(error)
        })
        document.body.appendChild(lex)
    }
}
```

**Comment by wcheek** [comment]
@bobpskier thanks so much for your help. I unfortunately didn't have much luck with this after trying hard to get your function running..
I've now moved on to VueJS in hopes of also getting to this solution. It's looking easier since the chatbot is a native Vue component. I've also reluctantly started using Amplify CLI to get the auth working.
