### ISSUE TITLE
AWS Lex V2 not recognizing voice utterance properly

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#396]
Hi Team,

In Lex V2 bot currently when input mode is speech, if a user is saying yes, it is accepting it as 'its yes', 'yeah sure', 'okay yes'. We are observing the same behaviour in multiple utterances, bot is interpreting those values as yes, but on web ui it is showing 'its yes', 'yeah sure' kind of utterance for 'yes' utterance which user actually used and this looks quite odd. Is there any way we can resolve the issue?

**Comment by bobpskier** [comment]
@karanakatle The inputTranscript field in the response object in Lex V2 contains the transcription of the input audio from the post to recognizeUtterance. Lex web ui will use this in the message bubble as input from the user. You might confirm that inputTranscript does contain the weird response. I checked the V2 API lambda response format and it does not seem to have a mechanism to override the inputTranscript return value which was my first thought at resolving this. It is very hard wired how LexWebUi handles this in terms of displaying user input for audio. I think one could return a very specific session attribute, say something named "inputTranscriptOverride", which contains just the word "yes". Then a code modification to LexWebUi to check for this session attribute and use if present instead of inputTranscript.

**Comment by karanakatle** [comment]
@bobpskier thank you so much, it seems to be a possible solution.. will try with it. I do have one more question. 
We got a bug for initialSpeechInstruction/bot audio for mobile devices, after a initialspeechinstruction/bot audio, even if the audio ends, status remains in the playing audio mode and user is required to click on stop/interrupt mode to go to the listening mode. 
We faced this issue on older devices like Iphone7 plus, in iphone13 it is working fine. I tried looking at lex-web-ui but could not find a possible solution. Any comments on this?

**Comment by bobpskier** [comment]
@karanakatle On old devices such as iPhone 6 and 7, one has to fully enable WebRTC in Safari to make this work. Settings->Safari->Advanced->Experimental Features. There are four WebRTC settings that all must be enabled. I tested on my iPhone 6 device and was able to move past the initial speech instruction prompt.

**Comment by karanakatle** [comment]
@bobpskier thank you so much for the response. Will try with it. Thanks

**Comment by karanakatle** [comment]
@bobpskier 1 more thing which we observed and looks quite odd. 
Even if a user is not speaking, sometimes because of background noise, bot interpret the noise as yes/no utterance. I tried to heard that interpreted voice again using playback option and many times found that they are some random noises. Also some times if an user say thousand dollars, bot interpret as dozen dollars. These looks quite odd. Is there any way we can improve the bots recognising capacity, any kind of settings which I might have missed to look at. In lex V1 i tried using sentiment analysis option but that didn't solve the issue as bot was still interpreting blank noises as yes/no.
Note: We are developing a bot on lex V2. Just to check sentiment analysis part, I went on V1

**Comment by bobpskier** [comment]
For the first issue, there are some parameters that can be adjusted that might have an affect on this aspect in the lex-web-ui recorder config. The file lex-web-ui/src/config/index.js contains the full set of values that can be adjusted in lex-web-ui-loader-config.json file. 

See quietThreshold and volumeThreshold below. 

```
recorder: {
    // if set to true, voice interaction would be enabled on supported browsers
    // set to false if you don't want voice enabled
    enable: true,

    // maximum recording time in seconds
    recordingTimeMax: 10,

    // Minimum recording time in seconds.
    // Used before evaluating if the line is quiet to allow initial pauses
    // before speech
    recordingTimeMin: 2.5,

    // Sound sample threshold to determine if there's silence.
    // This is measured against a value of a sample over a period of time
    // If set too high, it may falsely detect quiet recordings
    // If set too low, it could take long pauses before detecting silence or
    // not detect it at all.
    // Reasonable values seem to be between 0.001 and 0.003
    quietThreshold: 0.002,

    // time before automatically stopping the recording when
    // there's silence. This is compared to a slow decaying
    // sample level so its's value is relative to sound over
    // a period of time. Reasonable times seem to be between 0.2 and 0.5
    quietTimeMin: 0.3,

    // volume threshold in db to determine if there's silence.
    // Volume levels lower than this would trigger a silent event
    // Works in conjuction with `quietThreshold`. Lower (negative) values
    // cause the silence detection to converge faster
    // Reasonable values seem to be between -75 and -55
    volumeThreshold: -65,

    // use automatic mute detection
    useAutoMuteDetect: false,

    // use a bandpass filter on mic input
    useBandPass: false,

    // trim low volume samples at beginning and end of recordings
    encoderUseTrim: false,
  },
  ```
For the second issue, the Lex V2 bot needs to be trained with as many input values as possible. It might be possible to train the bot with the specific phase "thousand dollars" and it might resolve the input utterance correctly. Still accents can be problematic for Lex. You might need to open a support ticket with AWS and the Lex service team to see what might be possible to improve on for the voice recognition aspects of your bot.

**Comment by karanakatle** [comment]
@bobpskier thanks a lot for providing guidance. 
We did the testings by fully enabling webRTC in iphone 6/7, but still it didn't pass the initial speech instruction prompt successfully, user need to click on interrupt/stop button.

**Comment by bobpskier** [comment]
@karanakatle I'm not sure what else to try. With my iPhone 6 this worked for me in Safari browser. All I can suggest is to confirm you are on the last version of iOS that was released for this device. Is there a public link to the page available to test against? I could try from my device and see if I can reproduce.

**Comment by ladabhi** [comment]
@bobpskier yeah we followed the same steps. Infact our bot is working fine in Spanish, Portuguese and korean along with English.. Currently facing a problem with Chinese Mandarin (PRC) only and that too for voice based.. text based it is working fine.

**Comment by ladabhi** [comment]
@bobpskier yeah we followed the same steps. Infact our bot is working fine in Spanish, Portuguese and korean along with English.. Currently facing a problem with Chinese Mandarin (PRC) only and that too for voice based.. text based it is working fine.
