### ISSUE TITLE
Voice Recorder Issues

### ISSUE THREAD

**Issue by karanakatle** [aws-samples/aws-lex-web-ui#402]
Hi Team,

We faced a couple of issues when using voice recorder in lex web ui:

1. When you open an iframe and goes to the listening mode, it works fine at an initial stage, but when you change your browser/tabs/move to different page for 2-3 min and then come back to the iframe, start listening mode it doesn't record voices of the user instead takes blank/white noise as an input.
2. Lets say for question 1 you give an answer yes using voice mode and clicks on pause button for listening mode, lexw-web-ui will pass those recording as an input to lex, but question 2 will not be shown in lex-web-ui. If again you click on the mic button and try giving an answer for a question without pausing it, lex will consider that input as an answer to 2nd question which never showed in UI and directly 3rd question gets popped up. 
Means,when clicked on pause button during conversation,  question 1 and 3 appears in lex-web-ui instead of question 1,2,3.

Is these default behaviour?

**Comment by bobpskier** [comment]
@karanakatle For 1, the recorder will timeout the request when the tab is entered again. Any captured audio will be invalidated on this timeout. The Lex Bot / Intent should elicit a new response from the user in this case based on the state of the session. 

For 2, I'm not sure what you mean by pause button. There is only an interrupt button. The interrupt button cancels the recorder if the UI is listening. No content is sent to the Lex bot. The user can then type in a response or click the mic button to record a new response which will be sent to the bot. if the interrupt button is hit while audio is being played back, the audio playback will be stopped. The user can again type in the next response or click the mic button to record new input.
