### ISSUE TITLE
Able to use with Vue3?

### ISSUE THREAD

**Issue by wcheek** [aws-samples/aws-lex-web-ui#407]
All of the examples in the documentation are using Vue2. Is it possible to use the npm package with Vue3? I am immediately running into the issue of Vuetify only having support for Vue2.

**Comment by bobpskier** [comment]
I believe its going to be a heavy lift to shift to Vue3 from the current Vue2 implementation. Vuetify being one of the potential issues. Certainly will be needed sooner rather than later but I don't know of any efforts underway to make this conversion.
