### ISSUE TITLE
Aws Lex with Lambda integration

### ISSUE THREAD

**Issue by sathishkrish90** [aws-samples/aws-lex-web-ui#409]
Tried deploying Cloudformation master.yaml as CodeBuild mode. Deployment succeeded but Aws Lex with Lambda integration is not getting configured. 

Its creating 5 count of lambda functions for CognitoUserPoolDomainFn, CognitoUserPoolUpdatesFn, CognitoIDCleanStackNameFn, CodeBuildStarterLambda and CodeBuildDeployS3CleanupLambda.

So anyone can assist on this?

**Comment by bobpskier** [comment]
@sathishkrish90 LexWebUi does not configure or install Lambdas that would be called by your Lex bot for fulfillment. You would need to create, configure, publish versions, assign aliases for your Lex bot as part of your Lex pipeline or via the AWS Lex Console. LexWebUi allows you to target a Lex Bot (V2 or V1) that you have already created including any Lambdas that provide fulfillment functionality.
