### ISSUE TITLE
Response cards are not displayed on Web UI for Lex V2

### ISSUE THREAD

**Issue by bmanoj-aws** [aws-samples/aws-lex-web-ui#412]
Hi Team,

 Our Lex Bot running on v2 has a couple of response cards and is not displayed on Web UI., but works on lex console.

providing the code snippet we are using.

imageResponseCard = {
                         "title": "Do you want to place the order?",
                             "buttons": [
                                 {
                                     "text": "Yes",
                                     "value": "Yes"
                                 },
                                 {
                                     "text": "No",
                                     "value": "No"
                                 }
                     ]
                 }

def preconfirm(event,Descriptiondata,userid,expecteddate,orderquantity): 
 session_attributes['appContext'] =json.dumps({'responseCard': imageResponseCard})

    return {
           "sessionState": {
            # "sessionAttributes": session_attributes,
            #"sessionAttributes": event,
            "dialogAction": {
                "type": "ElicitSlot",
                "slotToElicit": "preconfirmdata"
            },
            "intent": {
                "name": event['sessionState']['intent']['name'],
                "slots": event['sessionState']['intent']['slots']
            }
        },
        "messages": [

                    {
                        "contentType": "ImageResponseCard",
                        "imageResponseCard": {
                        "title": "Do you want to place the order?",
                            "buttons": [
                                {
                                    "text": "Yes",
                                    "value": "Yes"
                                },
                                {
                                    "text": "No",
                                    "value": "No"
                                }
                    ]
                }
                    }
                    ]
        }

**Comment by bobpskier** [comment]
@bmakumar I don't see anything incorrect in the code you've posted. I can get that imageresponsecard payload to display in a test environment. By default the "title" will be hidden but the buttons will still show up. I would setup the response to be an array of messages with something like the following javascript. This provides the textual response in a separate message. If you ever want to use audio mode, its easier to proceed this way than trying to bundle everything in a single image response card. Image response cards by default are not displayed if in audio mode. The PlainText message would be converted into a voice response. 

```
let res2 = {
        "sessionState": sessionState,
        "messages": [
                    {
                        "contentType": "PlainText",
                        "content": "Do you want to place the order?",
                    },
                    {
                        "contentType": "ImageResponseCard",
                        "imageResponseCard": {
                        "title": "Confirmation",
                        "subtitle": "Options",
                        "buttons": [
                            {
                                "text": "Yes",
                                "value": "Yes"
                            },
                            {
                                "text": "No",
                                "value": "No"
                            }
                            ]
                        }
                    }
        ]
    }
  ```
  
It would display similar to:
![image](https://user-images.githubusercontent.com/11319101/179886869-82613f3f-e168-4457-8bd5-365bf66c127e.png)
  
  
Which version of lex-web-ui are you using? 

Can you capture the actual json response seen in the browser debugger?
