### ISSUE TITLE
Lex Web UI issue with CodeBuildDeploy in [ResourcePrefix] Parametter

### ISSUE THREAD

**Issue by HoangHa91** [aws-samples/aws-lex-web-ui#413]
Hi team
I try to deploy the Lex Web UI with AWS but get the below issue and make the update of the stack into status "UPDATE_FAILED"

[Parameters: [ResourcePrefix] must have values

with logical ID is CodeBuildDeploy

But in the master.yml file which was used to deploy, it doesn't have any Parameter name ResourcePrefix
and the CodeBuildDeploy nested stack status is UPDATE_COMPLETE that mean no issue in there. 
it only happens from lastweek, before that, everything seems no problem at all.

update 1:
I tried to delete the old stack and create the new one with same file, but it's unable to create the stack. 
anyone can help me with this ?

**Comment by bobpskier** [comment]
@HoangHa91 Are you using the single click deploy in your region from 
https://github.com/aws-samples/aws-lex-web-ui#getting-started 
?
If yes, which AWS region are you deploying in?

There is a parameter named BotNamePrefix that requires a value but none named ResourcePrefix that I'm aware of. 

If you are not using the single click deploy, can you provide template and parameters being used for your deploy?

**Comment by HoangHa91** [comment]
hi @bobpskier 
yes I use that with version  "Master Lex Web UI CloudFormation template (v0.19.4)" 
I deploy it in [ap-southeast-2]

**Comment by HoangHa91** [comment]
hi @bobpskier 
i think I found the isssue, I have use the v0.19.4 but in the newest version v0.19.5 , there is an update for ResourcePrefix . that causes my deployment fail
