### ISSUE TITLE
Send response card to chatbot UI with CustomEvent

### ISSUE THREAD

**Issue by wcheek** [aws-samples/aws-lex-web-ui#419]
I have the chatbot running through an iframe that I've loaded from the CloudFormation deployment. I'm exploring ways to pass data between the chatbot and the parent page. 

I want to ultimately send an image to the chatbot by triggering an event on the parent page.

I've found [from this API documentation](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#passing-event-messages-from-parent-to-chatbot-ui) that I can send text to the chatbot using the following code snippet, using the `postText` API method:
```js
 var event = new CustomEvent(
  "lexWebUiMessage",
  // chatbot ui has a handler for the toggleMinimizeUi event
  { detail: { message: { event: "postText", message: "test message" } } }
);
// this event is relayed to the iframe using postMessage
document.dispatchEvent(event);
```
You talk a bit about response cards [being supported natively with the `postText` API method](https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#response-cards), but I'm confused about what you mean. Is there another parameter I can pass into the event?

[Here](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-loader-api-functions), talking about the *loader API*, the `loader.api.postText` method has different parameters than the method I'm using above, but it looks like this one is capable of sending response cards. Are these different methods, or are they just documented differently?

Note that using the `loader` is not suitable for my use case, since after the ChatbotUI gets loaded, it's out of scope. If I can somehow access this object outside the initial loading script, then it may work for me.

**Comment by bobpskier** [comment]
@wcheek The best api to use is the one you refer to called the [loader API](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-loader-api-functions). There are several methods you can call on this api. postText() is one of them. You can also toggle the minimized/maximized state using toggleMinimizeUi(). You can also set session attributes. 

The main page should load the iframe via the loader using a <script> element at the top level. At this level you should be able to preserve the the loader reference created using the following.
```
var lexWebUiLoader = new ChatBotUiLoader.IframeLoader();
```
The documentation contains samples to that operate in this fashion. 

You could use the dispatchEvent mechanism as well to send a postText message. The syntax for this message would need to be determined but I expect this is also doable. 

When you call postText on the api above, this causes a postText (Lex v1 bots) or recognizeText(lex v2 bots) to be send to the Lex Bot. The lambda handler backing the Lex Bot can respond with an image response card which results in a response card being returned to the lex web ui which will be processed and displayed. Lex V1 and V2 have different response formats. Are you building a V1 or a V2 Lex bot?

However if the user sends audio by clicking on the mic, this results in a postContent (v1) or a recognizeUtterance (v2)  request being sent to the lex bot along with the recorded audio. If a lambda backing this response returns an image response card, it will be filtered out by the Lex service and not returned to the lex-web-ui by Lex. Hence image response cards using the response from a lambda will not work. As an alternative mechanism, lex-web-ui supports and detects a serialized image response card being returned in a special session attribute named appContext.altMessages.responseCard.

**Comment by bobpskier** [comment]
@wcheek To receive events on the main page from the iframe see the documentation [here](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-loader-event-based-api). Whenever the the state of the lex-web-ui is updated via a response from the Lex service, an even will be fired that the main (parent) page can process.

**Comment by wcheek** [comment]
@bobpskier Thanks as always for the good advice. 

You made me realize that I was thinking about the problem wrong - rather than sending an image to the chatbot, I should instead make the chatbot (lambda function) send the image to me. Maybe the issue should instead be called "Receive response card from chatbot UI after being prompted with CustomEvent."

It may be a more rudimentary solution than you recommended (I'm using a V2 bot), but I ended up using the `CustomEvent` as I explained above to send a message which includes the uploaded file name. The lambda function is then able to interpret the message and send back a link and an [ImageResponseCard](https://docs.aws.amazon.com/lexv2/latest/dg/API_ImageResponseCard.html) showing the uploaded image.

## My solution with AWS infrastructure
After the chatbot lambda function receives the message from `CustomEvent` dispatch:
1) Get the file name and type from the message using regex.
2) Create signed URL of the object on S3.
3) Use a URL shortener to be sure that the link is < 250 characters (limitation of `ImageResponseCard` `imageUrl` param). Annoying since S3 pre-signed links are massive.
4) Send a response back to the chatbot, something like:
```python
messages = (
    [
        {
            "contentType": "CustomPayload",
            "content": f"[{file_name}]({short_url})",
        },
        {
            "contentType": "ImageResponseCard",
            "imageResponseCard": {
                "title": "Uploaded file",
                "imageUrl": short_url,
            },
        },
    ]
    if file_type in ["jpg", "png"]
    else [
        {
            "contentType": "CustomPayload",
            "content": f"[{file_name}]({short_url})",
        }
    ]
)

response = {
    "sessionState": {
        "dialogAction": {
            "slotToElicit": slot_to_elicit,
            "type": "ElicitSlot",
        },
        "intent": current_intent,
    },
    "messages": messages,
```
