### ISSUE TITLE
CDK Deploy erroring out

### ISSUE THREAD

**Issue by kmaramr** [aws-samples/aws-lex-web-ui#420]
Hello,

We have a QnaBot deployment and trying to automate Lex Web UI deployment (master.yaml) using CDK (C#) I keep running into Template Url must be a supported URL. Not sure what i am doing wrong. (also, my first CDK deployment).

`
        internal LexWebUiStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
        {
            string path = Directory.GetCurrentDirectory();
            Bucket bucket = new Bucket(this, "lex-web-ui-cfm", new BucketProps
            {
                Versioned = true
            });

            Role bucketRole = new Role(this, "LexWebUICFMRole", new RoleProps
            {
                AssumedBy = new AnyPrincipal()
            });
            bucketRole.AddToPolicy(new PolicyStatement(new PolicyStatementProps
            {
                Actions = new[] { "s3:*" },
                Resources = new[] { bucket.BucketArn }
            }));

            var template = new cfnInc.CfnInclude(this, "Template", new cfnInc.CfnIncludeProps
            {
                TemplateFile = @$"{path}\src\LexWebUi\template\master-0.19.5.yaml",
                Parameters = new Dictionary<string, object>
                {
                    { "BootstrapBucket", bucket.BucketArn },
                    { "BootstrapPrefix", "/" },
                    { "BotName", "**********_qnabot_stack_BotDBNcG" },
                    { "BotAlias", "$LATEST" },
                    { "CognitoIdentityPoolId", "HIDDEN" },
                    { "CodeBuildName", "******-lex-web-ui-codebuild" },
                    { "WebAppParentOrigin", "localhost:3000" },
                    { "EnableCognitoLogin", false },
                    { "ReInitSessionAttributesOnRestart", true },
                    { "WebAppConfBotInitialText", "Please ask me a question" },
                    { "WebAppConfBotInitialSpeech", "Please ask me a question" },
                    { "WebAppConfToolbarTitle", "QnABot" },
                    { "WebAppConfHelp", "Help" },
                    { "WebAppConfNegativeFeedback", "Thumbs down" },
                    { "WebAppConfPositiveFeedback", "Thumbs up" },
                    { "CleanupBuckets", true },
                    { "EnableMarkdownSupport", true },
                    { "ShouldLoadIframeMinimized", true },
                    { "ShowResponseCardTitle", true }
                }
            });
        }`

**Error - CDK deploy**
`
| 3:30:43 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | Template/CodeBuildDeploy (CodeBuildDeploy) TemplateURL must be a supported URL.
`

**Comment by wcheek** [comment]
@kmaramr Although I don't have experience with `C# CDK` I suspect it may be a problem with the path you're supplying. Maybe try escaping the `\` or supplying the path with `/` instead of `\`? 

If that doesn't work, you can explore the problem further by using the `--verbose` tag when you call `cdk deploy`

**Comment by kmaramr** [comment]
Thanks @wcheek, this was { "BootstrapBucket", bucket.BucketArn }, it needed to be bucket.BucketName.
