### ISSUE TITLE
UI component for Multiple-valued slot.

### ISSUE THREAD

**Issue by SandeepPasula898** [aws-samples/aws-lex-web-ui#421]
Hi, do you have any provision of UI component for multiple-valued slot, something like checklist? if no, can we expect this feature in future. It would be really helpful if you add that feature in this project.

**Comment by bobpskier** [comment]
@SandeepPasula898 Presently a response card can be returned that provides a set of buttons the user can select from. This is supported in the response card implementation in the Lex api that a Lambda can augment. Adding a multi-selection list with a submit button would be an interesting feature to add. On submit the lex-web-ui could submit a recognizeText request prepending a start phrase and appending an "and" separated list of the values selected. The standard Lex api does not support a response from a Lambda function which would allow a list of values for this type of widget. However, a session variable containing a stringified json payload could be used instead. I think this feature could be considered as a way to support multiple-valued slots. I'll raise this with the AWS team and see if they would consider a pull request with this feature.
