### ISSUE TITLE
Amplify

### ISSUE THREAD

**Issue by gauravkumar-aws** [aws-samples/aws-lex-web-ui#422]
Hello Team,
can you please provide the steps how we can deploy this using amplify ?

Thanks,
Gaurav Kumar

**Comment by bobpskier** [comment]
lex-web-ui is built and deployed using cloud formation. An amplify option is not available. The cognito identity pool created by an amplify deployment could be reused by lex-web-ui. See [use existing identity pool](https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#adjusting-existing-identity-pools-to-be-used-with-the-lex-web-ui). The iframe based integration method of lex-web-ui could be reused in an amplify based web app by incorporating the snippet url in the app.

**Comment by gauravkumar-aws** [comment]
> 

we tried using the iframe code snippet but we keep getting the error : "ChatBotUiLoader not found"

**Comment by bobpskier** [comment]
This error is most likely due to a CORS error. The parent origin declared in the template parameter, WebAppParentOrigin, must much exactly the origin where the iframe will be deployed using the snipet. If you are just experimenting, then leave the WebAppParentOrigin empty and access the parent page using the newly deploy cloudformation domain /parent.html.

**Comment by gauravkumar-aws** [comment]
@bobpskier 
with some modification i got the project to run on amplify, but when trying to load the iframe i keep running into the below issue :

https://master.12345.amplifyapp.com/parent.html/index.html   --- 403
parent.html:61 chatbot UI failed to load Error: chatbot loading time out
    at e.onConfigEventTimeout (iframe-component-loader.js:524:23)

can you please help me that what i am doing wrong.

baseurl for me is "/"
"parentOrigin": "https://master.12345.amplifyapp.com",
"iframeOrigin": "https://master.12345.amplifyapp.com/parent.html",
"shouldLoadIframeMinimized": false,
"iframeSrcPath": "/index.html#/?lexWebUiEmbed=true"

**Comment by gauravkumar-aws** [comment]
i think i figured it out :)

**Comment by Toby-Akabogu** [comment]
> i think i figured it out :)

How did you figure it out? Running into a similar issue

**Comment by gauravkumar-aws** [comment]
@Toby-Akabogu 
the issue is with 
"parentOrigin": "https://master.12345.amplifyapp.com/",
"iframeOrigin": "https://master.12345.amplifyapp.com/parent.html",
correct is 
"parentOrigin": "https://master.12345.amplifyapp.com/",
"iframeOrigin": "https://master.12345.amplifyapp.com",

and you need to place index.html and parent.html in dist directory.

**Comment by gauravkumar-aws** [comment]
@Toby-Akabogu 
the issue is with 
"parentOrigin": "https://master.12345.amplifyapp.com/",
"iframeOrigin": "https://master.12345.amplifyapp.com/parent.html",
correct is 
"parentOrigin": "https://master.12345.amplifyapp.com/",
"iframeOrigin": "https://master.12345.amplifyapp.com",

and you need to place index.html and parent.html in dist directory.
