### ISSUE TITLE
Changing Page Title

### ISSUE THREAD

**Issue by srachir** [aws-samples/aws-lex-web-ui#423]
Hi Team, 

Is it possible to change the Page Title from default "Order Flowers Bot" to something else through environmental variables in code build or is there an easier way to change the Page Title during the deployment through CFN? 

Thank you!

**Comment by bobpskier** [comment]
@srachir The cloud formation template has a parameter named "WebAppConfToolbarTitle". The iframe toolbar title when using the iframe integration approach will be set to this value. Same with the toolbar title served up from single page approach in index.html. 

The pageTitle used in the generated index.html should be configurable by modifying lex-web-ui/src/config/index.js and/or lex-web-ui/src/config/config.prod.json for a prod build. The merge of this configuration data results in the generated index.html file. I don't know of anyway to override the merged value via an environment variable. It might be possible to inject a pageTitle via environment via changes to lex-web-ui/src/config/index.js.

**Comment by Anastasiyatik** [comment]
Hi guys, 
I have the same issue. Have you managed to fix it.
Thanks in advance

**Comment by soham-dasgupta** [comment]
You may need to update the config.json file in the S3 bucket -- and adding a new entry for pageTitle to the ui section of the config. such as: example: "ui": { "pageTitle": "INSERT YOUR PAGE TITLE HERE", },

1. Go to Cloudformation -- and look for your lex-web-ui deployment
2. Go to the Outputs section and find the S3 bucket name in the WebAppBucket key
3. Go to S3 and navigate to that S3 bucket
4. Download the lex-web-ui-loader-config.json file
5. Add the pageTitle setting such as the example above -- and Save
6. Don't change anything else in this file
7. Upload the file to the S3 bucket
