### ISSUE TITLE
pass multiple LocaleID for lex web UI

### ISSUE THREAD

**Issue by bmanoj-aws** [aws-samples/aws-lex-web-ui#428]
we have a single bot that hosts multiple languages , en_US, en_IN and both are in default version. can you guide us how we can host those both on the lex web UI.
we have updated the below parameter in the config.json file as well as updating during the cft deployment but neither of them worked and getting the below error.

 "v2BotLocaleId": ["en_US" , "en_IN"],

Error:

<html>
<body>

[Container] 2022/08/23 13:33:38 Running command make config
--
42 | [INFO] Running config script: [build/update-lex-web-ui-config.js]
43 | node build/update-lex-web-ui-config.js
44 | /codebuild/output/src942847909/src/config/utils/merge-config.js:27
45 | if (key in srcConfig ) {
46 | ^
47 |  
48 | TypeError: Cannot use 'in' operator to search for '0' in en_US,en_IN
49 | at /codebuild/output/src942847909/src/config/utils/merge-config.js:27:15
50 | at Array.map (<anonymous>)
51 | at mergeConfig (/codebuild/output/src942847909/src/config/utils/merge-config.js:22:6)
52 | at /codebuild/output/src942847909/src/config/utils/merge-config.js:37:21
53 | at Array.map (<anonymous>)
54 | at mergeConfig (/codebuild/output/src942847909/src/config/utils/merge-config.js:22:6)
55 | at /codebuild/output/src942847909/src/config/utils/merge-config.js:37:21
56 | at Array.map (<anonymous>)
57 | at mergeConfig (/codebuild/output/src942847909/src/config/utils/merge-config.js:22:6)
58 | at Object.<anonymous> (/codebuild/output/src942847909/src/config/dist.env.js:23:20)
59 | make: *** [config] Error 1
60 |  
61 | [Container] 2022/08/23 13:33:38 Command did not exit successfully make config exit status 2
62 | [Container] 2022/08/23 13:33:38 Phase complete: PRE_BUILD State: FAILED
63 | [Container] 2022/08/23 13:33:38 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: make config. Reason: exit status 2

</body>
</html>

**Comment by bobpskier** [comment]
@bmakumar Ultimately the config value should be a comma separated string such as: 
```
"v2BotLocaleId": "en_US, de_DE",
```
The text above in your post shows it as an array of strings. The parameter in cloudformation should also just be a comma separated string.
