### ISSUE TITLE
How to pass buttons in initial utterence from AWS Lex web UI

### ISSUE THREAD

**Issue by PranaliYangandul912** [aws-samples/aws-lex-web-ui#431]
We can only pass initial utterence as a text after iframe gets loaded ,
is there a way to pass button as a initial utterence
Thanks

**Comment by bobpskier** [comment]
@PranaliYangandul912 I'm not quite sure I understand your question. The lex-web-ui will send a recognizeText or a recognizeUtterance request to the lex bot via lex v2 api. The initial utterance configuration is used to send an initial recognizeText request. 

If you want to display one or more buttons to the user in the lex-web-ui on startup, the response to the initial utterance via recognizeText could include a ResponseCard that includes buttons to display. 

Can you clarify the user interaction you are looking for?

**Comment by PranaliYangandul912** [comment]
in config file we have this parameter initialText 
after iframe loads this initialText getting pushed , so can we push buttons along this initialText from UI initially when iframe loads?
we dont want this buttons to be pushed from lambda or lex
we want to push this buttons along with initial text from UI
With the help of buttons , user can get clarity for what this chatbot is built
