### ISSUE TITLE
QNA and Settings Import Automation instead of using Content Designer

### ISSUE THREAD

**Issue by joeyeng** [aws-samples/aws-lex-web-ui#437]
Is it possible to automate import of the qna and settings json files, or is that purely a manual process you have to do using the content designer?

**Comment by rstrahan** [comment]
Hi Joey,
FAQs, yes.. see https://github.com/aws-solutions/qnabot-on-aws/blob/main/docs/qnabot_cli.md
Settings, yes (ish).. we don't have a QnABot CLI for settings but all the settings are stored in Systems Manager Parameter Store.. Default settings values in one parameter, and modified/ custom settings values in another. The default and custom settings Parameter names are shown in the QnABot stack outputs in Cloud formation.
You can use the AWS get-parameters / put-patameter CLI (https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters.html) or SDK to read and update the Custom Parameter to add key/value pairs to override the default settings.
Hope this helps.
Cheers
Bob


Sent from Workspace ONE Boxer

On Oct 14, 2022 1:37 PM, Joey Eng ***@***.***> wrote:

Is it possible to automate import of the faq and settings json files, or is that purely a manual process you have to do using the content designer?
