### ISSUE TITLE
get access to audio streams

### ISSUE THREAD

**Issue by demsey2** [aws-samples/aws-lex-web-ui#44]
is there any way to get access to audio streams? I would like to disable microphone when I leave my bot page. I couldn't find anything that can let me access all existing media tracks. 

At the moment they are stored in the recorder instance, however, there is no way to access it. 

I modified the code and added another action 
```
// lex-web-ui.js: line 5764
getRecorder: function getRecorder() {
  return recorder;
},
```
with that change, I can access the recorder instance and everything on it

**Comment by JohnCalhoun** [comment]
hey demsey2,
can you submit a pull request to add this

**Comment by demsey2** [comment]
PR https://github.com/aws-samples/aws-lex-web-ui/pull/50
