### ISSUE TITLE
How to add more than 5 buttons in aws lex web ui

### ISSUE THREAD

**Issue by vinayburam** [aws-samples/aws-lex-web-ui#448]
Currently using imageresponse card i am able to display 5 buttons but not more than 5

**Comment by vinayburam** [comment]
@bobpskier Can you please help me in this

**Comment by vinayburam** [comment]
currently i am using below code.
def image_response_card(buttons_for_name):
    """
    This function returns format of imageResponseCard message"""
    return {
        "contentType": "ImageResponseCard",
        "imageResponseCard": {
        "title": "Click a button",
        "buttons": get_buttons(buttons_for_name) if buttons_for_name else None
        }
    }

//getbuttons is method to get array of string

**Comment by bobpskier** [comment]
@vinayburam The AWS Lex service only supports a maximum of five buttons. No getting around this from a standard Lex lambda response during fulfillment.

However, LexWebUi works around this limitation by allowing the response to contain a session attribute named "appContext" which is used by LexWebUi to render markdown, html, ssml, and in your case a response card that contains more than 5 buttons. For a discussion on this session attribute see https://github.com/aws-samples/aws-lex-web-ui/blob/a0de69ab1e01be48316579f9276eb5a9839acb8a/lex-web-ui/README.md#markdown-and-html-support. 

appContext must be a string when set as a session attribute. It contains a serialized json object which holds altMessages and responseCard properties. 

altMessages is a property that can be populated with markdown, html, or ssml. 

responseCard is the property that holds the Lex V1 responseCard format used to render in LexWebUi. 

The following example "appContext" property (string) returns a response card that has six buttons and an empty altMessages indicating there is no markdown, html, or ssml to render. 

```
"{\"altMessages\":{},\"responseCard\":{\"version\":\"1\",\"contentType\":\"application/vnd.amazonaws.card.generic\",\"genericAttachments\":[{\"title\":\"options\",\"buttons\":[{\"text\":\"One\",\"value\":\"1\"},{\"text\":\"Two\",\"value\":\"2\"},{\"text\":\"Three\",\"value\":\"3\"},{\"text\":\"Four\",\"value\":\"4\"},{\"text\":\"Five\",\"value\":\"5\"},{\"text\":\"Six\",\"value\":\"6\"}]}]}}"
```

If you set a string as the "appContext" session attribute containing a similar payload to above, LexWebUi will render a response card with more than 5 buttons. This is exactly what the AWS QnABot Solution does to render more than 5 buttons in LexWebUi.
