### ISSUE TITLE
chatbot timed out  error

### ISSUE THREAD

**Issue by sathvik2612** [aws-samples/aws-lex-web-ui#450]
In cloudfront the same website https://d65wdfp6ze5xy.cloudfront.net/  is working

but when i exposed it with route 53 it's not working and showing error timed out. 

The exposed website pwd.life

**Comment by sathvik2612** [comment]
The chatbot is working good in https://d65wdfp6ze5xy.cloudfront.net/ 

but not in pwd.life

**Comment by sathvik2612** [comment]
Could anyone please guide me regarding this

**Comment by sathvik2612** [comment]
Error: chatbot loading time out
    at e.onConfigEventTimeout (lex-web-ui-loader.min.js:157:13999)

**Comment by vinaykumar-buram** [comment]
change the parent origin from lexwebuiloaderconfig.json. now it must be your cloundfront url. change it with the url where your bot is getting deployed.

**Comment by bobpskier** [comment]
@sathvik2612 Update the CloudFormation stack with the new parent origin setting the template parameter WebAppParentOrigin to https://pwd.life.

**Comment by sathvik2612** [comment]
Thanks a lot I have already cleared it
