### ISSUE TITLE
How to hide initial utterance configured through WebAppConfBotInitialUtterance

### ISSUE THREAD

**Issue by vinaykumar-buram** [aws-samples/aws-lex-web-ui#451]
I have configured the bot using WebAppConfBotInitialUtterance has initial utterance, It is calling my initial intent when bot gets loaded. but it looks user has typed that utterance from the front end

**Comment by bobpskier** [comment]
@vinaykumar-buram Set HideButtonMessageBubble to be true in the CloudFormation stack template parameter. This parameter will also hide the initial utterance when loaded. You can also modify this setting the the lex-web-ui-loader-config.json file in your webapp bucket but note it will be updated on the next stack update using CloudFormation.

**Comment by vinaykumar-buram** [comment]
will it hide the the other buttons values as well

**Comment by bobpskier** [comment]
@vinaykumar-buram It hides those values sent during button clicks as well as the initial utterance.

**Comment by vinaykumar-buram** [comment]
@bobpskier But i want to hide only initial utterance.. and other button clicks should display as it is.. It looks bit wierd when initial utterance get diplayed even though it is not typed by user.
Is it possible to do it in that way?

**Comment by vinaykumar-buram** [comment]
is there any workaround to hide only initial utterance

**Comment by bobpskier** [comment]
You might try hiding the initial text message using css in the custom-chatbot-style.css. The initial utterance in this case would be the first div with the message-human class. I've not had a chance to experiment with this but in theory it should turn off the first element with this class. 

.message-human:first-of-type {
    display:none;
}

**Comment by vinaykumar-buram** [comment]
Hi Bob ,
I have tried with above aproach. When i added the above code in custom-chatbot-style.css from "dist" folder it is working.
but when i am adding the same code in file custom-chatbot-style.css from s3 bucket it is not working.
Can you please let me know where i am  doing wrong

**Comment by vinaykumar-buram** [comment]
Hi Bob, Its working . In my case it was second div. Thanks for your help
