### ISSUE TITLE
Welcome intent is getting qualified with 'ok' utterance but it is not trained with that keyword

### ISSUE THREAD

**Issue by vinaykumar-buram** [aws-samples/aws-lex-web-ui#454]
Hi, My bot is not trained to qualify the Welcome intent with keyword 'ok'. but still it is calling welcome intent when user type 'ok'
how to restrict the intent to get qualify from the random inputs.

**Comment by bobpskier** [comment]
@vinaykumar-buram I think you'll be better off directing your questions to the lex service via a support request or some other channel to understand the best practices to write a Lex bot. The aws-lex-web-ui just makes lex runtime api calls based on the user interaction via a web page. It can send an initial utterance when the web page is first displayed but I don't think that is what you are asking about. If the user types and submits "Ok" in the lex-web-ui, the lex-web-ui calls the Lex runtime api RecognizeText and passes "Ok" as in the input to this request. The Lex Bot via its intents will handle this request. If it is not trained to understand "Ok" then some other configured processing is taking place which is using the Welcome intent. You'll need to investigate why the Lex bot is behaving the way it is given the input "Ok".

**Comment by vinaykumar-buram** [comment]
thanks @bobpskier we raise support request
