### ISSUE TITLE
I am trying to find a way to control when to use the thumbs up/down in the UI. Right now, it seems to be showing up on all Lex responses

### ISSUE THREAD

**Issue by vinaykumar-buram** [aws-samples/aws-lex-web-ui#455]

**Comment by bobpskier** [comment]
@vinaykumar-buram In the present implementation as you've probably seen, display of Thumbs up/down is enabled or disabled globally based on the ui configuration properties positiveFeedbackIntent and negativeFeedbackIntent. When these are set, a Thumbs Up or Thumbs Down icon is displayed next to the last response from Lex. There is no mechanism to control these on a response by response basis. It might be possible to build an implementation that lets the response include well defined session attributes that govern this behavior.

**Comment by vinaykumar-buram** [comment]
Thank you..
