### ISSUE TITLE
How to remove three dots from the user input.

### ISSUE THREAD

**Issue by vinaykumar-buram** [aws-samples/aws-lex-web-ui#458]
Hi Team,
I can see there are three dots when user selects button or type anything. when we click on that it gives option to reload.
How to remove this

**Comment by bobpskier** [comment]
@vinaykumar-buram Update either lex-web-ui-config.json and set the configuration value ui.messageMenu to false or set MessageMenu to false via the CloudFormation template and update the stack. Be sure to manually invalidate your cloudfront distribution cache and refresh your browser if you make the change to the file manually.
