### ISSUE TITLE
Chatbot is updated only on iOS and OS (chrome) but doesn't work on window Chrome (but work on edge)?

### ISSUE THREAD

**Issue by Glassatlas** [aws-samples/aws-lex-web-ui#460]
Hi there,

So my chatbot integration to my testing site works for all devices. However, after I updated the config file (parentURL) from my previous site (test) to my current site (the real main website, I did this on a mac), it worked only on my mac and iPhone. My friend who opened the site using a window laptop, the chatbot shows a timeout error on Console. However, they could still go to my previous site and the chatbot would still be working there as if the config file was never updated. 

On OS and iOS, chatbot is no longer loaded at the previous site.
Do let me know what did I do wrong?

The site in question is:
previous: https://fjg.accesspoint.media/
current: https://www.fjg.co.uk/

**Comment by bobpskier** [comment]
@Glassatlas The "current" site looks to be working correctly for me. Did you deploy the updates via cloudformation template or via manual change to the lex-web-ui-config-loader.json file. If manual, you need to invalidate the cloudfront cache fronting the site or it will take some time to clear automatically. The template will perform this invalidation on an update. Also, the cache in your browser needs to be cleared such that the new config will be downloaded. Sometimes one or both of these will cause an issue until the caches are cleared.

**Comment by Glassatlas** [comment]
Hi bobpskier,
i forgot to close to issue last night but I also figured from previous similar issue that this seems to be the cache issue. Once I reuploaded the file after clearing the cache, it's now fully working. Thank you!

> @Glassatlas The "current" site looks to be working correctly for me. Did you deploy the updates via cloudformation template or via manual change to the lex-web-ui-config-loader.json file. If manual, you need to invalidate the cloudfront cache fronting the site or it will take some time to clear automatically. The template will perform this invalidation on an update. Also, the cache in your browser needs to be cleared such that the new config will be downloaded. Sometimes one or both of these will cause an issue until the caches are cleared.
