### ISSUE TITLE
Can we edit lex-web-ui-loader.min.js to add below code

### ISSUE THREAD

**Issue by vinaykumar-buram** [aws-samples/aws-lex-web-ui#463]
//Code
t.dispatch("lexPostText","Hi BUD").then((function(e){var n=JSON.parse(e.message)

I wanted to to add "Hi Bud" message as initial utterance

**Comment by bobpskier** [comment]
@vinaykumar-buram There are a couple of ways to do this already. 1) You can set the template parameter WebAppConfBotInitialUtterance and when the page is first loaded, this text will be sent to the Lex bot. 2) You can use the loader's postText() api to send a PostText after page load or at any point using javascript on the parent page.
