### ISSUE TITLE
Can we use Help Content in UI without a user click on help button?

### ISSUE THREAD

**Issue by SandeepPasula898** [aws-samples/aws-lex-web-ui#472]
Hi, I have recently came across helpContent Parameter in Config.json. This is very useful. But, it only works when we have "helpIntent" parameter enabled in same config file. Is it possible to render helpContent after initialText without clicking on help icon?

**Comment by bobpskier** [comment]
@SandeepPasula898 There is no each mechanism to render this content without clicking on the help button. The help v-btn in ToolbarContainer.vue calls a handler called sendHelp().  sendHelp() then either uses the vuex store to dispatch a 'pushMessage' to display the defined helpContent or dispatches a postTextMessage to send the help request on to the bot. The only way I could think of making this be available outside of the help button is via addition of code. One could create a new API method in initParentToIframeApi in iframe-component-loader.js that sends a new message to the iframe as the iframe to display the content. The handling of this new message would dispatch the pushMessage using the config defined in the json. Then the parent window holding the iframe can call this api whenever it needs to display the content such as during loading of the iframe. 

An alternative approach via code change would be to allow the initialText configuration to also support markdown such that similar content could be rendered in place of the simple text and automatically rendered at startup. 

If you'd like a proposal on building out a custom version to accomplish this, please let me know.

**Comment by SandeepPasula898** [comment]
Thanks @bobpskier Above suggested approaches looks convincing to me. Though I am not a UI person, I would like to propose on building this version in this project. Adding this can help in rendering custom text or buttons below initialText.
