### ISSUE TITLE
Pass auth session to iframe

### ISSUE THREAD

**Issue by jonkolar** [aws-samples/aws-lex-web-ui#491]
Hey, I was wondering if there is a way to load the deployed lex-web-ui as an iframe and send an already authenticated users session attributes to the iframe so they can use the bot as an authenticated user.

My current flow has the user signing in through a vue application using amplify auth, then I load the deployed lex-web-ui in an iframe. When I load the lex-web-ui in this iframe I would like it to recognize the user as authenticated.

**Comment by jonkolar** [comment]
UPDATE: I am still having issues trying to pass my authenticated user to the Lex Web UI iFrame. I have tried passing session attributes and have used the getCredentials event that the iframe fires and returned the amplify aws credentials from it. I have still had no luck trying to get the iframe to recognize the authenticated user.

**Comment by jonkolar** [comment]
@bobpskier Hey Bob, I appreciate the response. The goal is to use the authentication credentials from amplify and pass them to the iframe to be used for the backend lambda. The expected behavior is to only allow authenticated users to use the bot and for the bot to have access to the user's information for any use cases it might need them for.

I have tried passing the jwtToken created after a user is logged in and authenticated with amplify auth as a session attribute when loading in the iframe (as you mentioned in #164. From the documentation it appears like the getCredentials event is meant for this type of situation but I'm having issues getting the iframe to accept the cognito credentials set by amplify. the iframe will fire the getcredentials event but when credentials are sent back the bot either does not load on the page, or simply doesn't use the credentials.

Ill look into if the current identity pool im using has the correct features. That is one thing I haven't attempted yet.

**Comment by bobpskier** [comment]
@jonkolar I believe its best to align the cognito resources used by the ui with the existing identity pool. getCredentials does provide the opportunity to set the credential. Have you changed any of the lexwebui config json? enableLogin and forceLogin should probably be set to false as you don't want lexwebui showing a login menu item nor force a login through its defined identity pool. Does the browser console indicate any errors during page load when it fails to load? The token should also be set in the browsers local storage after getCredentials completes. You can examine this in the browser to validate that it is getting set.
