### ISSUE TITLE
Can we send a tabular format to lex so that we can get the details from the user such as Payment info

### ISSUE THREAD

**Issue by Rahulsingh0007** [aws-samples/aws-lex-web-ui#497]
Hi Team, 

By any chance can anyone help me to get the details about how can we send the tabular format from lambda to lex using amazon connect UI, 
Need to capture User info , please find the attachment below 

Kindly repsond
<img width="413" alt="Form Input" src="https://user-images.githubusercontent.com/48233043/228738127-18eebfd8-a11c-4669-8302-24fbb7478121.PNG">

**Comment by atjohns** [comment]
Hey,

Sorry for the delayed response, are you trying to send HTML data or is this Markdown? Both can be sent to the UI from Lex - please look at the [section of the ReadMe ](https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#markdown-and-html-support) for information on how to support it in your Lambda:

**Comment by Rahulsingh0007** [comment]
Hi Aws-Samples/Aws-Lex-Web-Ui,

Can we connect ones just to discuss more of it

Regards,
Rahul kumar

**Comment by atjohns** [comment]
Hello, yes I am happy to discuss I was just cleaning up the issues log and had not heard back from you
