### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by Eruputh-Nikhitha** [aws-samples/aws-lex-web-ui#501]
Hi, 
    I suspected this occurring from the AWS-LEX-UI, and I don't know how to fix the error "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node".

Thanks in advance,
Nikhitha

**Comment by atjohns** [comment]
Hi, can you provide any more details on where this error is occurring in the JavaScript or send a screenshot of what you see in the console?
