### ISSUE TITLE
Facing issue related number of responses diplayed by web ui

### ISSUE THREAD

**Issue by yainoit** [aws-samples/aws-lex-web-ui#510]
From the backend I am sending three messages in response but in the first intent which is automatically getting invoked I can see only 2 messages . but when i call the first intent explicitly I can see all those three messages. I am not able to debug the web ui since i am new to it. Can you please help me to figure it out

**Comment by yainoit** [comment]
I am using LEX V2. In the network tab i can see the all the response message but however it is not appearing at ui.

 if intent_name == 'welcome':
        print("welcome intent")
        message1 = plain_text(''What can I help you with today? --message1")
        message1 = plain_text('''What can I help you with today?message2" )
       message1 = plain_text('''What can I help you with today?-message3 )
       message1 = plain_text('''What can I help you with today?-message4" )
       
        #return elicit_slot(session_attributes, slots= None,
                        #slot_to_elicit="topic", intent_name = "TopicSelectionIntent", message=[message1])
        return close(intent_request, session_attributes,"Fulfilled", [message1,message2,message3,message4])

First time I am calling this intent implicitly without user input and that i am not able to see all 4 messages but in the n/w tab i can see all the four messages. But when I am calling this intent explicitly by typing "Hi" then I can see all the four messages.

**Comment by bobpskier** [comment]
@yainoit Are you having LexWebUi send in an initial utterance to start the conversation? This would result in a POST request to RecognizeText. Can you copy the request payload (json) from the network tab for this POST request to RecognizeText and the response (json) from the network tab and paste in this thread? If you are not sending in an initial utterance, no request/response will be made until the user enters and sends text. If you can share the URL to the lexwebui we can look at the behavior as well. The response payload will look similar to that defined at https://docs.aws.amazon.com/lexv2/latest/APIReference/API_runtime_RecognizeText.html.
