### ISSUE TITLE
Updating the CloudFormation Stack with new parentOrigin does not update config file in S3

### ISSUE THREAD

**Issue by spturner** [aws-samples/aws-lex-web-ui#52]
When you are using iframes and set the parentOrigin during the initial CF stack creation, if you later go back to change the parentOrigin value on the CF stack, the configuration file in the S3 bucket doesn't get updated and you get a CORS issue as show below. To correct this, requires a manual update to the config file in S3. 

> [Error] Origin <..removed...> is not allowed by Access-Control-Allow-Origin.
> 
> [Error] Failed to load resource: Origin  <..removed...>  is not allowed by Access-Control-Allow-Origin. (lex-web-ui-loader-config.json, line 0)
> 
> [Error] XMLHttpRequest cannot load https://<...removed...>/lex-web-ui-loader-config.json due to access control checks.

**Comment by kirstenEhlers** [comment]
Modifying the JSON file directly by downloading and uploading new version will work

**Comment by kirstenEhlers** [comment]
Also, set public read access

**Comment by rexosariemen** [comment]
@kirstenEhlers How would set public read access? I am getting cors when I update the parentOrigin

**Comment by rstrahan** [comment]
Can you try checking/correcting the CORS policy on the webappbucket S3 bucket - Permission tab, scroll to bottom. If ParentOrigin was set, a CORS policy should exist granting permission to that origin. Check that it exists, and identified the correct origin.
