### ISSUE TITLE
HTML Head Title

### ISSUE THREAD

**Issue by klotniaa** [aws-samples/aws-lex-web-ui#521]
Hi all, I am using the default cloudformation deployment with a custom Lex V2 bot. I have followed the suggestion of uploading a new version of the loader config file in order to resolve the issue of "Order flowers bot" not being changed as the HTML title that is shown in the web page tab.However this is not working for me. I have also changed every instance where Order flowers bot occurs in the entire codebase for the website and am still having this issue. I thought it might have been an issue with Cloudfront using the cached version of the website but I invalidated the cache and am still having the issue. Is there a recommendation for resolving this? I am hoping to use this to showcase a generative AI demo next Friday and I know I could change it temporarily for the demo via webpage inspection, would love to get to the root of the problem however. Thank you!

**Comment by bobpskier** [comment]
@klotniaa All it takes is to add  the "pageTitle": "your page title" within the ui block of the lex-web-ui-loader-config.json. I use this mechanism all the time. Next invalidate your cloudfront cache as you've indicated. Finally, clear your browser's cache or run a new incognito / private window and reload the page.  If you are running using the iframe embedding approach, the "toolbarTitle" can be adjusted in the same fashion. 

Can you post the url you are using and I can look at your config file?

**Comment by klotniaa** [comment]
Thank you very much for getting back to me. Worked like a charm. I didn't find this type of guidance in the documentation. Are there any developer docs/readmes that go into parameters like this that arent necessarily included in the readmes in the sample repo?

**Comment by bobpskier** [comment]
Most of the time the lexwebui is deployed as an iframe component on a page which is why the pageTitle is not well documented. You can see the all the attributes which can be overridden at [index.js](https://github.com/aws-samples/aws-lex-web-ui/blob/16e69105f358198335293b244cb6d6feca8dcbd7/lex-web-ui/src/config/index.js).

**Comment by klotniaa** [comment]
Got it, thank you!
