### ISSUE TITLE
Chat History  

### ISSUE THREAD

**Issue by Vamshijannu** [aws-samples/aws-lex-web-ui#530]
Hi, I have successfully Integrated My AWS Lex Chat Bot with my Website using AWS-lex-web-ui as an iframe. Can I clear the chat history Upon clicking minimize button? Currently in my config file save History is set to "false"

**Comment by bobpskier** [comment]
@Vamshijannu There is no mechanism implemented to clear history when clicking the minimize button. Similar functionality is available when save history is enabled via the toolbar to manually clear history. Code modifications could be made to leverage the manual clear history mechanism and invoke on minimize.

**Comment by israelias** [comment]
@Vamshijannu You can model the modification/addition after the `request*` methods in `ToolbarContainer.vue` where a dispatch on*Event might look something like

```js
   requestResetHistory() {
      this.$store.dispatch('resetHistory');
    },
```

 for a reset `action` that might look something like

```js
  resetHistory(context) {
    context.commit('clearMessages');
    context.commit('clearUtteranceStack');
    context.dispatch('sendInitialUtterance');
    context.commit('pushMessage', {
      type: 'bot',
      text: context.state.config.lex.initialText,
      alts: {
        markdown: context.state.config.lex.initialText,
      },
    });
  },
```
