### ISSUE TITLE
Failed to load resource S3 bucket error

### ISSUE THREAD

**Issue by monilamb** [aws-samples/aws-lex-web-ui#533]
I launched the stack for the Lex Web UI and I went to open the index.html file and i get the following errors: 
![image](https://github.com/aws-samples/aws-lex-web-ui/assets/22434326/967686e5-12c2-42b6-b31e-de51335fa9dd)
I have not made any changes to anything.

Here is part of the JSON file config where u can see the parent origin is the cloudfront:
![image](https://github.com/aws-samples/aws-lex-web-ui/assets/22434326/5563806d-e1eb-475b-af2f-4d31393c873d)

When I try to embed it on an html and try it on my local machine i get this:
![image](https://github.com/aws-samples/aws-lex-web-ui/assets/22434326/056a4940-e3c1-4e02-9b92-f4d9858919c3)

Idk how to proceed.

**Comment by atjohns** [comment]
Did you deploy from the current master branch and what region did you deploy to? Did you change anything in regards to CloudFront settings?

**Comment by monilamb** [comment]
> Did you deploy from the current master branch and what region did you deploy to? Did you change anything in regards to CloudFront settings?

yes, i did. I did not change anything other than my own bot info. I am able to see the bot in the ParentPageURL but not on parent.html on the s3 bucket.

**Comment by monilamb** [comment]
oh, and i did the northern virginia region

**Comment by bobpskier** [comment]
@monilamb In this config, when you try and load it from the s3 bucket via url its been configured to deny this. The only valid parent origin is that of the cloudfront url. CORS is configured to require use from the cloudfront parent origin in this configuration.

**Comment by monilamb** [comment]
> @monilamb In this config, when you try and load it from the s3 bucket via url its been configured to deny this. The only valid parent origin is that of the cloudfront url. CORS is configured to require use from the cloudfront parent origin in this configuration.

i see, how should i be able to test the updated css? If i add the bucket url to the webapporigin its still giving me a CORS error. is there a way i could test in on an html page hosted on my local machine?

**Comment by monilamb** [comment]
i was able to run a quick vue project to host on my local machine thanks to steps in another thread. thanks!
