### ISSUE TITLE
Auto pop up the chat window

### ISSUE THREAD

**Issue by vinayburam** [aws-samples/aws-lex-web-ui#539]
Hi team I am trying to find out the solution which should automatically open the chat window without clicking on chat icon.
Could you please help me

**Comment by vinayburam** [comment]
shouldLoadIframeMinimized i have set it to false but still not getting the desired result

**Comment by atjohns** [comment]
If you are just looking to have the window open on initial page load then 'ShouldLoadIframeMinimized' being false on the Cloudformation deployment should do the trick.

If its not working, please validate that your json configuration file is being updated properly on deployment. The file is called lex-web-ui-loader-config.json and the "iframe" section should have this...

```
  "iframe": {
    "iframeOrigin": "https://xxxx.cloudfront.net",
    "shouldLoadIframeMinimized": false,
  }
```

If you are attempting to have the iframe un-minimized based on other activity in your site, you can leverage the parent to iframe APIs discussed here: https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-loader-api-functions

**Comment by vinayburam** [comment]
<img width="389" alt="image" src="https://github.com/aws-samples/aws-lex-web-ui/assets/39019897/b0934697-bd21-49c7-bdd9-4f41d281d58d">
If we reload the page then it is maintaining the state of chatbot. If it is in minimized mode and we reload the page the chatbot icon will appear in minimized mode and and same maximize as well

**Comment by israelias** [comment]
@vinayburam Sounds like expected functionality when `ui.saveHistory: true`.  Worth checking.
Also worth sifting through all config defaults for `shouldLoadIframeMinimized` from Vue to Loader. There could be a hanging toggle that keeps setting a falsy truth in Vuex store
