### ISSUE TITLE
I can see the resopnse in network tab when inspect the element. But on chat window it shows only some line

### ISSUE THREAD

**Issue by vinayburam** [aws-samples/aws-lex-web-ui#540]
I can see the resopnse in network tab when inspect the element. But on chat window it shows only some line
When i test the bot from console getting right response.

<img width="485" alt="bot error scren shot" src="https://github.com/aws-samples/aws-lex-web-ui/assets/39019897/586ce3c2-a80a-4c7a-a7fb-658e453a6c77">

BELOW RESPONSE FROM THE NETWORK TAB
{
    "interpretations": [
        {
            "intent": {
                "confirmationState": "None",
                "name": "LegalKendra",
                "slots": {},
                "state": "ReadyForFulfillment"
            }
        },
        {
            "intent": {
                "name": "WelcomeIntent",
                "slots": {
                    "CDA": null
                }
            },
            "nluConfidence": {
                "score": 0.76
            }
        }
    ],
    "requestAttributes": {
        "x-amz-lex:kendra-search-response-question_answer-answer-1": ",
        "x-amz-lex:kendra-search-response-question_answer-answer-2": "",
        "x-amz-lex:kendra-search-response-question_answer-question-1": "Drafting Stage",
        "x-amz-lex:kendra-search-response-question_answer-question-2": "Executed Stage"
    },
    "sessionId": "us-east-1:",
    "sessionState": {
        "dialogAction": {
            "type": "Close"
        },
        "intent": {
            "confirmationState": "None",
            "name": "LegalKendra",
            "slots": {},
            "state": "ReadyForFulfillment"
        },
        "originatingRequestId": "",
        "sessionAttributes": {
            "Dept": "CDA",
            "bot_name": "",
            "intent_name": "SubtopicIntent",
            "request_time": "2023-08-28 14:21:04",
            "retrycount": "1",
            "subtopic": "explore by stage",
       
        }
    }
}

**Comment by atjohns** [comment]
I don't see any messages in your response which would be why nothing is showing up in the UI.
