### ISSUE TITLE
GDPR Compliance?

### ISSUE THREAD

**Issue by AutoMationMaestro** [aws-samples/aws-lex-web-ui#56]
Hey,
I am wondering if there is something that I need to implement to make this sample GDPR compliant?

I am not saving something in AWS Lex by myself.
My bot basically answers Questions and detects some Slots that I use to perform some actions on the parent page.

Does anybody have an Idea?
Thank you!

**Comment by JohnCalhoun** [comment]
hello germanAdrian,
I do not know GDPR rules enough to know if lex-web-ui is compliant or what you would need to do. AWS can/does support GDPR works loads, here is more information:
https://aws.amazon.com/compliance/gdpr-center/

if you do find there needs to be changes to lex-web-ui to support GDPR we can work on adding that.

**Comment by germanAdrian** [comment]
Hello JohnCalhoun,
So do I.
I will try to get some more information about GDPR and comment my findings.
