### ISSUE TITLE
Thumbs up and Thumbs down button disappeared after change Lex response to Lambda hook

### ISSUE THREAD

**Issue by JohnnyPeng123** [aws-samples/aws-lex-web-ui#564]
For some reason the thumbs up and down button in the UI disappeared when I use lambda hook in Lex bot to response to query.

Any help would be appreciated, thanks!

**Comment by atjohns** [comment]
Can you share what your response body looks like coming back to the web UI? It should be available in the network tab. I cannot think of what would cause this behavior.

**Comment by JohnnyPeng123** [comment]
> Can you share what your response body looks like coming back to the web UI? It should be available in the network tab. I cannot think of what would cause this behavior.

It currently looks like in the UI this with the following payload from the lambda hook:

{
            "sessionState": {
                "dialogAction": {
                    "type": "ElicitIntent"
                },
            },
            "messages": [
                {
                    "contentType": "CustomPayload",
                    "content": "testing..."
                }
            ]
        }

![image](https://github.com/aws-samples/aws-lex-web-ui/assets/48177194/d0109cfa-9add-4c7d-8b15-c4a2e47a6a9f)

**Comment by atjohns** [comment]
What does your config look like for your `positiveFeedbackIntent `and `negativeFeedbackIntent` line items? I'd like to recreate on my side and see what's happening

**Comment by JohnnyPeng123** [comment]
> What does your config look like for your `positiveFeedbackIntent `and `negativeFeedbackIntent` line items? I'd like to recreate on my side and see what's happening

In the lex-web-ui-loader-config.json file, they are set as:

    "positiveFeedbackIntent": "Thumbs up",
    "negativeFeedbackIntent": "Thumbs down",

**Comment by atjohns** [comment]
I was able to recreate this - it appears to happen only if the first message to the user is a custom payload. Can you validate that subsequent messages show the thumbs up/thumbs down?

**Comment by JohnnyPeng123** [comment]
> I was able to recreate this - it appears to happen only if the first message to the user is a custom payload. Can you validate that subsequent messages show the thumbs up/thumbs down?

Thanks for recreating the issue. For my use case, Lex only returns custom payload, so the first message is always a custom payload. Is there other ways around this issue?

**Comment by atjohns** [comment]
The logic happens in line 92 of Message.vue, if you wanted to modify that to get the behavior you need that would work. You could also add a welcome message to your bot that doesn't need feedback buttons so that subsequent answers provide feedback, which would work around the problem without a code change.

```
<div
 v-if="message.id === this.$store.state.messages.length - 1 && isLastMessageFeedback && message.type === 'bot' && botDialogState && showDialogFeedback"
                  class="feedback-state"
                >
```

**Comment by JohnnyPeng123** [comment]
> The logic happens in line 92 of Message.vue, if you wanted to modify that to get the behavior you need that would work. You could also add a welcome message to your bot that doesn't need feedback buttons so that subsequent answers provide feedback, which would work around the problem without a code change.
> 
> ```
> <div
>  v-if="message.id === this.$store.state.messages.length - 1 && isLastMessageFeedback && message.type === 'bot' && botDialogState && showDialogFeedback"
>                   class="feedback-state"
>                 >
> ```

I do have a welcome message set-up in the JSON config file as the following:

  "lex": {
    "initialText": "Hello!",
  },

But that didn't work for me. How should I change logic in line 92 to make it work? I am thinking removing "&& isLastMessageFeedback", but I am never use Vue.js before, so I am not sure about this. Thanks in advance!
