### ISSUE TITLE
toolbarLogo & avatarImageUrl in the v0.20.0 template is not working 

### ISSUE THREAD

**Issue by JohnnyPeng123** [aws-samples/aws-lex-web-ui#565]
In the latest template (v0.20.0), I tried setting the following 2 parameters as the url to the JPG image (not the s3 url, the https one):

toolbarLogo
avatarImageUrl

But it didn't come through to the UI properly as shown below.

![image](https://github.com/aws-samples/aws-lex-web-ui/assets/48177194/ea0f99fe-65d1-45d9-ba11-8af5e6f46078)

I can confirm both the url is publicly accessible, just wondering is there a requirement on the size or format for the image? Any advise would be appreciated, the image below shows the current size of the image I am using.

![image](https://github.com/aws-samples/aws-lex-web-ui/assets/48177194/0485825b-5de4-4416-897b-1e7192f50035)

**Comment by JohnnyPeng123** [comment]
> Can you share what your config looks like for these two values?

It is configured as below:

    "toolbarLogo": "https://fetch-profile-pic.s3.us-west-2.amazonaws.com/fetch-profile-pic.jpg",
    "avatarImageUrl": "https://fetch-profile-pic.s3.us-west-2.amazonaws.com/fetch-profile-pic.jpg",

**Comment by atjohns** [comment]
Ah yes this is probably due to the CSP that is in place as of the latest version. I'll put in a bug to fix this but for now you can either add `fetch-profile-pic.s3.us-west-2.amazonaws.com` under `MarkdownSupportDomains` in the CloudFormation template or manually add it to the CloudFront CSP header.

**Comment by JohnnyPeng123** [comment]
> Ah yes this is probably due to the CSP that is in place as of the latest version. I'll put in a bug to fix this but for now you can either add `fetch-profile-pic.s3.us-west-2.amazonaws.com` under `MarkdownSupportDomains` in the CloudFormation template or manually add it to the CloudFront CSP header.

That worked, thanks a lot for your help!
