### ISSUE TITLE
Getting no response on lex Ui bot

### ISSUE THREAD

**Issue by shivangisharma991** [aws-samples/aws-lex-web-ui#584]
I am not getting response of any prompt I enter on the lex-ui, not sure what is wrong or I to troubleshoot to check the issue. Any suggestion would be helpful.
<img width="1258" alt="Screenshot 2023-11-28 at 16 37 29" src="https://github.com/aws-samples/aws-lex-web-ui/assets/69389188/23e3f245-da74-4942-b09f-a84198dad993">

**Comment by atjohns** [comment]
There are a lot of things that could be happening here. Can you use the Developer tools of your browser to see if there are error messages?

**Comment by shivangisharma991** [comment]
> There are a lot of things that could be happening here. Can you use the Developer tools of your browser to see if there are error messages?

No, I don not see any error in developer tool of my browser.

**Comment by atjohns** [comment]
No that's just something I need to clean up, would not effect the bot. If you can check the network traffic when it sends a call to Lex it should be hitting a /text endpoint. Can you check what is happening on those calls - it could be an issue with the Lex bot itself.
