### ISSUE TITLE
iframe loading timeout

### ISSUE THREAD

**Issue by patran** [aws-samples/aws-lex-web-ui#59]
The latest release ...All files are from the same origin and in the same directory...

Appreciate all pointers...

Thanks...

(index):82 Error: chatbot loading time out
    at readyManager.onConfigEventTimeout (iframe-component-loader.js:356)
(anonymous) @ (index):82
Promise.catch (async)
(anonymous) @ (index):81
(index):117 Uncaught TypeError: Cannot read property 'style' of null
    at (index):117
(anonymous) @ (index):117
setTimeout (async)
document.getElementById.onclick @ (index):116

**Comment by patran** [comment]
I set iframeOrigin to an absolute URL and still getting timeout...

iframe-component-loader.js:212 postMessage not sent over MessageChannel MessageEvent
onMessageFromIframe @ iframe-component-loader.js:212
iframe-component-loader.js:212 postMessage not sent over MessageChannel MessageEvent
onMessageFromIframe @ iframe-component-loader.js:212
(index):82 Error: chatbot loading time out
    at readyManager.onConfigEventTimeout (iframe-component-loader.js:356)
(anonymous) @ (index):82

**Comment by patran** [comment]
I resolved it by simply using the built-in cloud formation

**Comment by sidharththapar** [comment]
Can you please explain in detail the "built-in cloud formation" method which helped you embed iframe without timing out.

Error faced:
Error: chatbot loading time out
    at readyManager.onConfigEventTimeout (iframe-component-loader.js:505)

**Comment by abdulsamadCS** [comment]
**### I am facing the same issue. Unable to resolve!**

Can you please explain in detail the "built-in cloud formation" method which helped you embed iframe without timing out.

Error faced:
Error: chatbot loading time out
at readyManager.onConfigEventTimeout (iframe-component-loader.js:524)

**Comment by oliverchoy** [comment]
Have the same issue on 0.18.0 onwards:
chatbot UI failed to load Error: chatbot loading time out
    at e.onConfigEventTimeout (iframe-component-loader.js:517)

**Comment by bobpskier** [comment]
Timeouts on load occur primarily due to misconfiguration of the parent origin. The LexWebUi is deployed with strict CORS control. If the loader can't access relevant files from the web app s3 bucket via cloud front, it will timeout and produce the error above. In order to pinpoint the problem please let us know the url of the parent page where you are loading the bot, a copy of the lex-web-ui-loader-config.json file, browser console error log messages, and a copy of the network requests made by the browser during page startup. If you see a CORS error in the browser console error log during page load, the parent origin configuration is most likely the culprit.

**Comment by radycle** [comment]
I wasn't sure if I should post here or open a new issue.  Experiencing the CORS error on v0.19.4.

**Comment by manjushankar1972** [comment]
> Timeouts on load occur primarily due to misconfiguration of the parent origin. The LexWebUi is deployed with strict CORS control. If the loader can't access relevant files from the web app s3 bucket via cloud front, it will timeout and produce the error above. In order to pinpoint the problem please let us know the url of the parent page where you are loading the bot, a copy of the lex-web-ui-loader-config.json file, browser console error log messages, and a copy of the network requests made by the browser during page startup. If you see a CORS error in the browser console error log during page load, the parent origin configuration is most likely the culprit.

@bobpskier, Thanks for all your support on this subject. Can you please check and suggest, what is mistake which is causing the timeout error.
Problem: chatbot UI failed to load Error: chatbot loading time out 
A. URL of the parent page: https://cjj.932.myftpupload.com/
B. Copy of the lex-web-ui-loader-config.json file image attached. Please note that used the following URLs as iframeOrigin. In both the cases, got the same time out error.
1. https://ddb28chhob2uu.cloudfront.net
![image](https://user-images.githubusercontent.com/79458301/165726479-f6080587-514d-4a7b-9e6c-fe93ad446c58.png)
2. https://lex-web-ui-naren-codebuilddeploy-1nz-webappbucket-1nd8ex102nufy.s3.us-east-1.amazonaws.com
C. Browser console error log messages - image attached
![image](https://user-images.githubusercontent.com/79458301/165726891-340fdec7-90b1-45ad-a53c-20e54150bb90.png)
D.  Copy of the network requests made by the browser during page startup - images attached
![image](https://user-images.githubusercontent.com/79458301/165727457-c8584ed4-c4f2-458a-be11-3bddb1411a31.png)
![image](https://user-images.githubusercontent.com/79458301/165727676-c2108261-be05-47a8-8c35-a2273d4aab1a.png)

Thanks.

**Comment by bobpskier** [comment]
When I navigate to the page https://cjj.932.myftpupload.com/index.html, it successfully loads the lex-web-ui-loader-config.json file. However, the parentOrigin is to

```
"parentOrigin": "http://stellaridealabs.com",
```

This will be problematic when the lexwebui checks for the allowed origins. If the parent page is "https://cjj.932.myftpupload.com/index.html" then the parentOrigin would need to be "https://cjj.932.myftpupload.com". 

I also noticed the url above loads from a different cloudfront distribution than listed in point #1. Point #1 indicates https://ddb28chhob2uu.cloudfront.net. The index.html from https://cjj.932.myftpupload.com/ is loading from https://d232ym6dxri0gr.cloudfront.net.

There might be some configuration inconsistencies on the parent page with respect to identifying the lexwebui that should be loaded. I'd start there and make sure the index.html is referencing the correct lexwebui via its reference to the cloudfront distribution.

Once this is correct, then the lex-web-ui-loader-config.json can be confirmed to be set correctly for the parent page. Don't forget that browser cache, and caches maintained by cloudfront need to be cleared after configuration changes as they may be pointing at stale data.
