### ISSUE TITLE
Update npm package?

### ISSUE THREAD

**Issue by RamenWarlord** [aws-samples/aws-lex-web-ui#614]
Hi, creating this issue to ask if it would be possible for you to update the npm package to latest release since aws-lex-web-ui seems to be at ver 0.13.2 on npm. Consuming an npm package would work best in my use case but the version is out of date and seems to lack a lot of functionality in latest versions.

**Comment by atjohns** [comment]
Thanks yes I will work on getting this updated.

**Comment by atjohns** [comment]
Hi, after digging around it appears this npm package was not created by our team and we cannot support it as we do not own it. My apologies
