### ISSUE TITLE
Applying v0.20.6 update loads v0.20.5 of the web UI

### ISSUE THREAD

**Issue by chanbi-aws** [aws-samples/aws-lex-web-ui#622]
After updating the stack (via 'Replace current template') with the master.yaml (https://github.com/aws-samples/aws-lex-web-ui/blob/master/templates/master.yaml), the upgrade is successful to v0.20.6, but the web UI initialises with version 0.20.5. Browser console output: "lex-web-ui.min.js:29 successfully initialized lex web ui version:  0.20.5".

**Comment by atjohns** [comment]
I don't think it will negatively effect anything since 0.20.6 was just to fix some Python versions in the Lambda deployment scripts, there was no change to the Web UI itself. That is also probably why the Web UI is still labeled 0.20.5 since no changes were made to the code.

**Comment by chanbi-aws** [comment]
But the loader is loading version version 0.20.5 of the lex-web-ui.min.js, so it is using the older version.

**Comment by chanbi-aws** [comment]
I also checked the S3 bucket (that is the origin for the CloudFront distribution) and the files such as lex-web-ui.min.js and lex-web-ui-loader.min.js are all version v0.20.5

**Comment by atjohns** [comment]
Yeah something went wrong with deployment into the S3 buckets, as the distribution is properly labeled v0.20.6

**Comment by atjohns** [comment]
This should be resolved now.
