### ISSUE TITLE
Clicking the mic icon on the chatbot from the parent.html returns Javascript error

### ISSUE THREAD

**Issue by chanbi-aws** [aws-samples/aws-lex-web-ui#623]
Issue experienced in both Chrome ("Uncaught in promise DOMException: The element has no supported sources.") and Safari ("Unhandled Promise Rejection: NotSupportedError: The operation is not supported."). Screenshots attached.
![Screenshot 2024-02-28 at 6 04 00 pm](https://github.com/aws-samples/aws-lex-web-ui/assets/91114681/760f500f-110d-4730-bfd5-c2616e02c181)
![Screenshot 2024-02-28 at 6 02 50 pm](https://github.com/aws-samples/aws-lex-web-ui/assets/91114681/2e5b492b-5b26-46f3-a440-1f67710d10cf)

**Comment by atjohns** [comment]
Thanks, looking into this

**Comment by atjohns** [comment]
When you get a chance can you validate that the newest build fixes this issue?

**Comment by chanbi-aws** [comment]
Same issue. First click on the mic does nothing, then second click throws the error. Ping me internally and I can share the cloudfront URL if required for you to reproduce.

**Comment by atjohns** [comment]
After digging into this, its a bug from how we generate the initial speech for different locales. It appears the _AU files are not being properly generated.

**Comment by alexsambacanada** [comment]
Hey there @atjohns.  I am running into an issue with the fr_CA locale.  Seems that the content type is text/html for the initial mp3 (which is different than the english locale which is working fine).  First press of the microphone button does nothing then I get the same errors as reported above.  Could this be the issue as the original post?

**Comment by alexsambacanada** [comment]
Big thanks to @atjohns for the help.  Confirmed this was the same issue.  Here's the workaround that fixed it for me (can use this until they release a fix):
1. Inspect your lex-web-ui page and see what file it is trying to grab (in my case it was`initial_speech_fr_CA.mp3`)
2. Go to Amazon Polly and make your own .mp3 file in the language you want.  Name it the same as what the site wants `initial_speech_fr_CA.mp3` and upload it to the S3 bucket your site is being served from (you can get the name of the bucket through Cloudfront)
3. I invalidated the Cloudfront distro and cleared the browser cache settings for good measure.
4. Refresh your page and it should call the .mp3 you uploaded.
