### ISSUE TITLE
.toolbar.theme--dark no longer working in custom-chatbot-style.css

### ISSUE THREAD

**Issue by justinramnandan** [aws-samples/aws-lex-web-ui#628]
We recently upgraded our lex-web-ui and noticed that the css for the .toolbar.theme--dark is no longer working after the upgrade.

**Comment by atjohns** [comment]
Hi,
Yes if you read the latest release notes you'll see we upgrade from Vuetify 1.5 -> Vuetify 3 as part of getting Vue 3 upgraded. Can you share your custom CSS, the team would like to support the dark theme as much as possible.

**Comment by atjohns** [comment]
So just to tack on, for this specific one Vuetify 3 no longer labels it as .toolbar.theme--dark, you can override with .bg-red now

.bg-red {
  background-color: #2b2b2b !important;
}

**Comment by justinramnandan** [comment]
Thanks, this will work.
