### ISSUE TITLE
Include Cognito JWT token for intent in Lex Fulfilment Lambda 

### ISSUE THREAD

**Issue by theSJace** [aws-samples/aws-lex-web-ui#636]
Hi, are there any docs/guides on including the JWT token for authenticated users in the user conversation with Lex. I require the JWT token to be passed from the Lex chatbot to the fulfillment lambda that fulfills the intent. What is the best way to do that with the lex-web-ui?

**Comment by atjohns** [comment]
Hi, I think the best way to do that would be to use session attributes. There is some documentation on how to pass variables up from the parent to the Lex bot here: https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#iframe-loader-api-functions
