### ISSUE TITLE
Carousel, quick reply, time picker?

### ISSUE THREAD

**Issue by chizzle** [aws-samples/aws-lex-web-ui#638]
I found documentation regarding interactive messages for Amazon Connect and Lex but the only one I can get to work is the list picker.  Are carousel, quick reply, time picker, etc, not supported?

https://docs.aws.amazon.com/connect/latest/adminguide/interactive-messages.html

**Comment by atjohns** [comment]
Carousel and quick reply are newer releases and I have not added support for those. I'm hoping to add support in the next release. Time Picker should work but that could be a bug, we'll look into it.

**Comment by chizzle** [comment]
Super fast response!  Thanks!  I literally just figured out why the time picker wasn't working.  The sample code on the amazon doc has an extra curly brace } at the end.  I didn't realize it until I did a test in Lambda.  The UI shows up but I've made a few customizations to the CSS so it's not showing the days/times like in the picture.  I'll play around more tomorrow.
