### ISSUE TITLE
Page title is hardcoded

### ISSUE THREAD

**Issue by juluriaj** [aws-samples/aws-lex-web-ui#643]
After deploying the lex-web-ui template, page title is not reflecting the values provided in the Cloudformation parameters. 

This seems hardcoded here and overriding what's in the configs - https://github.com/aws-samples/aws-lex-web-ui/blob/2d2358e273437e98875ec52ecbf3d5b837a09279/lex-web-ui/src/config/index.js#L153

**Comment by atjohns** [comment]
That should get overwritten by your own config, can you share what your lex-web-ui-loader-config.json file looks like?

**Comment by juluriaj** [comment]
Ideally yes, but its missing pageTitle attribute. I had to manually add pageTitle and upload to reflect the changes.

**Comment by atjohns** [comment]
Yes most users tend to embed the Web UI into another page, so it is a manual add to the config we don't bubble it up into the template parameters.
