### ISSUE TITLE
Issue with uploading artifacts to S3 with ACL in place

### ISSUE THREAD

**Issue by sleepwithcoffee** [aws-samples/aws-lex-web-ui#663]
From the doc:

> A majority of modern use cases in Amazon S3 no longer require the use of ACLs. We recommend that you keep ACLs disabled, except in unusual circumstances where you need to control access for each object individually. With ACLs disabled, you can use policies to control access to all objects in your bucket, regardless of who uploaded the objects to your bucket.

References:
* [Access control list (ACL) overview](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html)
* [Controlling ownership of objects and disabling ACLs for your bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html)

I would suggest removing the `--acl public-read` options from `build/upload-bootstrap.sh`

Error log:

```bash

upload failed: out/src-v0.21.1.zip to s3://.../src-v0.21.1.zip An error occurred (AccessControlListNotSupported) when calling the CreateMultipartUpload operation: The bucket does not allow ACLs

upload failed: out/custom-resources-v0.21.1.zip to s3://.../custom-resources-v0.21.1.zip An error occurred (AccessControlListNotSupported) when calling the CreateMultipartUpload operation: The bucket does not allow ACLs

upload failed: out/initiate-chat-lambda-v0.21.1.zip to s3://.../initiate-chat-lambda-v0.21.1.zip An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs

upload failed: out/streaming-lambda-v0.21.1.zip to s3://.../streaming-lambda-v0.21.1.zip An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs

```

The version of code: v0.21.1

**Comment by atjohns** [comment]
Makes sense, I will grab the PR and put it in the next release
