### ISSUE TITLE
Iframe in a subfolder not working

### ISSUE THREAD

**Issue by Guillaume-Bourque-Levio** [aws-samples/aws-lex-web-ui#674]
Hello, 

we are trying to use the iframe provide distribution.  As per instructions say we can copy all files from dist/ directory to our document root.   But in the dist directory their is an index.html file which we already have in our document root as any normal site.

So what we need is a procedure to use th iframe solution from a subdirectory of our document root.

From the test we did, the ./ derectory is hardcoded.

Also in the dist/ directory only the min files are provided but the code is refering to unminimise files.

Maybe I miss something but your help would be greatly appreciated.

Best, Guillaume.

**Comment by bobpskier** [comment]
@Guillaume-Bourque-Levio The easiest mechanism to embed as an iframe is to deploy lex-web-ui using the existing CloudFormation templates. You specify the lex bot it will use and the parent domain where the iframe is going to be hosted. There are a number of parameters you can specify while running the template that adjusts the default configuration of lex-web-ui. The template will create an S3 bucket, publish the distribution to this bucket (webapp bucket), and will build a cloudfront distribution to serve up the lex-web-ui. One of the CF outputs of this CF template is a snippet of html/javascript that you embed in your existing index.html. Once the javascript is embedded in your index.html, the iframe will be loaded. The config and css are all managed in the webapp S3 bucket.

**Comment by Guillaume-Bourque-Levio** [comment]
Thanks @bobpskier but the fact to include an Iframe from a different source url wont it bring some browser security issue ?

**Comment by bobpskier** [comment]
@Guillaume-Bourque-Levio The templates configure CORS based on the parent origin specified in the deployment. The iframe can only be loaded from a page in the parent domain. I've not run into any browser issues using this deployment mechanism if it is properly setup.

**Comment by Guillaume-Bourque-Levio** [comment]
If time permit, would it be a big effort to create a distribution that would work from a subfolder if hosting outside is not an option ? From what we understand this effort should be minimal with the knowledge of this solution ?

**Comment by bobpskier** [comment]
@Guillaume-Bourque-Levio In general, you would follow the instructions at https://github.com/aws-samples/aws-lex-web-ui?tab=readme-ov-file#iframe. You can copy the required dist files (*.js, *.css) which does not require copying the index.html. You would modify your index.html per the instructions referenced above. You'll need to build a cognito user pool associated with a minimal IAM role for unauthenticated users that provides credentials to make calls to your lex bot. You'll probably also manually setup a lex-web-ui-loader-config.json file that specifies the desired config that the loader javascript will by default pull in. You may want to refer to the cloudformation templates to understand whats being done that you will manually need to do especially with respect to cognito. The templates also construct a lex-web-ui-loader-config.json based on the supplied parameters. You may want to run the template once to get a default lex-web-ui-loader-config.json file that you can use going forward unless you are comfortable building this up by hand.

**Comment by Guillaume-Bourque-Levio** [comment]
> The config and css are all managed in the webapp S3 bucket.

Hello @bobpskier I did deploy the web-ui cloud formation stack like you said, so it is siting on an independant bucket behind a cloudfront stack.

In cloud formation I provide my web site domain without a trailing / and the name of the page /demo.html that as the script snipet code.

Now when I load my web site/demo.html page I still get 403 on files like this.

Do I need to manually bring some files on my web sites or my web sites only need to point to the web-chat-ui bucket with the provided code snipet only ?

![image](https://github.com/aws-samples/aws-lex-web-ui/assets/165071022/803f255d-da15-4d7c-952b-ea639f6a4342)

You lights are more then welcome.

Best, Guillaume

**Comment by bobpskier** [comment]
@Guillaume-Bourque-Levio This usually occurs if the parent origin specified in the cloudformation template does not match the origin in use where the snippet of html/javascript has been used. For example, if the specified parent origin is "https://sample.com" but the page using the snippet is "https://mydomain.com/site/demo.html", a CORS / 403 error will be seen. Also, the parent origin should only include the domain and not any child pages or paths. Its not clear in your message how the parent origin was specified but perhaps this is the case.
