### ISSUE TITLE
See a lot of errors when run npm run dev

### ISSUE THREAD

**Issue by DeveloperXMA** [aws-samples/aws-lex-web-ui#677]
Steps to reproduce.
1. Go to root folder, run `npm install`
2. Go to lex-web-ui folder, run `npm install`
3. run `npm run dev`

I will see a lot of errors, like

Definition for rule 'import/extensions' was not found
Definition for rule 'import/no-extraneous-dependencies' was not found
<template v-for> cannot be keyed. Place the key on real elements instead

There are 461 problems when I execute above commands, it this expected or I am doing somehting wrong.

Thanks

**Comment by sleepwithcoffee** [comment]
hi @DeveloperXMA , I am doing a blind guess here but you may need to use node v18 or higher to avoid certain errors

**Comment by DeveloperXMA** [comment]
Hi @sleepwithcoffee , I checked my node version on my two macs, one is v18.20.2 and the other is v21.6.1, they all have this error, and a lot more errors,

I just clone this project and did exact the above 3 steps, however I get a lot problems to get it running, Can you share with me what's your development process of this project?

<img width="969" alt="image" src="https://github.com/aws-samples/aws-lex-web-ui/assets/24968823/a789c101-b881-41d9-96f5-c4763721a2df">

**Comment by sleepwithcoffee** [comment]
hi @DeveloperXMA 
I simply follow the installation guide: https://github.com/aws-samples/aws-lex-web-ui?tab=readme-ov-file#building-and-deploying-your-own-lexwebui

Basically:
1. check out repo master branch
2. npm install at root folder
3. npm install at lex-web-ui nest folder: `cd lex-web-ui && npm install`

Please double check your node and npm versions:
```bash
$ node --version
v20.12.2
$ npm --version
10.5.0
```

**Comment by DeveloperXMA** [comment]
I just retied on my Windows and made my node version and npm version same as you, however I still get all those errors, no idea....

But thanks for your reply! Appreciate it.
<img width="907" alt="image" src="https://github.com/aws-samples/aws-lex-web-ui/assets/24968823/61855ddd-41cf-43de-9b64-b7f5fb8f24f8">

**Comment by atjohns** [comment]
Yeah the linting is very messed up since migrating to Vue 3. Please use 'npm start' for now for running the project locally, I will update the docs to reflect this in the next release and work on fixing the linting issues afterwards.
