### ISSUE TITLE
Enable Intent Trigger every start of a session

### ISSUE THREAD

**Issue by dangollayan** [aws-samples/aws-lex-web-ui#684]
As of now we have these two:
WebAppConfBotInitialText: Initial text sent by the bot every session started
WebAppConfBotInitialUtterance: Initial utterance sent to the bot every session started (forces an intent to trigger)

Currently, the WebAppConfBotInitialText parameter is utilized to send an initial message from the bot at the start of each session. However, there's a need for this initial text to trigger an intent without requiring a separate initial utterance to be sent by the user.

Use Case:
Our use case requires prompting the user for their name at the beginning of each session. By setting the initial text as an intent, we can ensure that this prompt consistently appears at the start of every conversation, without relying on a user-sent initial utterance.

Is there a way to do this?

**Comment by atjohns** [comment]
Sorry please help me understand why the same value cannot be used for both parameters to accomplish this?

**Comment by dangollayan** [comment]
Hi @atjohns, sorry for the late reply, our purpose is we want to force an utterance every start of conversation without forcing a prompt from the user side

**Comment by atjohns** [comment]
No problem, I don't understand how `WebAppConfBotInitialUtterance` isn't fails to accomplish this for you then. What is it not doing that you need done?

**Comment by israelias** [comment]
@dangollayan Yes, [it is](https://github.com/aws-samples/aws-lex-web-ui/issues/197#issuecomment-1788561924). And you want to hide the first message as it functions as an initialUtterance by a human disguised as an initialText by a bot.

https://github.com/aws-samples/aws-lex-web-ui/issues/197
