### ISSUE TITLE
Upgraded QnA Bot from v5.4.5 to v5.5.1

### ISSUE THREAD

**Issue by ijmoya** [aws-samples/aws-lex-web-ui#686]
Prior to our update we had our custom branded logo on our QnA admin site on the top right corner. We would update the following to bring our logo back after every update but it is no longer working with the recent update. 

The logo was stored in a publicly accessible bucket in order to be used. 

Added the following code to the very bottom of the main.js page.

(function (){
  $(document).ready(function (){
    var logo = document.createElement('img');
    logo.src = 'https://s3.us-west-2.amazonaws.com/at.maricopa.edu/mcccd-brand/Logo_RGB_MCCCD_Horizontal.png';
    $(".toolbar__items")[0].prepend(logo)
  })  
}) ();

Add the following code to the index.html <body> tag as a new line
script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

**Comment by ijmoya** [comment]
This update wasn't for our lex-web-ui it is for our QnA. It jumped from v5.4.5 to v5.5.1. So there were changes to some files here is the change log. 

- https://github.com/aws-solutions/qnabot-on-aws/blob/main/CHANGELOG.md

Updated
Migrated out of Bluebird promises to native promises
Migrated to AWS SDK for JavaScript v3
Upgraded to Webpack 5
Upgraded to Vue3
Upgraded to Vuetify 3
Upgraded to latest LLM Image
Code Quality improvements based on SonarQube analysis
Security patches for npm

*looks like it added files in our QnA Bot S3 bucket as well. As there were 13 objects previously and now there are over 23 objects in our bucket.

**Comment by atjohns** [comment]
Hmm so an update to the QnA bot broke the Web UI? That's interesting they should not be connected in any way the Web UI is very much its own entity. I'll try to reproduce still and see if I can find a root cause.

**Comment by atjohns** [comment]
Oh so this is purely a QnA Bot issue? You should ask over there.
