### ISSUE TITLE
Update ChatJS version to support the Connection Acknowledgement(ConnAck) event migration to the ConnectParticipant API

### ISSUE THREAD

**Issue by JoabHInclineIT** [aws-samples/aws-lex-web-ui#687]
Hi,

This is my first GitHub repo issue/suggestion so please forgive me if there is not enough information present.

We are using LexWebUI as a live chat widget on our customers' websites. Agents are receiving inbound chats on our custom CCP interface (embedded CCP).

We would like to send the `application/vnd.amazonaws.connect.event.connection.acknowledged` event from the LexWebUI to the agent on a recurring basis so we can monitor the state of inbound connections. 

As mentioned on the official AWS documentation, this event is becoming deprecated and has migrated to the ConnectParticipant API. However, as stated on the official amazon-connect-chatjs repo it requires ChatJS 1.4.0 or higher.

![image](https://github.com/aws-samples/aws-lex-web-ui/assets/169167835/58d6e0b1-8733-4b77-8a11-2c09c3342baf)

I can see in the package.json for this project that the chatjs version used is listed as 1.1.7
`"amazon-connect-chatjs": "^1.1.7",`

Are you able to upgrade the ChatJS dependency to something more recent, to support this migration, or will this introduce breaking changes?

Please let me know if you require more information on the use case.

Thanks

**Comment by atjohns** [comment]
Thanks for putting this issue in. I will investigate getting this upgraded, I don't see why it would introduce any breaking changes but if this is getting deprecated we'll have to get it working regardless. Thanks for putting it on our radar.

**Comment by atjohns** [comment]
We have updated to the latest version of the ChatJS in release v0.24.1, please let me know if you run into any issues
