### ISSUE TITLE
Lex V2 postTextMessage AccessDeniedException

### ISSUE THREAD

**Issue by GaryMLDev** [aws-samples/aws-lex-web-ui#698]
Question: 
I've brought up your default webpage and have signed into Cognito.  
When enter any text in Lexbot I get:  
"Sorry, I was unable to process your message. Try again later." 

From Chrome Console: 
Failed to load resource: the server responded with a status of 403 () runtime-v2-lex.us-east-1.amazonaws.com/bots/[my bot]

error in postTextMessage AccessDeniedException   lex-web-ui.min.js:28 

Trying to diagnose IAM error.  
any help appreciated.

**Comment by israelias** [comment]
@GaryMLDev 

Looks like the initial postText to verify creds isn't set in your config. 

COGNITO_POOL_ID should let you through unless you've manually added perms to `<stackname>--Unauthenticated-Role**` or switched from template to manual build in either case there's at least three more properties that may be missing from  `lex-web-ui-loader-config.json` that the loaders are expecting on init.

```js
	const config = {
      appUserPoolClientId: this.config.cognito.appUserPoolClientId,
      appDomainName: this.config.cognito.appDomainName,
      appUserPoolIdentityProvider: this.config.cognito.appUserPoolIdentityProvider,
    };
```

- https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/lex-web-ui-loader/js/lib/fullpage-component-loader.js#L38-L40
- https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/lex-web-ui-loader/js/lib/iframe-component-loader.js#L149-#L152

Most of these are visible in the CF's `apiGateWay/prod` endpoint. Or in the cognito pool pointed to the stack.

For completeness' sake on "access":

```jsonc
{
  "cognito": {
   "poolId": COGNITO_POOL_ID,
   "appUserPoolClientId": COGNITO_USER_POOL_CLIENT_ID,
   "appUserPoolName": COGNITO_APP_USER_POOL_NAME,
   "appUserPoolIdentityProvider":  COGNITO_APP_USER_POOL_IDENTITY_PROVIDER,
   "appDomainName": COGNITO_APP_DOMAIN_NAME,
    ...config.cognito,
},
  "lex": {
     "v2BotId": V2_BOT_ID,
     "v2BotAliasId": V2_BOT_ALIAS_ID,
     ...config.lex,
  },
...config,
}
```

*note fyi the VARIABLE naming convention above is not affiliated with the src code

**Comment by GaryMLDev** [comment]
It was the LexPost Policy on the Identity Pool Authenticated/Unauthenticated Roles.   It was not allowing my bot alias.

**Comment by israelias** [comment]
@GaryMLDev if it wasn't already there and in case you encounter an Access related error forthcoming, there's an auto gen `<stackname>-LexAccess-**` perm you may need to attach to `<stackname>-Unauthenticated-Role-**` that includes the message channel scope beyond PostText namely PollySynthesizeSpeech, RecognizeText etc in case you have `recorder.enabled: true` and so on. The catch all would be to just add `AmazonLexRuntimeBotsOnly` policy to the unauthorized role.
