### ISSUE TITLE
.card__actions .btn no longer working in custom-chatbot-style.css

### ISSUE THREAD

**Issue by sarah-chua** [aws-samples/aws-lex-web-ui#699]
Hi, I noticed that based on the latest release, the CSS selector `.card__actions .btn` no longer works. 

In commit 54fa3f89f3ab32a89d1874f01fad412bf487c4ac, the CSS selector was modified in `lex-web-ui/src/components/ResponseCard.vue` from `.card__actions .btn` to `.v-card-actions .v-btn`. This is the [link](https://github.com/aws-samples/aws-lex-web-ui/commit/54fa3f89f3ab32a89d1874f01fad412bf487c4ac#diff-72c150dc36480042f248cd826eef5a2e0c271b3aafacd0e37f6ef08a5c0ddb1cL118) to the referenced change.

Should this change to `.v-card-actions .v-btn` also be reflected in `README-css-style.md`?

**Comment by atjohns** [comment]
Yes, thank you for catching that, I will update the README. The upgrade to Vue3 required some changes to the CSS selectors but I missed this one in the documentation.

**Comment by atjohns** [comment]
This has been updated in the latest release
