### ISSUE TITLE
Parameters: [IDCApplicationARN] must have values

### ISSUE THREAD

**Issue by usmanlumen92** [aws-samples/aws-lex-web-ui#706]
I have deployed the cloudstack formation. Now when trying to launch this repository I am getting the error:
Parameters: [IDCApplicationARN] must have values

There is no field present with this parameter so i am not sure where and how I can provide this value.

If someone has any idea Kindly share the solution please. I have searched everywhere but couldnot find the solution.

Best regards
Usman

**Comment by atjohns** [comment]
Looks like a bug with the latest release, investigating now

**Comment by usmanlumen92** [comment]
@atjohns You're a gem. 
Thank you very much.
