### ISSUE TITLE
Unable to run lex-web-ui locally in Windows

### ISSUE THREAD

**Issue by hannahvarughese** [aws-samples/aws-lex-web-ui#710]
I am trying to make some code changes in lex-web-ui in Windows. I am hosting it via WSL(Ubuntu). When I do `npm run dev`, it is compiling successfully without any errors. But, in the browser it is showing the following error:
`GET http://localhost:8080/%3C%=%20BASE_URL%20%%3Efavicon.png 400 (Bad Request)` . 

I am new to QnAbot and may be there might be a mistake in my configuration. 

Can someone please guide me to resolve this issue?

**Comment by atjohns** [comment]
You want to use `npm start` to run the Web UI locally, and make sure you are inside the /lex-web-ui folder. The parent folder contains the loader not the actual Web UI Vue application

**Comment by hannahvarughese** [comment]
I tried `npm start` in the lex-web-ui folder. I am still getting the same error.
`URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.png'`.
I did `npm run build-dist` before `npm start` and the build was successful.

**Comment by atjohns** [comment]
Thanks, I'll double check that you shouldn't have to do the build-dist command. I'll close this out for now since you've resolved

**Comment by hannahvarughese** [comment]
Sorry, I didn't mention it fixed. Only, the build was successful. When I tried `npm start` . It throws the error:
`URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.png`

**Comment by atjohns** [comment]
Okay I did a fresh install and was able to replicate, reopening this and will let you know what the solution is

**Comment by atjohns** [comment]
Okay its running the wrong webpack configuration for some reason, in the vue.config.js change this...

```
module.exports = {
  chainWebpack: (buildType.isLib) ? chainWebpackLib : chainWebpackApp,
};
```
to this
```
module.exports = {
  chainWebpack: chainWebpackApp,
};
```

**Comment by hannahvarughese** [comment]
It worked. Thank you so much.
