### ISSUE TITLE
Can't deploy latest version of lex web ui

### ISSUE THREAD

**Issue by dangollayan** [aws-samples/aws-lex-web-ui#711]
stack error:
![image](https://github.com/user-attachments/assets/b61245a3-bc87-41c5-8a15-cca4771b1938)

**Comment by atjohns** [comment]
I have not seen that error before, the only thing I can think of is the 100 bucket limit per account. I believe that can be changed on request by submitting a service limit increase.

**Comment by dangollayan** [comment]
Hi @atjohns , you are correct. Thanks!
