### ISSUE TITLE
Attachments paperclip doesn't show

### ISSUE THREAD

**Issue by seanhufnagel** [aws-samples/aws-lex-web-ui#716]
In the Lex Web UI cloudformation template I have set ShouldEnableUpload to true and added an s3 bucket name to the UploadBucket parameter. My chat widget works as expected however there is no paperclip icon to attach a file to the chat and upon exploring the code base I am not finding anywhere where that icon is referenced. What steps can I take to troubleshoot this and get the attachment icon to appear in my chat widget?

**Comment by atjohns** [comment]
Are you logged in? By default upload is disabled unless the user is logged in. See the [README](https://github.com/aws-samples/aws-lex-web-ui/blob/master/README-file-upload.md) for details on how to change that behavior.

**Comment by seanhufnagel** [comment]
When you say login are you referring to the Cognito pool? My chatbot does not use Cognito or any login process. So just to confirm ShouldEnableUpload is not compatible unless a Cognito pool is also in use?

**Comment by atjohns** [comment]
Yes for security we don't have anonymous uploads enabled without a manual config modification. To support anonymous uploading, you will need to configure your own IAM policies in Cognito and manually set uploadRequireLogin to false in your lex-web-ui-loader-config.json file. Allowing anonymous uploading of documents is not recommended.

**Comment by seanhufnagel** [comment]
Is there anyway you could provide guidance on how that can be completed? If I am not using Cognito at all I don't get why I would need to configure IAM policies in there.. Also when I explore the codebase I am not seeing the paperclip icon anywhere in the code for me to modify its function.

**Comment by atjohns** [comment]
Sure, so the Web UI uses Cognito to provide access to your bot. Even if you don't use it, there is still an unauthenticated role that has permissions to make calls. You will need to add permissions to make S3 calls into the bucket you selected for uploading as well. 

If you navigate to Cognito -> Identity Pools and find the User access tab, you will see a Guest access section with a role attached. Click on that role and add the following policy permissions to it.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::<your bucket>/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**Comment by seanhufnagel** [comment]
Thanks for your response. The upload feature is now working so that the attachments are being added to s3 and can be accessed from there. In addition, I am trying to enable the sharing of attachments while on a live chat and I it works when sending from the chat widget to an agent but whenever the agent sends an attachment from CCP it doesn't show in the chat widget. Does lex-web-ui support receiving attachments? If so what do I need to do to display the attachment to the customer?

**Comment by atjohns** [comment]
Currently this is not supported, I will add it to our list of enhancement requests however.
