### ISSUE TITLE
Type error in aws-lex-web-ui/build /upload-bootstrap.sh

### ISSUE THREAD

**Issue by byoungsoo** [aws-samples/aws-lex-web-ui#717]
When I execute upload-bootstrap.sh, layers.zip file isn't uploaded to S3.

```
aws s3 cp ..templates/layers.zip \
  "s3://${BOOTSTRAP_BUCKET_PATH}/layers.zip"
```

It needs to be fixed.
```
..templates -> ../templates
```

**Comment by atjohns** [comment]
Thanks, I will put in a fix for this in the next release. If you would like to submit a PR for it I can also approve that and get you credit for the fix.
