### ISSUE TITLE
rollback_failed Error showing in stack creation on CloudFormation 

### ISSUE THREAD

**Issue by ankitaivd** [aws-samples/aws-lex-web-ui#718]
when i create a CloudFormation stacks that i a alo attached IAM role with policy , but it is create a error like rollback_failed. also when i want delete that stack it is showing IAM role invalid or cannot be assumed. Iam role is exits.
Please help me on that. It is in aws CloudFormation  stack console

**Comment by atjohns** [comment]
Hi, going to need some more information to help you here. So did the initial deployment work but then you added some IAM roles? What did you add them to? Or was the initial deployment a failure? If so can you give me the exact error in the CFN template

**Comment by ankitaivd** [comment]
I added  Iam role. yes when i create CloudFormation stack that time this error is crated. 


![rollback](https://github.com/user-attachments/assets/be03c0c0-6fe7-44f4-987a-4f6e33247cdf)

**Comment by atjohns** [comment]
That error is saying you entered stuff for both V1 & V2 bots. It has nothing to do with your IAM role

**Comment by ankitaivd** [comment]
no , I add only lex v1,please check this.
![cloudformation](https://github.com/user-attachments/assets/d313dbb7-33c4-49e6-bf34-059b7bedc0fe)

**Comment by atjohns** [comment]
Did you change it from V2 to V1 at some point? That is the other thing that error could indicate. I'd maybe delete this stack and start fresh.

**Comment by ankitaivd** [comment]
No,I only add v1 not v2 data. also i can not delete this stack also. showing  this eeror . I attched a screenshot for that.
But, this IAM role is exits.
![deletewproblem](https://github.com/user-attachments/assets/0043fe5f-2ee5-45e8-b5f6-822cfba01757)

**Comment by atjohns** [comment]
Gotcha, can you show me what that role looks like?

**Comment by ankitaivd** [comment]
Yes ,I am attaching iam role, policy, true policy .Please check it
![iamrolepolicy](https://github.com/user-attachments/assets/d38c8b8a-1221-4045-ba25-45479a3dc3c4)
.
![Iamrole](https://github.com/user-attachments/assets/54b14734-b180-4224-8417-61e7f8f85d10)

![iamroletruepolicy](https://github.com/user-attachments/assets/019252da-bc46-46ff-a0fc-ff54af39b23e)

**Comment by atjohns** [comment]
And your goal now is just to delete the stack yes? I would manually delete this policy then delete the stack, that should work.

**Comment by ankitaivd** [comment]
no, i want to delete and re-create the stack

**Comment by atjohns** [comment]
I'm confused as to what this role is for exactly. Did you manually create it?

**Comment by ankitaivd** [comment]
yes i created it manually.

**Comment by atjohns** [comment]
So the issue here is with the role that you are using to deploy the template, not with the web ui template itself.
