### ISSUE TITLE
How to setup minimum working example?

### ISSUE THREAD

**Issue by jenia** [aws-samples/aws-lex-web-ui#719]
Hello.

I'm running the chatbot UI component in an HTML page by [following the readme](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#run-test-server) in `src/README.md`:
```
npm start
```

But I get the message in the web console:
```
1 validation error detected: Value 'ca-central-1_someID' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+
```

Before hand I successfully created the Cognito identity pool using the Cloudformation [template](https://github.com/aws-samples/aws-lex-web-ui/blob/master/templates/cognito.yaml) and copied `User pool ID` from AWS Cognito interface but I still receive the error above.

And here is my `lex-web-ui-loader-config.json` config:
```
  "connect": {
    "contactFlowId": "",
    "instanceId": "",
    "apiGatewayEndpoint": "",
    "promptForNameMessage": "",
    "waitingForAgentMessage": "",
    "waitingForAgentMessageIntervalSeconds": "",
    "agentJoinedMessage": "",
    "agentLeftMessage": "",
    "chatEndedMessage": "",
    "attachChatTranscript": "",
    "transcriptMessageDelayInMsec": ""
  },
  "cognito": {
    "poolId": "ca-central-1_someID",
    "aws_cognito_region": "ca-central-1",
    "region": "ca-central-1"
  },
  "ui": {
    "enableLogin": true
  }
```

My questions are as follows:
1. Where do I get the Cognito pool id from? I copied the value directly from the field `User pool ID` in AWS Cognito interface.
2. What about the rest of the fields in `connect` object above? Do I need to create an API gateway for this minimal example? Or the [provided sample web app ](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#run-test-server) can call Lex without an API Gateway but simply call it directly? I looks to me that the [provided API Gateway cloudformation script](https://github.com/aws-samples/aws-lex-web-ui/blob/master/templates/restapi.yaml) is designed with the idea that you'll be hosting this code on an S3 bucket rather than running a simple example locally. I prefer to only run a simple example locally rather than hosting an entire website on S3 for now.

**Comment by atjohns** [comment]
The easiest thing to do, if you have deployed it via CloudFormation, is hit your deployed web app and check the network traffic. It will have a `lex-web-ui-loader-config.json` file and you can just copy the contents and paste it into your local config file for development.

To answer your questions directly
1. The pool ID should be an output you can pull from the template, but it should look something like <region>:<guid> (for example us-east-1:xxxxxx-xxxx-xxxx-xxxxxxxxxxx)
2. That object is only for doing Live chat with Amazon Connect, you can leave it blank for normal development

**Comment by jenia** [comment]
thank you kindly!

**Comment by jenia** [comment]
thank you!
