### ISSUE TITLE
Trying to use the libraries with my angular 6 application

### ISSUE THREAD

**Issue by abhishekdhotre** [aws-samples/aws-lex-web-ui#72]
Hello All,
I'm trying to use the lex-web-ui-loader.js file in my angular application. 
I have upload the code below:
[https://github.com/abhishekdhotre/AngularLexChatBot](url)

First, I have created an folder (see shared folder below) where I have copied all the files from dist folder to my application.

![image](https://user-images.githubusercontent.com/23284214/41893202-93ea53c2-78e0-11e8-87ee-418bc673493a.png)

Then, I imported the ChatBotUiLoader from the js file and calling the load function like below

`import ChatBotUiLoader from './shared/lex-web-ui-loader';`
`chatbot = new ChatBotUiLoader.FullPageLoader().load();`

After doing this, when I run the application I get following error in console

![image](https://user-images.githubusercontent.com/23284214/41893150-6819a36a-78e0-11e8-98a3-e1287b746ef8.png)

Please help me to resolve the issue and to integrate the library into my application.

**Comment by afinski-incomm** [comment]
@abhishekdhotre hey, have you found how to do that?

**Comment by ojo-john** [comment]
Did you ever figure this out?
