### ISSUE TITLE
Cognito cannot call Lex with IAM role

### ISSUE THREAD

**Issue by jenia** [aws-samples/aws-lex-web-ui#720]
I successfully ran the app using the instruction [here](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/README.md#install).

I'm slightly confused regarding the error I'm getting when I interact with the bot:

```
error in postTextMessage AccessDeniedException: User: arn:aws:sts::XXXXX:assumed-role/cognito6-CognitoUnauthRoleV1-XXXXXXXXX/CognitoIdentityCredentials 
is not authorized to perform: lex:RecognizeText 
on resource: arn:aws:lex:ca-central-1:XXXXXXXXXXXX:bot-alias/XXXX/XXXXX because no identity-based policy allows the lex:RecognizeText action
```

My question are as follows:
1. How does the JS script know the role `CognitoUnauthRoleV1-XXXXXXXXX` it needs to assume? I think that role was created when I ran the [Cloudformation Cognito script](https://github.com/aws-samples/aws-lex-web-ui/blob/master/templates/cognito.yaml)? Where did the JS script find the exact ARN to use? Perhaps when I did `npm run` it simply read the env variables and made calls to AWS to find the needed role?
2. What do I need to do to resolve the error? Do I need to login using the UI or do I need to allow the role `cognito6-CognitoUnauthRoleV1` to perform the action `RecognizeText`?
3. When I try to login using the UI, I get: `The parameters: App client Id, App web domain, the redirect URL when you are signed in and the redirect URL when you are signed out are required`. I don't see there params in the [sample config](https://github.com/aws-samples/aws-lex-web-ui/blob/master/src/config/default-lex-web-ui-loader-config.json). What is `app client id` in this case?

Here is my config:

```
{
  "cognito": {
    "poolId": "ca-central-1:XXXX-XXXXX-XXXXX-XXXXX",
    "aws_cognito_region": "ca-central-1",
    "region": "ca-central-1"
  },
  "ui": {
    "enableLogin": true
  },
  "lex": {
    "botName": "example00",
    "initialText": "You can ask me for help ordering flowers. Just type \"order flowers\" or click on the mic and say it.",
    "initialSpeechInstruction": "Say 'Order Flowers' to get started.",
    "initialUtterance": "",
    "region": "ca-central-1",
    "retryOnLexPostTextTimeout": false,
    "retryCountPostTextTimeout": 1,
    "v2BotId": "XXXXXX",
    "v2BotAliasId": "XXXXXX",
    "v2BotLocaleId": "",
    "allowStreamingResponses": false,
    "streamingWebSocketEndpoint": "",
    "streamingDynamoDbTable": ""
  }
}
````

**Comment by atjohns** [comment]
1. The roles are connected to Cognito, they are created by the CloudFormation when you deploy. You can find them on the identity pool in the AWS console under the 'User Access' tab. There is an authenticated and guest role, if you don't have logins set up you are probably using the guest role.

2. You need to adjust the role your Cognito login is using, yes

3. These should exist in the Cognito app/user pool, if your config settings are pointing to the right pieces of Cognito you shouldn't have to adjust anything

**Comment by jenia** [comment]
Hello @atjohns. Thank you for your reply. 

I managed to make the app work by giving the un-authenticated user in Cognito the right to call `RecognizeText` on my Lex bot.

So this, together with the picture below, means I'm definitely pointing to the right Cognito in AWS. I'm not sure why login fails though.

![image](https://github.com/user-attachments/assets/502155fd-cc86-47e5-9369-4c9223384939)

**Comment by israelias** [comment]
@jenia You'll want the whole curation under `AmazonLexRuntimeBotsOnly` permission tree. Namely, `RecognizeSpeech, *Intent` etc.

there's an auto generated `<stackname>-LexAccess-**` permission that includes the curated perms you may need to manually attach to `<stackname>-Unauthenticated-Role-**` if it isn't already synced.

Else attach  `AmazonLexRuntimeBotsOnly` to `<stackname>-Unauthenticated-Role-**` as it at least bears the lex/polly perms beyond your singular `RecognizeText`

https://github.com/aws-samples/aws-lex-web-ui/issues/698

**Comment by israelias** [comment]
@jenia Login fails if you haven't configured the authenticated-role to the same degree with a provider, etc. while having `"enableLogin": true` 

[Administrative Federation for QnABot with IAM Identity Center](https://catalog.us-east-1.prod.workshops.aws/workshops/20c56f9e-9c0a-4174-a661-9f40d9f063ac/en-US/deployment/optional-configurations/sso)

**Comment by jenia** [comment]
@israelias. Thank you kindly for your help and replies.
May I inquire please, how did you find out that I need "the whole curation `AmazonLexRuntimeBotsOnly`, namely `RecognizeSpeech, *Intent`"? I spend a lot of time doing trial and error IAM configuration by adding permissions piece meal so I want to find out how to find the curation of permissions for a specific task? That'll save me a lot of time adding permissions by analysing the error logs with missing permissions.

**Comment by israelias** [comment]
@jenia Trial and error as well, along with reading LexV2 API Docs. Once you see that `<stackname>-LexAccess-**` has pre-selected permissions ranging from PollySynthesizeSpeech to RecognizeIntent**, and once you plug and play other services, it'll be super clear that churning through input text (RecognizeText) is just one job function in the entire suite of paths to fulfillment c/o QnABot Solution.
