### ISSUE TITLE
Updates to vue component is not reflecting.

### ISSUE THREAD

**Issue by Shubham1500** [aws-samples/aws-lex-web-ui#725]
Hi Team,

This might be pretty obvious, but I am having issues as any updates to Vue component is not reflecting when running application from the parent folder.
Steps followed - 
1. Added a div in Message.vue, build the code and executed npm start from aws-lex-web-ui\lex-web-ui directory and able to see my changes on UI.
After that
2. Successfully ran make command on aws-lex-web-ui\dist directory. 
Running npm start on aws-lex-web-ui directory. 

I also tried to run npm run build-dist from ~/lex-web-ui and then copy the files from ~/lex-web-ui/dist/bundle to ~/dist

I am able to connect to Lex bot but any changes made to vue components are not reflected when I run from parent folder.

**Comment by atjohns** [comment]
This looks like a bug in the build that was introduced on last release, I will get a fix out asap.

**Comment by atjohns** [comment]
I will not get a new deployment out today but if you take the development branch version of vue.config.js you should be able to build successfully again.

[Corrected File](https://github.com/aws-samples/aws-lex-web-ui/blob/development/lex-web-ui/vue.config.js)

**Comment by Shubham1500** [comment]
Thanks for the prompt response @atjohns 
I will try this.

**Comment by Shubham1500** [comment]
@atjohns 
I tried updating the file you shared. 
Executed make command, and ran npm start on aws-lex-web-ui directory.

Still the updates made to .vue file is not reflected here.
If I run npm start in lex-web-ui directory I am able to see my changes on UI.

Additional details on changes - 
Downloaded code from github.
Updated lex-web-ui-loader-config with cognito and lex details. 
Updated Message.vue to add a div to test changes. 

Snippet - 

 <v-icon
                  v-if="message.type === 'bot' &&  message.id !== $store.state.messages[0].id && showCopyIcon"
                  class="copy-icon"
                  @click="copyMessageToClipboard(message.text)"
                >
                  content_copy
                </v-icon>
                **<div class="my-div">
                  <p>This is Shubham test div entry.</p>
                </div>**
                <v-icon
                  size="medium"
                  v-if="message.type === 'bot' && botDialogState && showDialogStateIcon"
                  :class="`dialog-state-${botDialogState.state}`"
                  class="dialog-state"
                >

**Comment by atjohns** [comment]
So your localhost version is showing the changes, but your deployed version is not. Can you walk me through your deployment steps?

Are you following the deployment steps outlined here: https://github.com/aws-samples/aws-lex-web-ui?tab=readme-ov-file#building-and-deploying-your-own-lexwebui

**Comment by Shubham1500** [comment]
Here is what I have done so far.
1. Downloaded code from Github, updated below files - 
   src\config\lex-web-ui-loader-config.json  - Updated Configs. 
   lex-web-ui\vue.config.js  - With the file you provided above.
2. After this I ran npm install and npm start and I am able to connect to Lex via Lex web UI.

Now the issue arises when I am adding new vue components in lex-web-ui/src /components.
I updated Message.vue component.

Tried couple things to build the project - 
a. Executed 'make' command at 'C:\Users\shubham.c.sharma\Shubh_Arena\Code\Git_code_public\Version2\aws-lex-web-ui\dist'   
b.  Ran npm run build-dist from aws-lex-web-ui\lex-web-ui and then copy the files from aws-lex-web-ui\lex-web-ui\dist\bundle to ~aws-lex-web-ui\dist  .


If I execute 'npm start' from aws-lex-web-ui\lex-web-ui\ directory I can see the changes on localhost reflected. (It displays order flower UI with my changes from vue component)
But If I run 'npm start' from parent directory aws-lex-web-ui I am not getting the changes reflected on localhost.

Please let me know if I am missing something here.
Thanks for your help.

**Comment by Shubham1500** [comment]
@atjohns
I discarded all changes, updated config files lex-web-ui-loader-config and the fix you shared.
Ran npm install and npm run dev on root folder and changes are reflecting now. 

Looks like the solution worked.
Thanks for prompt response.
