### ISSUE TITLE
Lex Web UI using Cognito Guest Access

### ISSUE THREAD

**Issue by sachindogne** [aws-samples/aws-lex-web-ui#727]
This issue has been flagged by our security team that the Lex Web UI is using Cognito Guest Access. We want to understand that the guest access is not a security risk.

Also please suggest if there's a workaround so that we don't have to use the guest access for our users.

**Comment by atjohns** [comment]
I am not aware of any security issues inherit to Cognito Guest Access as long as you operate under lease privileged when providing access to the guest role. The Web UI only provides the guest role with access to the bot, and you can see the exact privileges that are granted on the [cognito.yaml](https://github.com/aws-samples/aws-lex-web-ui/blob/master/templates/cognito.yaml) template to validate it meets your security criteria. If you have security concern specifically with the Cognito service I'd recommend putting a support ticket to get more information, as this solution simply leverages that service.

You can also refer to the [Credential Management portion of our README](https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/README.md#credential-management) for more in-depth explanation of how Cognito integrates into the solution.

To answer your final question, there is no way to get around Cognito guest access without forking and rewriting portions of the authentication in the Web UI. You can enable 'Force login' as outlined in the link above but the guest access role is still utilized but denies all access.
