### ISSUE TITLE
Need to postText in full page (not iframe)

### ISSUE THREAD

**Issue by cylinderStudio** [aws-samples/aws-lex-web-ui#73]
I've seen references to people getting postText to work outside the web-ui. I'm using the full-page example, which lacks the iframe API ability to, for example:

`return lexWebUiLoader.api.postText('Buy flowers')`

In absence of that, can someone point me to the global AWS object so I can do it manually? I can't find anything to hook onto to do that, and things like lexRuntimeClient or this.lexRuntimeClient are undefined. Thank you.

**Comment by CelticRugger** [comment]
need this too but also need to 
1) get the messages from the input (within the iframe)
2) disable lex if lex says cant continue and fulfillment has failed
3) used the input (not necessarily speech) for communicating to a new 3rd party web chat service (human agent)

to me this is a key priority of this project as its the kind of thing that needs to work in the real world and add serious value to lex related projects

I am urgently searching for a solution :-/

**Comment by jinot92** [comment]
Hi, Please refer this issue
https://github.com/aws-samples/aws-lex-web-ui/issues/106#issue-369125461
