### ISSUE TITLE
Webappbucket missing after update to 0.21.6

### ISSUE THREAD

**Issue by crazedout** [aws-samples/aws-lex-web-ui#745]
After updating lex-web-ui to version 0.21.6 I don't seem to have a UI installed anymore. Visiting the Cloudfront-URL in the Outputs gives an error code "NotFound". Looking for the WebAppBucket in S3 to check the files and there isn't a bucket visible or available. I followed the normal update procedure and everything i CloudFormation says it went well. Just before this update I've updated the QnABot to version 6.1.1. Before the update everything worked as expected.

If this takes long to remedy, is there a way to downgrade to the previous version?

**Comment by atjohns** [comment]
I was able to replicate this issue, going to rollback to the previous version. Will let you know when its done.

**Comment by atjohns** [comment]
Well I reverted to v0.21.5 and the issue is still occurring. New deployments are working however if its feasible for you to deploy a new stack instead of updating your existing stack please do so. I'm continuing to investigate

**Comment by atjohns** [comment]
Sorry to spam, but to clarify after rollback, if your deployment was broken a stack update does not restore the web app bucket. You will need to redeploy with a clean stack. If you deploy with v0.21.5 and then update, that appears to work correctly. I believe this was related to the S3Cleanup process. Apologies.

**Comment by atjohns** [comment]
After further investigating this is happening because of two issues...

- The custom resource got updated with new parameters to handle the VPC toggles, this appears to be a [known behavior](https://stackoverflow.com/questions/50599602/updating-custom-resources-causes-them-to-be-deleted) where it wants to delete the custom resource because of generating a new ID. Normally, not a problem
- Unfortunately the S3CleanUp Lambda function gets triggered during this time, and its looking for a 'DELETE' call to clean up the S3 web app bucket. It sees this delete and incorrectly thinks you are deleting your stack, when in fact the stack is updating but deleting a custom resource. 

I think the right thing to do here is make the CleanUp Lambda more specific, which I will investigate.

**Comment by crazedout** [comment]
I've deleted the stack from Cloudformation and are trying to do a clean install. However, I've run into some kind of problem during the reinstall process. See the attached image for error details. I've gotten the same error twice. It's probably something I'm doing wrong.
![2024-10-07_13h00_00](https://github.com/user-attachments/assets/273b762d-014f-4cbe-8e51-54f19a89add1)

**Comment by atjohns** [comment]
I have not seen that one before, its failing very early though and the message leads me to think its a VPC issue (which shouldn't even be deployed now with the rollback). Can you confirm that you don't see any of the VPC parameters when you deploy the stack? Also can you share the region so I can make sure the rollback didn't fail in a specific region?

**Comment by crazedout** [comment]
I'm deploying in the eu-central-1 region. I didn't see any VPC parameters in the stack creation, if that is what you mean. And yes, I'm sure that I use the correct link from the github page.

**Comment by atjohns** [comment]
I was able to deploy the Web UI into eu-central-1 without issue. This could be caused by the previous deployment not being removed entirely. I would double-check that and potentially give this stack a different name than the failed upgrade to v0.21.6 stack

**Comment by crazedout** [comment]
Ok, my installation problem turned out to be because I used the link instead of the "Launch" button. Feels weird that it didn't work, but now I have a new install. Thank you for your patience! Hope you find a solution for the initial update problem.

**Comment by sarah-chua** [comment]
Hi, may I know when a fix for this will be available or do we stick to 0.21.5 for now? 

I faced the same issue of the Webappbucket being deleted when trying to deploy from my own bootstrap bucket with 0.21.6. It worked after reverting back to 0.21.5.
