### ISSUE TITLE
Developer experience opinion

### ISSUE THREAD

**Issue by simonstewart-aishop** [aws-samples/aws-lex-web-ui#749]
The process of creating an Amazon Lex V2 chatbot and testing it within the AWS Console "test" window is pretty easy but I can't help but feel the process of actually surfacing it to users is more work than needed.

I've looked for simple step-by-step tutorials but the closest I've found is going via Kommunicate which defeats the purpose in my opinion.

Surely the point of Amazon Lex is to surface this to users and doing that via a website would be the primary mode?

My expectation going into this was that showing a chatbot overlaid onto an existing site would be something like:
```
<script src="some-cdn/lex-web-ui-loader.js"></script>
<script>
  new ChatBotUiLoader.SomeLoader({someConfigs...}).load();
</script>
```

But it seems I need a standalone page hosting the chatbot which is then iframe'd into an existing site.

There is a lot of info on this repo but it's a pain to separate all the samples and figure out what's actually needed to get something running. The CloudFormation samples, while comprehensive, will probably take more time to unravel than just looking for an alternative approach.

This isn't meant to be a complaint; it's just an observation from a web dev who was hoping to get the Lex bot running on an existing site quickly.

Although I've spent some time going through the README's, I'm happy to be proven wrong as I must be missing something.

**Comment by atjohns** [comment]
If you run the CloudFormation template linked on the main GitHub README and only fill in your Lex bot parameters and parent page domain, it will basically just work as you describe (the embed is slightly different code that what you put but pretty close).

There are a ton of extra features that you would not need to concern yourself with on this GitHub, but a vanilla deployment is straightforward. But yes this repo is designed to cover a wide range of use cases so there is some complexity here.
