### ISSUE TITLE
Anyone can explain how to intercept outgoing incoming chat messages and lex bot incomplete

### ISSUE THREAD

**Issue by CelticRugger** [aws-samples/aws-lex-web-ui#77]
From the chat
Catch actual raw user message text going out to the lex channel (posted)  from the chatUI
Catch full message responses returned from amazon lex to the chatUI + all the other struct objects
plus know that chat could not complete / fulfilment failed - and lex says could not complete task. This is important to maybe then instantiate another service to bring in a human agent.

Appreciate if someone could give some basic guidance how to capture these things as this add weight to this overall solution in a customer sense.  A bit of clarification would help clear up this mechanism.

Kind regards,

    Karl

**Comment by kirstenEhlers** [comment]
Just to clarify, do you want to obtain kind of like a transcript? I did this by invoking a lambda in push message in the lex-web-ui.js file. The lambda can take the input and session attributes as parameters
