### ISSUE TITLE
Parent.Html document.one - should be "on" 

### ISSUE THREAD

**Issue by CelticRugger** [aws-samples/aws-lex-web-ui#78]
*******************>>>  should be on
        $(document).one('receivelexconfig', function onReceiveLexConfig() {
          var localTimeZone;
          try {
            localTimeZone = JSON.stringify(
              Intl.DateTimeFormat().resolvedOptions().timeZone
            );
          } catch (err) {
            localTimeZone = JSON.stringify(
              new Date().getTimezoneOffset()
            )
          }

**Comment by JohnCalhoun** [comment]
can you explain why this should be on vs one?

**Comment by CelticRugger** [comment]
looks like a typo bug to me.
