### ISSUE TITLE
response cards from lambda functions

### ISSUE THREAD

**Issue by pocppib** [aws-samples/aws-lex-web-ui#80]
Are there any limitations with response cards from lambda functions?  I have one that displays fine in the test bot console but I can't get it to display in the web ui.

**Comment by CelticRugger** [comment]
i think its a lex issue. change output from facebook to slack or kik. do this for your cards  save intent build publishm it starts working. i had that issue. if you edit that intent i think it resets to facebook so watch for that problem. Amazon need to start fixing these bugs. Regardless of setting in cards it should work so maybe its more a lex ui problem. change card target type from facebook thought seems to display it in lex ui.

regards



Sent from my Samsung Galaxy S6 - powered by Three


-------- Original message --------

**Comment by pocppib** [comment]
Thanks CelticRugger, ends up it was the "title" field under "genericAttachments".  Technically it's optional, so I didn't include it (I was just returning a message with an image), but it works now that I added it.

**Comment by sasankmukkamala** [comment]
In my case it was "version" field. (Again, it is technically optional). [Source](https://github.com/aws-samples/aws-lex-web-ui/blob/731bb598c9d2f78a380c6020d0f9c3826ddc89aa/lex-web-ui/src/components/Message.vue#L132)

**Comment by bshelling** [comment]
It's absolutely the version field if you're using version 0.14.2
