### ISSUE TITLE
Query- FallBack Intent

### ISSUE THREAD

**Issue by leeu3581** [aws-samples/aws-lex-web-ui#81]
Hi,

Do you know if the built in [FallBack intent](https://developer.amazon.com/blogs/alexa/post/c97f3bb7-9701-41e8-ac06-a3a44b9f1638/use-the-new-fallback-intent-to-respond-gracefully-to-unexpected-customer-requests) available for Alexa will be made available for Lex? And if so, do you know when it will be released?

Thanks.

**Comment by JohnCalhoun** [comment]
I dont know about lex, but we can start utilizing the Alexa Fallback intent, what would be the desired behavior for a QnABot Fallback intent?
