### ISSUE TITLE
Major Bug : Microphone listening captures 0.5 secs of TTS speech before human starts speaking causing transcription errors

### ISSUE THREAD

**Issue by CelticRugger** [aws-samples/aws-lex-web-ui#82]
if you listen to the speech samples in the bot window you can clearly here 0.5 of Text to speech voice clipped before the human voice sample plays.  It's clear the sample on the microphone is starting too early in the collection process.  What this does is create failures in the speech recognition, and lex can get it wrong. Clearly a bug or a setting issue.   This is a pretty major one.

**Comment by rstrahan** [comment]
Hi @CelticRugger - look at the default config settings (see https://github.com/aws-samples/aws-lex-web-ui/blob/master/lex-web-ui/src/config/index.js) - specifically the 'recorder' section, where you can play with volume thresholds for silence detection and trimming, and even disable silence trimming (encoderUseTrim).
