### ISSUE TITLE
Concurrent Users

### ISSUE THREAD

**Issue by deepblue2** [aws-samples/aws-lex-web-ui#89]
It doesn't seem as if users can concurrently interact with the sample GUI, maintaining separate conversations with the Lex Flowers bot.  What change would be needed to make sure that the userID's in the postText/postContent requests were different for different users?

**Comment by bobpskier** [comment]
I believe userId will be different for different users. Note, the userId will be the same when using the same browser instance but in a different tab or window. The userId is derived from the credentials obtained via the Cognito pool (unauthenticated use case) which is setup during install of the lex web ui. This credential is cached in the browser's local storage. Hence if you spin up two tabs to the lex web ui in the same browser and then alternate input to the lex web ui between these, you'll be the same user. If however you bring up a different browser on the same system or bring up a browser on a different system, the userIds will be different and will not share the same session with lex. If you are testing concurrent users in a way you believe should result in different userIds but are not, please post the use case.

**Comment by deepblue2** [comment]
Thanks.  That clarifies why I was unable to get concurrent sessions running within the same browser.
